### PR TITLE
Fix #5438 - DataTable: cleanup sorting

### LINKED ISSUE #2601: DataTable: with dynamic column looses sorting on refresh
## 1) Environment
- PrimeFaces version: 6.1.3

## 2) Expected behavior
When you rerender a sorted datatable with dynamic columns the sorted column should keep the style class "ui-state-active" 

## 3) Actual behavior
All columns are now "active"

## 4) Steps to reproduce
See also example zip for prepared test [primefaces-datatable-column-sort.zip](https://github.com/primefaces/primefaces/files/1197195/primefaces-datatable-column-sort.zip)
            
## 5) Sample XHTML

   ```
 <p:commandButton update="cars" value="refresh"  icon="ui-icon-refresh"/>
            <p:dataTable id="cars" var="car" value="#{dtColumnsView.cars}" widgetVar="carsTable">
                <p:columns value="#{dtColumnsView.columns}" var="column" columnIndexVar="colIndex"
                           sortBy="#{car[column.property]}">
                    <f:facet name="header">
                        <h:outputText value="#{column.header}"/>
                    </f:facet>
                    <h:outputText value="#{car[column.property]}"/>
                </p:columns>
            </p:dataTable>
```

## 6) Analysis

When a table is sorted the current sorting is saved by SortFeature.java in the table sortBy property

```
ValueExpression sortByVE = sortColumn.getValueExpression(Column.PropertyKeys.sortBy.toString());
table.setValueExpression(DataTable.PropertyKeys.sortBy.toString(), sortByVE);
```

**Notice that for dynamic columns this is always the same string.** In the example it will be always "#{car[column.property]}" 

When the table is refreshed each column checks if it is currently sorted by comaparing against this string. But because all strings are the same all columns calculate that they are active. org.primefaces.component.datatable.DataTableRenderer#resolveDefaultSortIcon:

```
if((sortField != null && field != null && sortField.equals(field)) || (tableSortByExpression != null && 
  tableSortByExpression.equals(columnSortByExpression))) {
      if(sortOrder.equalsIgnoreCase("ASCENDING"))
           sortIcon = DataTable.SORTABLE_COLUMN_ASCENDING_ICON_CLASS;
       else if(sortOrder.equalsIgnoreCase("DESCENDING"))
           sortIcon = DataTable.SORTABLE_COLUMN_DESCENDING_ICON_CLASS;
        }
```

## 7.) Workaround
For now it seems to work when I override resolveDefaultSortIcon in a simpler custom renderer:

 ```
  protected String resolveDefaultSortIcon(DataTable table, UIColumn column, String sortOrder) {
     String sortIcon = null;
     if(column.equals(table.getSortColumn())) {
       if(sortOrder.equalsIgnoreCase("ASCENDING"))
         sortIcon = DataTable.SORTABLE_COLUMN_ASCENDING_ICON_CLASS;
       else if(sortOrder.equalsIgnoreCase("DESCENDING"))
         sortIcon = DataTable.SORTABLE_COLUMN_DESCENDING_ICON_CLASS;
     }
     return sortIcon;
   }
```

### LINKED ISSUE #3347: DataTable: Pass nulls to the sortFunction or make the nullSortOrder column-specific
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 7
- Affected browsers: Firefox 57

## 2) Problem description
When sorting a column in a `<p:dataTable />` there is the possibility to define a custom `sortFunction`. However, within this sort function the user has no access to `null ` values as they are already dealt with by the `BeanPropertyComparator#compare` method.

While it is possible to define the `nullSortOrder` on the table (which decides whether nulls should be first or last) this approach has two problems:
1. nulls can never be "in the middle"
2. All columns in the table have to follow the same strategy. It is impossible to have column A follow the "nulls first" strategy while column B follows the "nulls last" strategy.

## 3) Suggested solutions
1. Add the attribute `nullSortOrder` to the column. This would allow different columns to implement different strategies how they can deal with null values. If there is the `nullSortOrder` attribute set on the column, it should overwrite the value of the table.
2. Let the implementer of the sort function deal with nulls. I think when you already offer to make a custom implementation it is not to much to ask of the implementer to deal with null values. Most Java programmers should be used to it anyway when they implement custom Comparators or Comparable classes.

### LINKED ISSUE #5438: DataTable: cleanup sorting
Filters previous had 3 similar attributes:
Filters
FilterBy
FilterMeta

we should check the same for sorting.

All properties related to sort:
* sortMeta
* sortField
* sortBy
* sortOrder
* sortFunction
* sortMode (single | multiple)
* allowUnsorting

Some facts:
1) it seems like sortBy and sortField is similar. One points to a fieldname of the entity, one is a VE? @Rapster Maybe you have a better overview here?
2) if sortMode = multi, sortMeta is the source of all sort informations
3) if sortMode = single, sortBy+sortOrder+sortFunction is used
4) in general, sortMeta is just a collection of (sortBy+sortOrder+sortFunction) for mulitple columns. So multiSort is actually the same thing as singleSort, just that sortMeta could only contain 1 value instead of multiple.

Goals (Reduce attributes to):
* sortBy (a map of SortMeta, multisort will contain mulitple values, singlesort only 1 value)
* initial sorting can by defined by sortOrder and sortPriority on p:column
* allowMultiSort (sortMode before, default = true?)
* allowUnsorting
* remove old attributes from PropertyKeys+taglib and throw a exception in getter/setter

### LINKED ISSUE #6372: DataTable: headerRow refactoring
**Description**
Based on https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml

**Describe the solution you would like**
As I started to have a look at #5438, `DataTable#sortBy` is used for grouping feature. And since the idea is to remove `DataTable#sortBy` I wonder how to make row grouping working... The way I see it, we should be able to simply configure row grouping like this:
```xml
<p:dataTable var="car" value="#{dtRowGroupView.cars}">

    <p:headerRow groupBy="#{car.brand}" expandable="true" />

    <p:column headerText="Year">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
</p:dataTable>
```

**Additional context**
My idea is to give slightly less responsability to DataTable which already contains a lot of attributes. Also, I like the idea that headerRow component is the determinist element _(carrying all sorts of attributes)_ that will activate the feature, just like `Column#groupRow` does.

As of today, headerRow has to contain at least one column. I don't have any scenario where several columns would be needed but I guess it can be solved with a facet if user wants to do so.

Anyway, let me know what you think?

### LINKED ISSUE #6468: Datatable: multi-sort loses order with lazy
**Describe the defect**
I've a table with columns [a,b,c,d,e] and lazy initialization. When I provide an intilial list of sortmeta (c, a) it sorts data correctly. But, If I change page, It loses sortmeta order (a, c). For example:

After apply sort columns:
- sortMeta: c DESC, a DESC

After change page (a and c got swapped):
- sortMeta: a DESC, c DESC 

**Environment:**
 - PF Version: 8.0
 - JSF 2.3: Jakarta faces 2.3.14
 - Affected browsers: ALL

**Expected behavior**
Maintain sortmeta order with pagination. 

**Example XHTML**
```html
<p:dataTable scrollable="true" scrollHeight="auto" rows="#{exampleBean.session.nReg}" first="#{exampleBean.session.nPage}" id="dtExample" paginator="true" paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" rowsPerPageTemplate="20,50,100" emptyMessage="Empty table" value="#{exampleBean.dataSource}" var="rec" paginatorAlwaysVisible="true" currentPageReportTemplate="{totalRecords}" selection="#{exampleBean.selectedRecords}" rowKey="#{rec.uid}" sortOrder="descending" style="font-size: 0.9em !important;" lazy="true" sortMode="multiple" styleClass="myTooltip" rowIndexVar="rowIndex" rowStyleClass="#{exampleBean.styleClazz(rec)">
        <p:column selectionMode="multiple" style="width:16px;text-align:center" exportable="false"/>
	<p:column headerText="A" sortBy="#{rec.a}">#{rec.a}</p:column>
        <p:column headerText="B" sortBy="#{rec.b}">#{rec.b}</p:column>
        <p:column headerText="C" sortBy="#{rec.c}">#{rec.c}</p:column>
        <p:column headerText="D" sortBy="#{rec.d}">#{rec.d}</p:column>
	<p:column headerText="E" sortBy="#{rec.e}">#{rec.e}</p:column>
</p:dataTable>
```

### PR DESCRIPTION
**Pull request by Rapster**
**Remove**:
- DataTable#sortMeta _(replaced by DataTable#sortBy)_
- DataTable#sortField _(replaced by UIColumn#field)_
- DataTable#sortOrder _(replaced by UIColumn#sortOrder)_
- DataTable#sortFunction _(replaced by UIColumn#sortFunction)_
- DataTable#expandableRowGroups _(replaced by HeaderRow#expandable)_
- DataTable#nullSortOrder _(replaced by UIColumn#nullSortOrder)_
- DataTable#caseSensitiveSort _(replaced by UIColumn#caseSensitiveSort)_

**Update**
- DataTable#sortMode: default value "multiple"
- DataTable#allowUnsorting" default value "false"
- DataTable#sortBy: expects a single or a collection of SortMeta _(default sorting can either be configured through markup or programmatically)_

**Add**
- Column#sortPriority: defines in which order columns sorter should apply initially
- Column#sortOrder
- Column#nullSortOrder
- Column#caseSensitiveSort
- #6372

**Breaking changes**
- DataTable#sortBy: no longer expect a Map, but a single or a collection of SortMeta _(use SortMeta#builder)_ `UIColumn#field` or `UIColumn#sortBy` must be set to enable default sorting.
- As it is possible from now on to configure default sorted columns on a single sort mode datatable. Users will be expected to implement only one method `LazyDataModel#load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy)`

### CODE REVIEW

**Comment by tandraschko** [comment]
in general it looks quite good, just some points from my first rough review:
1) why not store the sortMeta as sortBy? So we are similar to filterBy and the user could theoretically build it like he want via a Bean.
2) you init sortMeta as component var via PostAddToView; i'm not sure if this works correctly for all cases like MyFaces ViewPooling. Also in Mojarra its sometimes called 2 times in the past. We should in general avoid to store "state" in variables - use the stateHelper here like stated in 1) - 2 birds 1 stone.

**Comment by Rapster** [comment]
Thanks Thomas for your feedbacks.
 
1. The reason why I don't store sortMeta just like sortBy used to do, it's simply because sortMeta is a map and sortBy shouldn't be a map but a list. Users shouldn't bothered figuring out what client id their column would be, on top of that, SortMeta is not really API friendly since it expects columnKey, clientId, value/method expressions... The backing code is quite horrible if you have to configure default sorting... But! I'm working on reintroducing `DataTable#sortBy` in this PR. I'm surely will be able to do something about it. Ideally, it should look like this:

```xml
<p:dataTable var="car" value="#{dtSortView.cars1}" sortBy="#{dtSortView.sorters}">
    <p:column headerText="Id" field="id" />
    <p:column headerText="Year" field="year" />
    <p:column headerText="Brand" field="brand" />
    <p:column headerText="Color" field="color" />
</p:dataTable>
```
`dtSortView.sorters` being a list of SortMeta introducing a new constructor:
```java
    public class SortMeta {

        // attributes

        public SortMeta(String sortField, SortOrder sortOrder, ValueExpression sortBy, MethodExpression sortFunction, Integer priority) {
            // init attributes
        }
    }
```

Finally, you'll be able to configure default sorting through markup or programmatically.

2.  Yes that something I recently realized, few attributes are stored in statehelper and some are not which creates a lot of confusion and issues. I'm gonna try to figure something out so sortMeta is stored in statehelper. I quite like the PostAddToView initilization, that's something we do already for `p:columns`. I don't see how to initialize sortMeta without it...

**Comment by tandraschko** [comment]
Can't we make sortMeta just a list and a add a constructor, like you mentioned, for easy enduser construction? :D (+ rename to sortBy)
We should just align with with filters, we may also think about filterBy/filterMeta then.

**Comment by Rapster** [comment]
Well, having a map makes things so much easier (and actually faster). Even we were turning sortMeta into a list, you still need to sync internal sortmeta and sortBy (defined by the user)  in order to set the column, columnkey _(you can't make it one unique property, I tried, it will create other issues)_. 

I managed to put the sort metas into the statehelper. So far I've been using PostAddToView event to trigger that sync, which looks like the most appropriate place to do so. I don't know much about view pooling but sounds like a particular feature of MyFaces, but in both impl PostAddToView event should be either called during restore view or render response phase. I guess you're referring to #2110?

I'll rename the attribute sortMeta into sortBy later, and yes filters should work the same way (I'm planning to work on it once I'm done with this PR)

**Comment by tandraschko** [comment]
thats the problem, PostAddToView is called only once per cached view AFAIR. Just dont rely it on, always get the Map via StateHelper and update

**Comment by Rapster** [comment]
> thats the problem, PostAddToView is called only once per cached view AFAIR.

You mean during an ajax request for example?

This is something I'm doing now, but I still need to execute the initilization of sortMetas, where should i do it if it's not in PostAddToView?

**Comment by tandraschko** [comment]
Views are reused for multiple requests and its only fired in one request probably.
Just lazy init?

**Comment by Rapster** [comment]
>Views are reused for multiple requests and its only fired in one request probably.

Ok, from what I can see PostAddToView is called for every request I made on showcase (navigation, refresh, ajax)

> Just lazy init?

This is something I tried the very first time, as a quick & dirty approach... Lazy initialization is something that I hate, basically you lose control of your attributes, for example I can't tell you when exactly "sort by metas" are initialized... But right now, I finally managed to make it work 😄

File: src/main/java/org/primefaces/component/datatable/DataTable.java [hunk 1]
```diff
@@ -25,11 +25,13 @@
 
 import java.lang.reflect.Array;
 import java.util.*;
+import java.util.List;
```
Comment (melloware) [inline src/main/java/org/primefaces/component/datatable/DataTable.java]: Not sure why it imported List when java.util.* was above it?

**Review by melloware — CHANGES_REQUESTED** [review]
This looks good to me but i assume there are some HeaderRow and Datatable 9.0 MD docs that need updating as well?

**Comment by Rapster** [comment]
I'll deal with the docs once PR reviewed

**Comment by christophs78** [comment]
I´ll do a testdrive later this week. And i´ll update / extend our integration-tests.

**Review by melloware — APPROVED** [review]

**Comment by christophs78** [comment]
When i build your PR one unittest fails:
`[ERROR]   DataTableTest.testAllowUnsorting:44 expected: <true> but was: <false>`

**Comment by christophs78** [comment]
Just made a draft-PR for out integration-tests: https://github.com/primefaces-extensions/primefaces-integration-tests/pull/54/files
@Rapster: Did i adapt them as intended by you?

**Comment by christophs78** [comment]
Additional to documentation and integration-tests we need to update showcase after this PR is done.
I´ll try to add some more integration-tests on top of our existing ones.

**Comment by Rapster** [comment]
Hi @christophs78 

Thank you for taking time to test that PR. I'll have to start to have a look to these integration-tests, sounds quite interesting. Regarding the error, yes `DataTable#allowUnsorting` default value has been modified to false. Any plan to move these ITs into primefaces repo? Since you're probably the first to have a look to this PR with Thomas, feel free to give any feedbacks :wink:

File: src/main/java/org/primefaces/component/datatable/DataTable.java [hunk 2]
```diff
@@ -1547,50 +1411,134 @@ public void resetMultiViewState() {
...
+
+        // merge internal sortBy with user sortBy
+        if (sortByTmp != null) {
+            Collection<SortMeta> sortBy;
+            if (sortByTmp instanceof SortMeta) {
+                sortBy = Collections.singletonList((SortMeta) sortByTmp);
+            }
+            else if (!(sortByTmp instanceof Collection)) {
+                throw new FacesException("DataTable#sortBy expects a single or a collection of SortMeta");
+            }
```
Comment (christophs78) [inline src/main/java/org/primefaces/component/datatable/DataTable.java:1468]: Would it be theoretically possible to add there some kind of backward-compatibility? (Convert PF<=8  sortBy into SortMeta and write warning to log.)
I don´t want to say this is a good idea. Just thinking about it.

Comment (Rapster) [reply src/main/java/org/primefaces/component/datatable/DataTable.java:1468]: True, on one hand it can easily be done, on the other hand, since clients will have to do a bit of cleanup of their tables it might be the best opportunity for them to change their sortBy than wait till the backward compatibility is removed ... The decision is up to @tandraschko

**Comment by Rapster** [comment]
Any idea when this PR could be reviewed?

**Comment by tandraschko** [comment]
~1-2 weeks, dont have many time to review this big PR and i have a deadline here

**Comment by tandraschko** [comment]
@Rapster @melloware should we move the migration guide to the offical docs here? So rapster could also prepare the migration guide, it would be much easier to get a overview of the changes when we could first check the migration guide changes

**Comment by Rapster** [comment]
You mean adding a subsection "Migration guide" in "Getting Started" section for example? Anyway, yes sounds like a good idea

**Comment by melloware** [comment]
Agreed. That way we could keep it with each set of docs per version.

**Comment by tandraschko** [comment]
yep

**Comment by melloware** [comment]
I can backfill the Migration Guide section in the 7.0 and 8.0 docs if you handle the 9.0 version @Rapster ?

**Comment by tandraschko** [comment]
i will do it for all versions now, @Rapster can just add his new changes :)

**Comment by Rapster** [comment]
Sounds good

**Comment by tandraschko** [comment]
we added the migration guide now, could you add it to your PR?

**Comment by Rapster** [comment]
Not yet, I was waiting for your review before modifying the docs

**Comment by tandraschko** [comment]
it would be much easier for me to get an overview of your changes  :D

**Comment by Rapster** [comment]
I'm working on it, but if that's an overview you want, you can read it from [here](https://github.com/primefaces/primefaces/pull/6390#issue-497711470) 😄

**Comment by melloware** [comment]
Looks like there are conflicts too.

**Comment by tandraschko** [comment]
@Rapster Just to be sure:
1) the sortMeta is built with columnKey as map key 
2) Initial SortMeta must be built with field or sortBy
3) columnKey == clientId
4) initialSortMeta will search the right columnKey via field || sortBy

What is with https://github.com/primefaces/primefaces/pull/5407? The PR doesnt solve/change this behavior currently, so we still have field and sortBy, right?

I wonder if we should do the following:
Allow to set the columnKey on p:column (maybe just a "key" attr) and allow the SortMetaBuilder to use the columnKey to build the initial sortMeta. Maybe better as field || sortBy but requires another attribute.
So maybe we should talk about 5407 first.

**Comment by tandraschko** [comment]
Or even better: columnKey == id attr of the column (not clientId), so we dont need a new attr or rely on field/sortBy in our Builder

**Comment by Rapster** [comment]
> @Rapster Just to be sure:
> 
> 1. the sortMeta is built with columnKey as map key

Yes

> 2. Initial SortMeta must be built with field or sortBy

Yes
> 3. columnKey == clientId

Yes
> 4. initialSortMeta will search the right columnKey via field || sortBy

Yes via field, sortBy is used to deduce field if not defined

> What is with #5407? The PR doesnt solve/change this behavior currently, so we still have field and sortBy, right?

This PR does a better a job in terms of resolving the field from a VE, but it doesn't do anything regarding sorting

> I wonder if we should do the following: Allow to set the columnKey on p:column (maybe just a "key" attr) and allow the SortMetaBuilder to use the columnKey to build the initial sortMeta. Maybe better as field || sortBy but requires another attribute.

My first initiative was actually to get rid of `UIColumn#columnKey`, and replace it with `UIColumn#field`. At least one reason I didn't do so, it turns out people use sometimes same field for different columns, see #6421, don't know why but it happens... 

> So maybe we should talk about 5407 first.

Right now this is not the topic, but once this PR and the other about filtering will be merged, I will merge #5407

> Or even better: columnKey == id attr of the column (not clientId), so we dont need a new attr or rely on field/sortBy in our Builder

Yeah but people still need to know id of the columns, less painful than clientId for sure but remains tricky. I don't think we should bother too much about this, UIColumn#field should be the key and if people need several columns for the same field then they should add more field to their backing beans/view objects.

**Comment by tandraschko** [comment]
ok i see.
Shouldnt we then better remove #columnKey and use #clientId directly? But this wouldnt work for p:columns probably?

**Comment by Rapster** [comment]
Yeah but whether it's columnKey or clientId, problem is the same, we'll have to loop over sortMeta to find the right match. If it was UIColumn#field it would be a lot more easy to achieve. But right now, let's keep columnKey...

**Comment by tandraschko** [comment]
ok. Did you test your PR with dynamic columns/p:columns? how is the columnKey constructed there?

**Comment by Rapster** [comment]
This PR has been tested will all showcases, for p:columns a subset of DynamicColumns is created:
```java
            if (child instanceof Columns) {
                Columns uiColumns = (Columns) child;
                String uiColumnsClientId = uiColumns.getClientId(context);

                for (int j = 0; j < uiColumns.getRowCount(); j++) {
                    DynamicColumn dynaColumn = new DynamicColumn(j, uiColumns);
                    dynaColumn.setColumnKey(uiColumnsClientId + separator + j);
                    columns.add(dynaColumn);
                }
            }
```

**Comment by tandraschko** [comment]
ups, unsure if i selected "squashe and merge" :D

Thanks for effort @Rapster , i really enjoy the result.
Please update the showcase by yourself.

Could you also please update filtering in the same level now? (Builder for initial filterBy and that stuff)

**Comment by melloware** [comment]
From what I can tell it looks like you squashed and merged correctly.

**Comment by Rapster** [comment]
Thanks Thomas,

It's okay, I can do the merge next time :wink: but yeah squashing commits is pretty cool to avoid cumbersome/messy history (specially that, sometimes I don't bother too much in my commit messages).

I'll update showcase and prepare filtering PR

**Comment by melloware** [comment]
We will update all the Datatable Integration Tests and let you know if we find any issues.
