### PR TITLE
Fix #95 and #171: Charts escape non numeric data consistently.

### LINKED ISSUE #95: Chart fails with java.util.Date based model
While the p:lineChart serializes a java.util.Date correctly and adds quotation marks around the resulting string:

``` javascript
PrimeFaces.cw('LineChart','widget_j_idt6_test',{id:'j_idt6:test',data:[[ .... ,categories:['Tue Jan 01 00:00:00 CET 2013','Wed Jan 02 00:00:00 CET 2013', ....
```

The new p:chart component fails badly:

``` javascript
PrimeFaces.cw('Chart','widget_j_idt6_j_idt8',{id:'j_idt6:j_idt8',type:'line',data:[[[Tue Jan 01 00:00:00 CET 2013,1633],[Wed Jan 02 00:00:00 CET 2013,1595],
```

As you can see this not valid javascript anymore.

The code that generates this:

Backing bean:

``` java
@Named("demosource")
@javax.faces.view.ViewScoped
public class DemoSource implements Serializable {
    private CartesianChartModel model;

    public DemoSource() {
        model = new CartesianChartModel();

        ChartSeries series = new ChartSeries("Server 1");

        Calendar now = new GregorianCalendar(2013, 0, 1);

        for(int i = 0; i < 1500; i++) {
            series.set(now.getTime(), 1500 + ((int) (200 * Math.random())));
            now.add(Calendar.DAY_OF_MONTH, 1);
        }
        model.addSeries(series);

        DateAxis axis = new DateAxis("Dates");
        axis.setTickCount(30);
        axis.setTickAngle(30);
        model.setZoom(true);
        model.getAxes().put(AxisType.X, axis);
    }

    public CartesianChartModel getModel() {
        return model;
    }
}
```

Demo site:

``` xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
        <h:outputScript name="jquery/jquery-plugins.js" library="primefaces"/>
    </h:head>
    <h:body>
        <h:form>
            <p:lineChart id="test" value="#{demosource.model}" title="Server Auslastung" style="height: 300px" />
            <!--<p:chart type="line" model="#{demosource.model}" style="height: 300px" />-->
        </h:form>
    </h:body>
</html>
```

This is the "working" sample (slow, but works), if you disable p:lineChart and enable p:chart you can see the problem.

### LINKED ISSUE #171: ohlc charts not working using dateaxis with date
Hello,

Primefaces use jqplot to display ohlccharts.

From examples available at this location: http://www.jqplot.com/tests/date-axes.php dates data are encapsulated by **simple quotes**.

``` javascript
$(document).ready(function(){
  var line1=[['2008-09-30 4:00PM',4], ['2008-10-30 4:00PM',6.5], ['2008-11-30 4:00PM',5.7], ['2008-12-30 4:00PM',9], ['2009-01-30 4:00PM',8.2]];
  var plot1 = $.jqplot('chart1', [line1], {
    title:'Default Date Axis',
    axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer}},
    series:[{lineWidth:4, markerOptions:{style:'square'}}]
  });
});
```

It's not the case from javascript script generated by primefaces:

``` javascript
$(function(){PrimeFaces.cw('Chart','widget_j_idt357',{id:'j_idt357',type:'ohlc',data:[[[2015-04-23,30.0,120.0,12.0,110.0],[2015-04-24,90.0,102.0,10.0,110.0]]],title:"Evolution du cours",axes:{xaxis: {label:"Date",max:"2015-04-30",renderer:$.jqplot.DateAxisRenderer,tickOptions:{angle:"-50"}},yaxis: {label:"Valeur",renderer:$.jqplot.LinearAxisRenderer,tickOptions:{angle:"0"}}},datatip:true},'charts');});
```

I have lived executed the code in my firebug console with single quotes and it is working. 

Can you add quotes in the file OhlcRenderer line 39 (checked in Primefaces 5.1). This problem may affect other charts type.

Thanks by advance.

Regards,

Damien

### PR DESCRIPTION
**Pull request by melloware**
Fix #95 Dates issue not wrapped in quotes in charts
Fix #171 OHLC chart not escaped consistently.

Went through all charts making their data  elements consistent by:

- If Data is NULL then the word "null" is used
- If Data is a Number then its not wrapped in Quotes all others are quoted such as Date, String, etc
- Escape the JSON data in case the String value has a character that needs to be escaped.

### CODE REVIEW

**Comment by melloware** [comment]
@jxmai any idea why this commit is failing the Travis build?  I can't tell from the errors?

**Comment by tandraschko** [comment]
Seems like 4 unused imports: https://travis-ci.org/primefaces/primefaces/jobs/286211819

**Comment by jxmai** [comment]
Can you build locally ? The checkstyle does not allow to have unused import

```
[ERROR] src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java:[26,8] (imports) UnusedImports: Unused import - org.primefaces.util.ComponentUtils.
[ERROR] src/main/java/org/primefaces/component/chart/renderer/DonutRenderer.java:[26,8] (imports) UnusedImports: Unused import - org.primefaces.util.ComponentUtils.
[ERROR] src/main/java/org/primefaces/component/chart/renderer/LineRenderer.java:[26,8] (imports) UnusedImports: Unused import - org.primefaces.util.ComponentUtils.
[ERROR] src/main/java/org/primefaces/component/chart/renderer/PieRenderer.java:[24,8] (imports) UnusedImports: Unused import - org.primefaces.util.ComponentUtils.
```

File: src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java [hunk 1]
```diff
@@ -37,14 +37,14 @@ protected void encodeData(FacesContext context, Chart chart) throws IOException
...
             writer.write("[");
-            writer.write(String.valueOf(s.getX()));
+            writer.write(escapeChartData(s.getX()));
             writer.write(",");
-            writer.write(String.valueOf(s.getY()));
+            writer.write(escapeChartData(s.getY()));
             writer.write(",");
-            writer.write(String.valueOf(s.getRadius()));
-            writer.write(",\"");
-            writer.write(ComponentUtils.escapeText(String.valueOf(s.getLabel())));
```
Comment (jxmai) [inline src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java:46]: Once you remove this line. ComponentUtil becomes unsed

**Review by jxmai — COMMENTED** [review]
Here is the problem

File: src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java (hunk 1 above)
Comment (jxmai) [reply src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java:46]: The same reason for the other three classes, so you just need to remove the componentUtil import line

**Comment by melloware** [comment]
Ah!  Will fix. I went back through my changes and tried to make them as minimal as possible. Whoops!

**Comment by sorny** [comment]
I think `escapeChartData` should do some String sanitation? Having an additional quote e.q. "Stan's X-Value" would brick the chart data now right?

**Comment by melloware** [comment]
@sorny It does.  The method escapeChartData does "ComponentUtils.escapeText" which does exactly what you are describing on this line..

https://github.com/primefaces/primefaces/pull/2800/commits/84c1f1ae633ad830804aec999d7910c28ba9a5c0#diff-f9f675d809656851a148f8b7e9dbc24fR96
