### PR TITLE
Fix #8548: BlockUI Refactor

### LINKED ISSUE #5866: dataTable: blockUI stop works after ajax update
1) Environment
- PrimeFaces version: 7.0
- Application server + version: Spring boot tomcat embed 9
- Affected browsers: All

2) Expected behavior
blockUI should keep working

3) Actual behavior
blockUI stop works after ajax update

4) Steps to reproduce
After loading the page, use the pagination, see that it is working correctly.
But if you create a search, for example, that updates the records with update, when paging again, the blockui stops working.

5) Sample XHTML
```xml
<p:dataTable id="myDataTable"
					value="#{myLazyDataModel}" var="e" lazy="true"
					paginator="true">
<!-- Coluns here -->
</p:dataTable>
<p:blockUI block="#{p:component('myLazyDataModel')}" trigger="#{p:component('myLazyDataModel')}">
				<div class="p-grid ui-g p-align-center vertical-container p-justify-center sigor-blockui-loading">
        			<div class="p-col-fixed">
						<div class="blockui-loading-image ld ld-ring ld-spin" />
						<div class="blockui-loading-text">#{msg.get('blockuiMessage')}</div>
					</div>
				</div>
   			</p:blockUI>
```

6) Considerations
I know why the problem occurs, but I'm not managed to solve.
because when using the <p: ​​blockUI> component, it injects a jquery code, which needs to be re-executed after ajax events.
```javascript
$(document).on('pfAjaxComplete', function() {
     console.log('pfAjaxComplete');
     runOnEveryPartialPageLoad();
});
```
Do you have any suggestions on how do i solve this problem?

### LINKED ISSUE #8494: BlockUI: widgetVar is reset to null after partial updates
I am using Primefaces 11, and I am adding this components in home.xhtml page:

```html
<p:dataTable id="dataTable" var="n" value="#{homeBean.dataMedel}" lazy="true" paginator="true" rows="10"
             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {NextPageLink} {RowsPerPageDropdown}" 
             sortOrder="descending" rowsPerPageTemplate="10,15,20,30,50">
```
```html
<p:blockUI widgetVar="bui" block="dataTable" animate="false">
     <p:graphicImage value="ajax_loader.gif"/>
</p:blockUI>
```
```html
<h:selectOneMenu id="filterTopic" value="#{filterBean.topic}" label="topic" title="topic"
    <p:ajax event="change" update="dataTable" onstart="PF('bui').show();" oncomplete="PF('bui').hide()"
            listener="#{homeBean.onPreRender}"/>
    <f:selectItems value="#{topicBean.topicList}"/>
</h:selectOneMenu>
```

when I select one of the items in filterTopic menu, the ajax_loader.gif should fall on the dataTable until the data is fetch from homeBean. but it`s not working and i can see in the console the following error:

**Widget for var 'bui' not available!**  -->   core.js.xhtml?ln=primefaces&v=11.0.0:18

**home.xhtml Uncaught TypeError: Cannot read properties of null (reading 'hide')**  -->  home.xhtml

also when refresh page and run PrimeFaces.widgets in browser console, result is:

     bui: c {_super: undefined, cfg: {…}, id: 'form:j_id_bo', jqId: '#form\\:j_id_bo', jq: S.fn.init(1), …}

but when select one of the items in filterTopic menu, bui value set to null:

     bui: null

also this code worked with primefaces 10

### LINKED ISSUE #8548: BlockUI: refactor + root element should not be moved in DOM
Currently the BlockUI script is a bit weird as it moves the root element to the target. Sometimes its also cloned, which should not be required.

I think it needs a bit of refactoring, also the code itself reads weird as it covers multiple block targets but the code is hard do unterstand.

This example shows the weird behavior:
```
        <h1>BLOCK UI Null Widget</h1>
        <h:form id="frmTest">
            <h:panelGroup id="panel">
                Panel
            </h:panelGroup>
            <p:blockUI widgetVar="blockPanel" block="panel" blocked="true"/>
            <p:commandButton value="Unblock"
                             update="panel"
                             oncomplete="PF('blockPanel').hide()"/>
        </h:form>
```

BlockUI is actually on the same level as commandButton and panelGroup but our BlockUI script moves the conent into the panel.
How does this work with multiple block target? It will probably duplicate the root element, which means we have multiple DIVs with the same ID, which is also wrong

- [x] Format code for readability
- [x] When using multiple targets prevent duplicate ID's in the DOM
- [x] Do not put the DOM element inside the Target (fixed NULL widget issue)
- [x] Test with showcase and reproducers

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko this is part of my incremental refactoring just trying to untangle this component.  This PR documents the current process and fixes the issue of duplicate ID's when using multiple targets.

image

This now gives it unique `_block` and `_blockcontent` ids using the target id and not the BLockUI's id.

### CODE REVIEW

**Comment by melloware** [comment]
OK I got everything working and the block ui now attach to `document.body` and tested with existing use case and showcase examples!

File: primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js [hunk 1]
```diff
@@ -179,30 +179,68 @@ PrimeFaces.widget.BlockUI = PrimeFaces.widget.BaseWidget.extend({
...
+            });
+            currentContent.css({
+                'height': height + 'px',
+                'width': width + 'px',
+                'left': position.left + 'px',
+                'top': position.top + 'px'
+            });
+
+            // append the blocker to the document 
+            $(document.body).append(currentBlocker).append(currentContent);
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js:241]: Append to document body instead of the target.

File: primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js [hunk 2]
```diff
@@ -179,30 +179,68 @@ PrimeFaces.widget.BlockUI = PrimeFaces.widget.BaseWidget.extend({
...
+                'width': width + 'px',
+                'left': position.left + 'px',
+                'top': position.top + 'px'
+            });
+            currentContent.css({
+                'height': height + 'px',
+                'width': width + 'px',
+                'left': position.left + 'px',
+                'top': position.top + 'px'
+            });
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js]: The reason it was putting the block panel inside the target element was so it could properly calculated position so this just preemptively copies the size and position to the block UI elements.

File: primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js [hunk 3]
```diff
@@ -179,30 +179,68 @@ PrimeFaces.widget.BlockUI = PrimeFaces.widget.BaseWidget.extend({
...
+
+            // append the blocker to the document 
+            $(document.body).append(currentBlocker).append(currentContent);
         }
+
+        // assign all matching blockers to widget
+        this.blocker = $('[data-bui-overlay~="' + widgetId + '"]');
+        this.content = $('[data-bui-content~="' + widgetId + '"]');
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js:246]: This properly grabs all the block panels the old code was actually only holding the "last" one instead of all of them in the case of multiple target.

**Comment by tandraschko** [comment]
i think we can do it more easily
instead of move this.jq to the panel content, we can clone this.jq (there was a clone already!) and move this + change id

**Comment by tandraschko** [comment]
the problem isnt that we put something inside the panel, the problem we remove this.jq from its original DOM position completely
but not sure whats more failsafe and cleaner (also think about positioning + scrolling)

**Comment by melloware** [comment]
Yep the issue is by putting it inside the panel it's when the panel gets destroyed it takes the block ui DIV with it. So it needs to live outside the panel which is why it's in the doc body now. 

Also it's gets proper ids based on its target to prevent duplicate ids it was getting before.

**Comment by tandraschko** [comment]
i think we should really avoid to move this.jq around, this would require the `appendTo` logic/cleanup and so on
what about not moving or cloning the content of this.jq but just re-position via css?

**Comment by melloware** [comment]
So this.jq is the overlay  mask DiV. It's already being moved and postioned with CSS?  And it's cloned only if the target has more than 1 target it makes a copy. 

So not quite sure how to solve this unless we move that overlay mask outside of the target right?

**Comment by tandraschko** [comment]
if the current fix also works with scrolling and so on, i'm ok with it

**Comment by jepsar** [comment]
Since this was caused by regression, shouldn't we add ITs?

**Comment by melloware** [comment]
Let me test scrolling today and see if I can add some IT tests.

**Comment by melloware** [comment]
@jepsar great idea on the integration tests it helped me find a few more holes in this blockUI code and dom elements not properly being cleaned up on destroy and aggressive cloning when it was not necessary if there is no content to display.
