### PR TITLE
Fix #11421: Ignore ColumnRenderer helper in components using columns

### LINKED ISSUE #11421: SelectCheckboxMenu: Custom rendering broken when used as `DataTable` filter in a `ColumnGroup`
### Describe the bug

When a `SelectCheckboxMenu` with custom rendering is used as a `DataTable` filter, and the header of the table is specified within a `ColumnGroup`, then the rendering of the `SelectCheckboxMenu` is broken. The column with the selection labels is empty, and an additional column, which contains the value of the header facet, is rendered for each selection item.

SelectCheckboxMenu-broken

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/14233689/primefaces-test-master.zip)

### Expected behavior

There should be just one column with the selection labels.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8.0_202-b08

### Browser(s)

Chromium 121.0.6167.85, Firefox 115.7.0esr

### PR DESCRIPTION
**Pull request by melloware**
Fix #11421: Ignore ColumnRenderer helper in components using columns

This PR does it the "better" way with a utility to wrap and restored the helper.  Note we need to do this on all components that have custom "Column Rendering".

### CODE REVIEW

**Comment by melloware** [comment]
also i didn't know if "Stateless" was the right term since this is removing a value from the State map...

**Comment by tandraschko** [comment]
i like this more actually but it wraps IOException into FacesException, which can have drawbacks on exception handling propably
but not sure

**Comment by Rapster** [comment]
Not sure about the name, but the try/catch and the return null doesn't look nice... Use a `Runnable` instead, something like `FailableRunnable` for nicer exception handling

**Comment by melloware** [comment]
@Rapster can you give an example of how that would work?  I have only use Runnable's for threading not just for a lambda wrapper?

**Comment by Rapster** [comment]
You can use Runnable just like any other functional interfaces

**Comment by melloware** [comment]
OK @Rapster i think I got it if you want to re-review

File: primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java [hunk 1]
```diff
@@ -506,7 +508,10 @@ protected void encodeSuggestions(FacesContext context, AutoComplete ac, Object i
         Converter converter = ComponentUtils.getConverter(context, ac);
 
         if (customContent) {
-            encodeSuggestionsAsTable(context, ac, items, converter);
+            FailableRunnable<IOException> runnable = () -> {
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java]: instead of declaring it, I don't mind if it's inline

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 2]
```diff
@@ -698,7 +710,9 @@ public static <T> T executeInRequestScope(FacesContext context, String var, Obje
 
         Object oldValue = requestMap.remove(var);
         try {
-            requestMap.put(var, value);
+            if (value != null) {
+                requestMap.put(var, value);
+            }
 
             return callback.get();
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: Simpler this way no?

```java
Object oldValue = requestMap.put(var, value);
try {
    return callback.get();
}
finally {
    if (oldValue != null) {
        requestMap.put(var, oldValue);
    }
}
```

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 3]
```diff
@@ -710,6 +724,35 @@ public static <T> T executeInRequestScope(FacesContext context, String var, Obje
...
+
+        Object oldValue = stateMap.remove(var);
+        try {
+            runnable.run();
+        }
+        finally {
+            if (oldValue != null) {
+                stateMap.put(var, oldValue);
+            }
+        }
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: same here

File: primefaces/src/main/java/org/primefaces/util/FailableRunnable.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+ */
+package org.primefaces.util;
+
+/**
+ * A functional interface like {@link Runnable} that declares a kind of {@link Throwable}.
+ *
+ * @param <E> The kind of {@link Throwable}.
+ */
+@FunctionalInterface
+public interface FailableRunnable<E extends Throwable> {
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: We could acually shaded few of these, I'm thinking about IOBiConsumer

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 2 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: I think you are mixing up the two methods. The execute in Request Scope requires a return value while executeStateless does not its a void.  One is putting a temp variable on the request scope an removing it when done.  This one is removing a State variable and putting it back when done.

**Review by Rapster — CHANGES_REQUESTED** [review]

File: primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java (hunk 1 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java]: Inlined...

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 2 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: For example i need to remove `Constants.HELPER_RENDERER` from the state map, run some code, and then re-instate the `Constants.HELPER_RENDERER` value.

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: You sure? Don't think I'm mixing anything here, also why having this null check before `requestMap.put(var, value);`?

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: My coment is on executeInRequestScope not executeInStatelessScope 😄

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 3 above)
Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: Ok got it, but I think the name doesn't say much about what the method really does

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: Yeah I couldn't think of a better name so I am open to suggestions.  Its basically removing a state variable, running, and restoring a state variable.

File: primefaces/src/main/java/org/primefaces/util/FailableRunnable.java (hunk 4 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: I don't have thoughts other than with like our COmmons IO issue its sometimes easier not to shade?  But I could be convinced either way 😄

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 2 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: Resolved

File: primefaces/src/main/java/org/primefaces/util/FailableRunnable.java (hunk 4 above)
Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Yeah... The difference I see here is that, as they are functional interfaces, the chances for them to change is very low?

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Another option would be to do like in omnifaces: https://github.com/omnifaces/omnifaces/blob/4.x/src/main/java/org/omnifaces/util/Callback.java

So we don't end up with too many java files?

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 3 above)
Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: Not easy, I wish I could come up with something better than "pop and run" 😅

File: primefaces/src/main/java/org/primefaces/util/FailableRunnable.java (hunk 4 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Oohhh I like that let me update and see if you like it.

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: OK submitted that to a new class called `Callbacks`.

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Looks nice, at this point, you can:
- rename IOBiConsumer into FailableBiConsumer
- move SerializableXXX classes into Callbacks
- rename ConsumerThree into TriConsumer and move it also

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Done!

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: Yup, looks good! WDYT?

File: primefaces/src/main/java/org/primefaces/util/Callbacks.java [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+import java.util.Objects;
+import java.util.function.Consumer;
+import java.util.function.Function;
+import java.util.function.Predicate;
+import java.util.function.Supplier;
+
+/**
+ * Collection of callback interfaces. Useful in (mini) visitor and strategy patterns.
+ */
+public final class Callbacks {
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/Callbacks.java:37]: private ctor

File: primefaces/src/main/java/org/primefaces/util/FailableRunnable.java (hunk 4 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FailableRunnable.java]: I like it. I think you are right I need a private CTOR

**Comment by tandraschko** [comment]
why not just a callbacks package? IMO the more common way

**Comment by Rapster** [comment]
As they're just extension of java.util, it makes sense to keep them in org.primefaces.util. I don't like having a deep and wide package structure, it always end up having a mess: the flatter the better.

Callbacks at this point is just a container, but could become what `Failable` is (from commons-lang), we'll most probably introduce new utils in the future, and no need to create another utils

One may argue how cumbersome it is to do someting like `Callbacks.FailableConsumer` but you can use static import and that should solve the "problem"

**Comment by tandraschko** [comment]
all right, thats ok for me

static imports are even more mess in the most times, so lets better stay with it

**Comment by melloware** [comment]
so I am OK to merge this I am very happy with this PR with @Rapster help where we landed on this!

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 3 above)
Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: We can stick with this name for now

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:751]: I have a preference to call it "runInStatelessScope" to make it less verbose, same as the other one

**Comment by melloware** [comment]
@Rapster how about `runWithoutStateVariable` since that is really what its doing?

**Comment by Rapster** [comment]
i'm fine with that

**Comment by tandraschko** [comment]
not sure about the name
its not a "state" var actually - "state "in JSF is always viewstate
better would be something like request attribute

**Comment by melloware** [comment]
I changed it to `runWithoutFacesContextVar`

**Review by Rapster — APPROVED** [review]
