### PR TITLE
Fixed #2690 - not to encode menu button if no children

### LINKED ISSUE #2690: Splitbutton: display as button in case no children rendered
If there is not child items defined in SplitButton, don't display arrow (e.g should look like a button then). It makes think there is something wrong...

### PR DESCRIPTION
**Pull request by jxmai**
Fix #2690 

Test code:

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h1>#{testView.testString}</h1>

	<p:splitButton value="Save" icon="ui-icon-disk" iconPos="right">
		<p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink" />
	</p:splitButton>

</h:body>
</html>
```

snapshot1

---

and 

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h1>#{testView.testString}</h1>

	<p:splitButton value="Save" icon="ui-icon-disk" iconPos="right">
	</p:splitButton>

</h:body>
</html>
```

snapshot1

### CODE REVIEW

File: src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java [hunk 1]
```diff
@@ -157,16 +159,19 @@ protected void encodeMenuIcon(FacesContext context, SplitButton button, String i
             writer.writeAttribute("disabled", "disabled", "disabled");
         }
 
-        //icon    
-        writer.startElement("span", null);
-        writer.writeAttribute("class", "ui-button-icon-left ui-icon ui-icon-triangle-1-s", null);
-        writer.endElement("span");
+        
+        if (button.getChildCount() > 0) {
```
Comment (Rapster) [inline src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java:163]: @jxmai Was this test really necessary? Since `encodeMenuIcon` is called by `encodeMarkup``where the test is made

**Comment by Rapster** [comment]
FYI, top/bottom right corner are not rounded

File: src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java (hunk 1 above)
Comment (jxmai) [reply src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java:163]: Alright, I see. This if statement seems redundant because of https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java#L90. but since you have raised another PR https://github.com/primefaces/primefaces/pull/3503 with better enhancement to deal with the same ticket, I will leave the task up to you :smile:

**Comment by jxmai** [comment]
> FYI, top/bottom right corner are not rounded

will resolve by https://github.com/primefaces/primefaces/pull/3503/files#diff-1eb0becf22758944ef1b0f0c7b627b3aR23 ?
