### PR TITLE
Fix #14387: 15.0.11 Datatable scrollable with table-layout:auto

### LINKED ISSUE #14387: DataTable: scrollable=true incompatible with table-layout:auto
### Describe the bug

`<p:dataTable scrollable="true">` is incompatible with `body .ui-datatable table { table-layout: auto; }` (client's requirement to retain default behavior of RichFaces data table). The widths of scrollable header are off every time the table is loaded, sorted,  paginated or resized.

I've monkeypatched it as follows, you may find it useful. Probably adjust it to only apply when `table.css("table-layout") === "auto"`.

```js
/**
 * - Monkeypatch p:dataTable scrollable="true" to be compatible with table-layout:auto
 * - Monkeypatch p:dataTable scrollable="true" to scroll back to top when paginated
 * - Monkeypatch p:dataTable scrollable="true" to reset columns width when paginated or resized
 */
PrimeFaces.widget.DataTable = PrimeFaces.widget.DataTable.extend({
    firstRow: function () {
        return this.tbody.find("tr:not(.ui-datatable-empty-message)").first(); // Needed to calculate the proper column widths.
    },

    resetColumnsWidth: function() {
        this.bodyTable.find(".ui-datatable-scrollable-theadclone").remove();
        this.cloneTableHeader(this.thead, this.bodyTable);
    },

    cloneTableHeader: function(thead, table) {
        const theadClone = thead.clone();
        const firstRow = this.firstRow();

        if (firstRow.length) {
            theadClone.find("th").each(function() {
                $(this).css({width: "", minWidth: ""}); // clear out width so table-layout:auto is properly recalculated
            });
            theadClone.insertBefore(this.tbody);
        }

        theadClone.find("th").each(function(i) {
            const th = $(this);

            if (firstRow.length) {
                const td = firstRow.find("td").eq(i);
                const width = td.width();
                th.css({width: width + "px"}).data("width", width); // remember width in data so minWidth can be set after prependTo
            }

            th.attr("id", th.attr("id") + "_clone");
            th.removeAttr("aria-label");
            th.children().not(".ui-column-title").remove();
            th.children(".ui-column-title").children().remove();
        });

        theadClone.removeAttr("id").addClass("ui-datatable-scrollable-theadclone").height(0).prependTo(table);

        if (firstRow.length) {
            thead.find("th").each(function(i) {
                const th = $(this);
                const thClone = theadClone.find("th").eq(i);
                const width = thClone.data("width"); // because setting minWidth doesn't work before prependTo
                th.css({width: width + "px", minWidth: width + "px"});
                thClone.css({width: width + "px", minWidth: width + "px"});
            });

            if (!thead.data("resizeTimer")) {
                thead.data("resizeTimer", true);
                const thiz = this;
                var resizeTimer;
    
                $(window).on('resize', function() {
                    clearTimeout(resizeTimer);
                    resizeTimer = setTimeout(thiz.resetColumnsWidth.bind(thiz), 100);
                });
            }
        }

        return theadClone;
    },

    updateColumnsView: function() { // invoked after sorting/paging/filtering
        this._super();

        if (this.scrollBody) {
            this.scrollBody.scrollTop(0).scrollLeft(0); // reset scroll position to left-top.

            const firstRow = this.firstRow();

            if (firstRow.length) {
                this.resetColumnsWidth();
            }
        }
    }
});
```

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

15.0.8

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0.11

### Java version

21

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #14387: 15.0.11 Datatable scrollable with table-layout:auto

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -5785,6 +5852,18 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
...
+        // reset the position and column widths if scrollable
+        if(this.scrollBody) {
+            // reset scroll position to left-top.
+            this.scrollBody.scrollTop(0).scrollLeft(0); 
+
+            // reset the column widths if the first row exists
+            const firstRow = this.firstRow();
+            if (firstRow.length) {
+                this.resetColumnsWidth();
+            }
```
Comment (BalusC) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:5865]: This section should check for isAutoLayout. I meant with previous comment that only the line this.scrollBody.scrollTop(0).scrollLeft(0) doesn't need to check for isAutoLayout.

Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:5865]: My bad I misunderstood!
