### PR TITLE
Fix #12044: Rating accessibility and bug fixes

### LINKED ISSUE #12044: Rating: Resubmit after invalid sets value to 3
### Describe the bug

Value is getting set to 3 after the component has been marked invalid discovered by @Rapster 

### Reproducer

Submit a required rating.  Then Submit it again the invalid value gets set to 3.

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12044: Rating accessibility and bug fixes

- [x] - Fixed bug with submitting required field twice
- [x] - Fixed keyboard handling with Arrow Keys
- [x] - Fixed ARIA labels for screen reader to read "3 stars" from PrimeLocale
- [x] Integration tests for REQUIRED added

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js [hunk 1]
```diff
@@ -1225,16 +1225,28 @@
...
+            var label = (ariaLocaleSettings && ariaLocaleSettings[key]) ? ariaLocaleSettings[key] : PrimeFaces.locales['en_US']['aria'][key];
+            label = label || (defaultValue || "???"+key+"???");
+            if (options) {
+                for (const key in options) {
+                    if (options.hasOwnProperty(key)) {
+                        label = label.replace(`{${key}}`, options[key]);
+                    }
+                }
+            }
+            return label.trim();
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js:1246]: I brought this over from PrimeReact to replace `"{star} stars"` type labels

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js [hunk 2]
```diff
@@ -1225,16 +1225,25 @@
...
-        getAriaLabel: function(key, defaultValue) {
+        getAriaLabel: function(key, defaultValue, options) {
             var ariaLocaleSettings = this.getLocaleSettings()['aria'];
-            var label = (ariaLocaleSettings&&ariaLocaleSettings[key]) ? ariaLocaleSettings[key] : PrimeFaces.locales['en_US']['aria'][key];
-            return label || (defaultValue || "???"+key+"???");
+            var label = ariaLocaleSettings[key] || PrimeFaces.locales['en_US']['aria'][key] || defaultValue || "???" + key + "???";
+            if (options) {
+                Object.keys(options).forEach(function(valKey) {
+                    label = label.replace(`{${valKey}}`, options[valKey]);
+                });
```
Comment (Rapster) [inline primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: for...of... instead of forEach (it seems it has better performance https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/)

Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: I switched to `for` loop.

File: primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java [hunk 3]
```diff
@@ -142,7 +141,7 @@ protected void encodeInput(FacesContext context, Rating rating, String id, Strin
         writer.writeAttribute("min", "0", null);
         writer.writeAttribute("max", rating.getStars(), null);
         writer.writeAttribute("autocomplete", "off", null);
-        writer.writeAttribute("value", Objects.toString(value, "0"), null);
+        writer.writeAttribute("value", LangUtils.isBlank(value) ? "0" : value, null);
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java]: We could introduce a new method here: `LangUtils#toString(value, blankDefault)`

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java]: I added `defaultIfBlank` to match commong Lang StringUtils.
