### PR TITLE
Fix #10150: Log warning on missing locale-XX.js file

### LINKED ISSUE #10150: HeadRenderer: Client side localization fails for missing localization
### Describe the bug

Exception is thrown by [encodeJS](https://github.com/primefaces/primefaces/blob/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L175) when a localization resource is missing.

### Reproducer

Set a locale that is not provided. See [META-INF/resources/primefaces/locales](https://github.com/primefaces/primefaces/tree/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/resources/META-INF/resources/primefaces/locales)

### Expected behavior

Maybe [encodeBegin](https://github.com/primefaces/primefaces/blob/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L130) should retry with a default locale. Or skip throwing the exception if a default locale is already provided in JavaScript.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #10150: Log warning on missing locale-XX.js file

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java [hunk 1]
```diff
@@ -126,8 +129,16 @@ public void encodeBegin(FacesContext context, UIComponent component) throws IOEx
...
-            Locale locale = LocaleUtils.getCurrentLocale(context);
-            encodeJS(context, LIBRARY, "locales/locale-" + locale.getLanguage() + ".js");
+            try {
+                Locale locale = LocaleUtils.getCurrentLocale(context);
+                encodeJS(context, LIBRARY, "locales/locale-" + locale.getLanguage() + ".js");
+            }
+            catch (FacesException e) {
+                if (LOGGER.isLoggable(Level.WARNING)) {
+                    LOGGER.log(Level.WARNING,
+                            "Failed to load client side locale.js. {0}", e.getMessage());
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java:139]: I would log the filename inclusive language

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java:139]: Good idea

Comment (mihaiDumea) [reply primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java:139]: Maybe is a good idea to replace the condition `if (LOGGER.isLoggable(Level.WARNING)) {` with `if( FacesContext.getCurrentInstance( ).isProjectStage( ProjectStage.Development ) )` as nothing can be done to get rid of this message.

Regarding the message content, the filename and language is already included in exception message: `Failed to load client side locale.js. Error loading JavaScript, cannot find "locales/locale-zz.js" resource of "primefaces" library`
