### PR TITLE
Fix #10576: Paginator position must be lowercase in script

### LINKED ISSUE #10576: DataTable: Incorrect casing of paginator position causes paginator to fail pagination
### Describe the bug

when applying a paginator position for a data table, the position must be one of the following: "top", "bottom", or "both". Although when using uppercase for the first letter, it seems to render correctly, but the page links and rows dropdown silently fail without throwing any errors.

### Reproducer

1. Create a data table component with a sample dataset with paginatorPosition set to `Bottom`:
```xhtml
<h:form id="frmBookDataTable">
                <p:dataTable var="book" value="#{booksDataTable.books}"
                             paginator="true" rows="10"
                             currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} records"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="10,25,50,{ShowAll|'All'}"
                             paginatorPosition="Bottom" allowUnsorting="true" selectionMode="single"
                 >
                    <p:column sortBy="#{book.isbn}" filterBy="#{book.isbn}" filterMatchMode="contains"
                              headerText="ISBN">
                        <h:outputText value="#{book.isbn}"/>
                    </p:column>
                    <p:column sortBy="#{book.author.name}" filterBy="#{book.author.name}" filterMatchMode="contains"
                              headerText="Author" sortPriority="1">
                        <h:outputText value="#{book.author.name}"/>
                    </p:column>
                    <!-- ... -->
                 </p:dataTable>
</h:form>
```
2. Load the data table and click the paginator buttons to see nothing is loading correctly or changing pages
DataTableFailing

3. Change the data table paginatorPosition to `bottom`:
```xhtml
<h:form id="frmBookDataTable">
                <p:dataTable var="book" value="#{booksDataTable.books}"
                             paginator="true" rows="10"
                             currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} records"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="10,25,50,{ShowAll|'All'}"
                             paginatorPosition="bottom" allowUnsorting="true" selectionMode="single"
                 >
                    <p:column sortBy="#{book.isbn}" filterBy="#{book.isbn}" filterMatchMode="contains"
                              headerText="ISBN">
                        <h:outputText value="#{book.isbn}"/>
                    </p:column>
                    <p:column sortBy="#{book.author.name}" filterBy="#{book.author.name}" filterMatchMode="contains"
                              headerText="Author" sortPriority="1">
                        <h:outputText value="#{book.author.name}"/>
                    </p:column>
                    <!-- ... -->
                 </p:dataTable>
</h:form>
```

4. Load the data table and click the paginator buttons to see everything working as expected
DataTableWorking

### Expected behavior

I expect that paginatorPosition should either have validation for specific casing to throw an exception, or lowercase the input automatically to handle different input casing

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Arya

### JSF implementation

Mojarra

### JSF version

3.0

### Java version

17.0.8 2023-07-18 LTS

### Browser(s)

_No response_

edit: updated step 4 in reproduction steps to use correct gif of it working

### PR DESCRIPTION
**Pull request by melloware**
Fix #10576: Paginator position must be lowercase in script

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java [hunk 1]
```diff
@@ -155,7 +155,7 @@ protected void encodePaginatorConfig(FacesContext context, Pageable pageable, Wi
             paginatorContainers = "'" + clientId + "_paginator_top','" + clientId + "_paginator_bottom'";
         }
         else {
-            paginatorContainers = "'" + clientId + "_paginator_" + paginatorPosition + "'";
+            paginatorContainers = "'" + clientId + "_paginator_" + paginatorPosition.toLowerCase() + "'";
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java:158]: I think we have more or less the same issue with other attributes which basically should have been enums. IMO using an enum would be better (but it would be a huge task to change them all). And if a users uses a value that does not match any of the enum values, we should throw an exception. But again, that's my opinion.

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java:158]: I totally agree I noticed we do a ton of `"bottom".equalsIgnoreCase(position)"` type stuff all over but in this one spot it was missed and causes a bug. If it was an enum that would be impossible and we could throw an error.

Maybe it would be worth doing in a bigger cleanup task @tandraschko  ?

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java:158]: Should we open a new issue for this?

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java:158]: Yes please
