### PR TITLE
Fix #99: ConfirmDialog allow ajax=false submission

### LINKED ISSUE #99: Non-Ajax submit support for Global ConfirmDialog
Currently using `ajax=false` with Confirm Dialog does not work.
```xml
<p:commandButton id="delete" 
                 action="#{trafficExpenseItemsMBean.deleteExpenseItemsGroup}" 
                 icon="ui-icon ui-icon-trash" 
                 value="Delete" 
                 ajax="false"
                 title="DeleteButton">
    <p:confirm header="Delete Record" 
               message="Are you sure about deleting this record?" 
               icon="ui-icon-alert"/>
</p:commandButton>
```

### PR DESCRIPTION
**Pull request by melloware**
Fix #99: ConfirmDialog allow ajax=false submission

- [x] Integration Tests Added
- [x] Showcase example added
- [x] Basically if the function passed to the confirm dialog is EMPTY we know this is AJAX=false so remove the existing `onclick` event which brough up the dialog and then `click` the button.

### CODE REVIEW

**Comment by melloware** [comment]
Another weird one.  This test is passing locally for me.

File: primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js [hunk 1]
```diff
@@ -939,8 +939,18 @@ PrimeFaces.widget.ConfirmDialog = PrimeFaces.widget.Dialog.extend({
                 if(el.hasClass('ui-confirmdialog-yes') && PrimeFaces.confirmSource) {
                     var id = PrimeFaces.confirmSource.get(0);
                     var js = PrimeFaces.confirmSource.data('pfconfirmcommand');
-
-                    PrimeFaces.csp.executeEvent(id, js, e);
+                    
+                    // Define the pattern to match an empty function like: function(event){}
+                    const isEmptyFunctionPattern = /function\s*\(\s*event\s*\)\s*{\s*}/;
+                    // Test if the function matches the pattern
+                    if (isEmptyFunctionPattern.test(js)) {
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js]: i wonder if it wouldnt be better to check js.contains(pf.ab || jsf.ajax)?

Comment (tandraschko) [reply primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js]: see PF selenium:         return script.contains("PrimeFaces.ab(") || script.contains("pf.ab(")
                || script.contains("mojarra.ab(")
                || script.contains("myfaces.ab(")
                || script.contains("jsf.ajax.request") || script.contains("faces.ajax.request");

**Comment by jepsar** [comment]
I think I'll wait for this to be merged to update my PR. I'll probably won't have time to work on it until this weekend anyway 😁

File: primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js (hunk 1 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js]: Not a bad idea let me try that!

**Comment by melloware** [comment]
@tandraschko here is what the `js` variable contains in AJAX vs NON-AJAX mode.

AJAX: 
```js
PrimeFaces.bcn(this,event,[function(event){PrimeFaces.ab({s:"j_id_7j:j_id_7m",f:"j_id_7j",u:"j_id_7j:message"});return false;}]);
```

NON-AJAX:
```js
PrimeFaces.bcn(this,event,[function(event){}]);
```

That is why above I decided to use a regex to look for an empty function `function(event){}`.  Thoughts?

**Comment by tandraschko** [comment]
no idea TBH, i just thought that checking for AJAX is more safe then a empty-function regex, which could mean anything?

**Comment by melloware** [comment]
Nevermind it works like a charm.  Integration tests running now
