### PR TITLE
Fix #3551: Datatable remember multiple selection between AJAX updates

### LINKED ISSUE #3551: DataTable: Multiselection with shift-click doesn't work after update
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version? **No - 6.2**
- Application server + version: **WildFly 12.0**
- Affected browsers: **Firefox**

## 2) Expected behavior

After clicking entry a) of the datatable and then shift-clicking a second entry b), all entries from a) to b) should be selected, even if the DataTable has bean updated in the meantime.

## 3) Actual behavior

After first click, entry a) is selected.
After updating the DataTable, still a) is selected, this is OK.
But after shift-clicking b), all entries from the first row to b) are selected.

## 4) Steps to reproduce

With the example, select one entry, wait a second, then shift-select another entry

## 5) Sample XHTML

Just use the "Multiple with Meta and Shift keys" example from:
https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

and add the following line to make it update the DataTable, this issue is not just related to the <p:poll> component, it could also be updated with a button or anything else: 
`<p:poll interval="1" update="multipleDT"/>`

### PR DESCRIPTION
**Pull request by melloware**
Fix #3551: Datatable remember multiple selection between AJAX updates

This PR stores the `rowMeta` and not just the `index` of the rows selected between AJAX updates.  This allows a lookup by the `rowKey` to find the rows selected again or if they have changed (aka removed) indexes in between AJAX updates it can still find the correct rows by row key.

- Store `rowMeta` with `rowKey` instead of `rowIndex`
- After AJAX update if these have values lookup the new row by its `rowKey`
- Select rows that were selected before the AJAX update

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -797,17 +797,33 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
...
             $this.updateSelectionAria($(this))
         });
 
         this.bindSelectionEvents();
+        
+        //shift key based range selection
+        this.originRowMeta = this.originRowMeta ? this.getRowMeta(this.tbody.find("[data-rk='" + this.originRowMeta.key + "']")) : null;
+        if (this.cursorRowMeta) {
+            // #3551 lookup row after update by row key
+            var crow = this.tbody.find("[data-rk='" + this.cursorRowMeta.key + "']");
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js]: crow? is this a common name for vars? :D

**Comment by tandraschko** [comment]
could we add a test here?

**Comment by melloware** [comment]
Yes let me add a test!

**Comment by melloware** [comment]
Integration test added.  I confirmed the test fails without this change and passes with this change.
