### PR TITLE
Fix #7079/#7082: CascadeSelect NPE or incorrect label displayed

### LINKED ISSUE #7079: CascadeSelect: NPE when placeholder-attribute is not set
Noted while writing integration-tests for CascadeSelect.

### LINKED ISSUE #7082: CascadeSelect: does not show selected value (eg after submit/update or for pre-selected values)
Integration-test PR is incoming

### PR DESCRIPTION
**Pull request by melloware**
Fixes both issues.  If for example you had a pre-selected value like "Montreal"
```java
private String selection = "Montreal";
```
It was not showing up as the selected label on the UI.

### CODE REVIEW

**Review by christophs78 — APPROVED** [review]

File: src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java [hunk 1]
```diff
@@ -83,18 +84,18 @@ protected void encodeMarkup(FacesContext context, CascadeSelect cascadeSelect) t
 
         renderARIACombobox(context, cascadeSelect);
 
-        encodeInput(context, cascadeSelect);
-        encodeLabel(context, cascadeSelect);
+        String valueToRender = ComponentUtils.getValueToRender(context, cascadeSelect);
```
Comment (christophs78) [inline src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java:87]: It´s only partial solved. Only solved for SelectItems which only have a label.
It does not work when we have value and label. In this case we see after update the value instead of the label.

Comment (melloware) [reply src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java:87]: Fixing with another PR
