### PR TITLE
Fixes #8977 - DataExporter: Numbers greater than 1000 are formatted as currency in Excel exporter with numberConverter

### LINKED ISSUE #8977: DataExporter: Numbers greater than 1000 are formatted as currency in excel exporter with numberConverter
### Describe the bug

When using `<f:numberConverter>` with type "number" and exporting with any excel format, the numbers are exported as currency when they are numbers.

image

### Reproducer

```xhtml
<p:dataTable id="table" var="r" value="#{testView.records}">
    <p:column headerText="Text Value">
        <h:outputText value="#{r.textValue}" />
    </p:column>
    <p:column headerText="Int Value">
        <h:outputText value="#{r.intValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Long Value">
        <h:outputText value="#{r.longValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Double Value">
        <h:outputText value="#{r.doubleValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Currency Value">
        <h:outputText value="#{r.currencyValue}">
            <f:convertNumber type="currency" />
        </h:outputText>
    </p:column>
    <f:facet name="footer">
        <h:commandLink immediate="true">
            <h:outputText value="xls" />
            <p:dataExporter type="xls" target="@parent:@parent" fileName="test" />
        </h:commandLink>,
        <h:commandLink immediate="true">
            <h:outputText value="xlsx" />
            <p:dataExporter type="xlsx" target="@parent:@parent" fileName="test" />
        </h:commandLink>,
        <h:commandLink immediate="true">
            <h:outputText value="xlsxstream" />
            <p:dataExporter type="xlsxstream" target="@parent:@parent" fileName="test" />
        </h:commandLink>
    </f:facet>
</p:dataTable>
```

### Expected behavior

It should be formatted as numbers in excel at least or could be formatted with provided DecimalFormat of ExcelOptions if was set.

image

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0, 12.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jasonex7**
Fixes #8977

This modifies #8964 by changing the name of the property decimalFormat to more specific name "currencyFormat"

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java [hunk 1]
```diff
@@ -110,19 +114,32 @@ private void updateCell(Cell cell, String value) {
         }
     }
 
-    private boolean applyNumberStyleIfApropiate(Cell cell, String value) {
+    private boolean setNumberValueIfApropiate(Cell cell, String value) {
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java]: Appropriate has two P's.

**Review by melloware — CHANGES_REQUESTED** [review]

File: primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java (hunk 1 above)
Comment (jasonex7) [reply primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java]: Oh, I fix the typo

**Review by melloware — APPROVED** [review]
