### PR TITLE
DataTable/TreeTable: cellEditor saves changes too late #7776

### LINKED ISSUE #7546: DataTable: onCellEdit event fires too late
**Describe the defect**
Assume we have datatable whit cell we trying edit and some button below that submit that has ajax action
Then
first scenario: we edit datatable cell (enter new value), do mouse click on some form place (to imitate focus lost) - here onCellEdit 
 event will fire, then click the button.
So - **onCellEdit will fire first, then button action will fire second**
second scenario: we edit datatable cell (enter new value), then do mouse click directly on the button.
**The button action will fire first, onCellEdit will fire second**
But de-facto row cell also lost focus when we do click the button

**To Reproduce**
Go to edit datatable cell, change the value then click the mouse on the button that has ajax action event
Firs button action will be fired, then onCellEdit event

**Environment:**
 - PF Version: 10.0
 - Chrome 91

**Expected behavior**
OnCellEdit should fire BEFORE button action.

P.S.
I found the same problem description on StackOverflow, added long time ago:
https://stackoverflow.com/questions/26099330/pcelleditor-does-not-save-textarea-onblur-when-clicking-a-link
The author said he created a bug request in primefaces repo, but I did not found it in issues.

### LINKED ISSUE #7776: DataTable/TreeTable: cellEditor saves changes too late
**Describe the defect**
DataTable cellEditor saves changes when you click away from it. But if you click something like a commandButton, then the saving request gets queued after the button's, which is usually not what you want.

**Reproducer**
[primefaces-datatable-celledit-request-late.zip](https://github.com/primefaces/primefaces/files/7085911/primefaces-datatable-celledit-request-late.zip)

**Environment:**
 - PF Version: _6.2.30_, _10.0.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to http://localhost:8080/primefaces-test/
2. Click on the "Initial" value in the table.
3. Change it to "123". Don't press Enter.
4. Click on the button.
5. Note the stdout:
```
Acting on value: Initial
Changing value to 123
```
The value was changed after the button's action.

**Expected behavior**
Saving request happens before whatever was triggered by the click away. Maybe by also handling focusin or mousedown, or mouseup?

**Example XHTML**
```
<h:form id="form">
	<p:dataTable id="datatable" value="#{testView.list}" var="row" style="width: 100px" editable="true" editMode="cell">
		<p:column headerText="Column">
			<p:cellEditor>
				<f:facet name="input">
					<p:inputText value="#{row.value}" />
				</f:facet>
				<f:facet name="output">
					#{row.value}
				</f:facet>
			</p:cellEditor>
		</p:column>
	</p:dataTable>
	<p:commandButton id="btn" value="Act" action="#{testView.act}" process="@this" />
</h:form>

```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {

	private List<Bean> list = List.of(new Bean());

	public List<Bean> getList() {
		return list;
	}

	public void act() {
		System.out.println("Acting on value: " + list.get(0).getValue());
	}

	public static class Bean {

		private String value = "Initial";

		public String getValue() {
			return value;
		}

		public void setValue(String value) {
			System.out.println("Changing value to " + value);
			this.value = value;
		}

	}
    
}
```

### PR DESCRIPTION
**Pull request by VsevolodGolovanov**
Save/cancel on mouseup to que the event request before whatever was clicked reacts.

Got rid of incellClick and contextMenuClick, since the order of events changed. `if (currentCell.is(target) || currentCell.has(target).length)` takes care of their logic.
This does mean right clicking another cell would now end editing, but that seems acceptable.

### CODE REVIEW

**Comment by melloware** [comment]
Yes that seems acceptable to me.  Can you check treetable.js to see if it needs the same fixes?

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -3200,53 +3197,50 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
...
                             }
                         });
 
-            $(document).off('click.datatable-cell-blur' + this.id)
-                        .on('click.datatable-cell-blur' + this.id, function(e) {
-                            var target = $(e.target);
-                            if(!$this.incellClick && (target.is('.ui-input-overlay') || target.closest('.ui-input-overlay').length || target.closest('.ui-datepicker-buttonpane').length)) {
-                                $this.incellClick = true;
-                            }
+            // save/cancel on mouseup to que the event request before whatever was clicked reacts
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js]: `que` should be `queue`

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by VsevolodGolovanov** [comment]
@melloware, did the same for treeTable, tested a bit.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I updated the ticket and the PR title to reflect its for both tables.
