### PR TITLE
Fix #12694: AjaxStatus handle Faces completion

### LINKED ISSUE #12694: SelectOneMenu: ajaxStatus does not go back to status "complete"
### Describe the bug

Hi, 
Within a form containing a selectOneMenu with a listener on ajax event "change", when an item is selected in the select menu,  component p:ajaxStatus switches to state "start" but never finishes to the state "complete".
In my case, the spinner displayed by p:ajaxStatus does not disappear, even though it should after an item is selected from selectOneMenu 

### Reproducer

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core"
      xmlns:p="http://primefaces.org/ui">
<h:head/>

<h:body styleClass="main-body">
        <p:ajaxStatus styleClass="block mb-4">
            <f:facet name="default">
                <h:outputText value="Status: StandBy"/>
            </f:facet>

            <f:facet name="start">
                <i class="pi pi-spin pi-spinner loading-icon" aria-hidden="true"></i>
            </f:facet>

            <f:facet name="complete">
                <h:outputText value="Status: Completed"/>
            </f:facet>
        </p:ajaxStatus>

        <h:form id="simpleForm">

            <p:selectOneMenu value="#{myForm.valueHolder}">
                <f:selectItem itemLabel="label1" itemValue="value1"/>
                <f:selectItem itemLabel="label2" itemValue="value2"/>
                <f:ajax event="itemSelect"
                        listener="#{myForm.onChange()}"
                        render=":simpleForm"/>
            </p:selectOneMenu>
        </h:form>
</h:body>
</html>

```

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12694: AjaxStatus handle Faces completion

Faces has 1 arg while PF has 3 args.

The code to shortcircuit on redirect was assuming always 3 args.

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js [hunk 1]
```diff
@@ -189,10 +189,11 @@ PrimeFaces.widget.AjaxStatus = PrimeFaces.widget.BaseWidget.extend({
                 break;
 
             case 'complete':
+                var isFaces = args.length === 1;
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js]: Please add a comment here 

Maybe there is a more safer check possible?

Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js]: Let me investigate since they both have at least 1 arg I can look for something in arg[0] to detect JSF from PF

**Comment by tandraschko** [comment]
maybe its easier to check if its a PF request and then do `!isPF` as mojarra and myfaces might be different

**Comment by melloware** [comment]
OK updated how does that look?

**Comment by tandraschko** [comment]
hmm, for it still feels hacky
maybe we can introduce 2 different events? `.trigger('complete')` and `.trigger('facesComplete')` 

then its quite clear

**Comment by melloware** [comment]
OK that would be more clear.

**Comment by melloware** [comment]
OK updated to have `facesComplete` event

**Comment by tandraschko** [comment]
looks good for me!

**Comment by melloware** [comment]
@tandraschko i think my original solution while hacky solved all issues  Now the `complete` is closing the facet but not firing the `oncomplete` JS code.
