### PR TITLE
Fix #9429: rowSelectMode="none" remove cursor pointer

### LINKED ISSUE #9429: DataTable: selectionMode=multiple with rowSelectMode=none still shows cursor pointer
### Describe the bug

DataTable Checkbox selection with `rowSelectMode="none"` still sets the `cursor: pointer` style on hover of the entire row, despite only being able to select via the Checkbox.

### Reproducer

This issue can be reproduced running the showcase locally. Modify the Checkbox example in the `ui/data/datatable/selection.xhtml` showcase page and set `rowSelectMode="none"`. Run the showcase and hover the rows in that example.

### Expected behavior

If a row cannot be selected by clicking on the row itself, the cursor should remain as the arrow rather than changing to a pointer.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

All

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

All

### PR DESCRIPTION
**Pull request by melloware**
Fix #9429: rowSelectMode="none" remove cursor pointer

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -809,6 +809,9 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
             if(this.cfg.rowSelectMode !== 'none') {
                 this.bindRowEvents();
             }
+            else {
+                this.jq.find('tr.ui-datatable-selectable').css('cursor', 'default');
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:813]: Why are there rows classed with `ui-datatable-selectable` when row select mode is `none`?

Comment (FlipWarthog) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:813]: Take a look at the initial PR #9430. It's a difference between selecting via row click vs. actually clicking the checkbox, but removing the style affects the checkboxes too.
