### PR TITLE
Fix #9773: Add ui-datepicker-week-end class to weekends

### LINKED ISSUE #9773: Datepicker: CSS classes missing
### Describe the bug

[Server API](https://primefaces.github.io/primefaces/12_0_0/#/components/datepicker?id=skinning) lists css classes, which are not found on a rendered datepicker.

For example `.ui-datepicker-week-end` is listed at the API, but not found an the actual component.

The problem is also present in the [showcase datepicker](https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml)

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

Master Snapshot

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #9773: Add `ui-datepicker-week-end` class to weekends

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 1]
```diff
@@ -278,6 +278,11 @@
             return firstDayOfWeek > 0 ? 7 - firstDayOfWeek : 0;
         },
 
+        getSaturdayIndex: function () {
+            var firstDayOfWeek = this.options.locale.firstDay !== undefined ? this.options.locale.firstDay : this.options.locale.firstDayOfWeek;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]: I know it's a copied function, but isn't this the same?
```suggestion
            var firstDayOfWeek = this.options.locale.firstDay || this.options.locale.firstDayOfWeek;
```

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 2]
```diff
@@ -278,6 +278,11 @@
...
+            return firstDayOfWeek > 0 ? 7 - firstDayOfWeek - 1 : 6;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]: Isn't this just
```suggestion
            return 7 - firstDayOfWeek - 1;
```
?

**Comment by melloware** [comment]
Great idea i actually refactored and found a few more places that was being done.  I also updated the MD with some corrected and missing styles.

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 3]
```diff
@@ -273,11 +273,20 @@
             return dayIndex >= 7 ? dayIndex - 7 : dayIndex;
         },
 
+        getFirstDayOfWeek: function () {
+            return this.options.locale.firstDay !== undefined ? this.options.locale.firstDay : this.options.locale.firstDayOfWeek;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:277]: This won't work?
```suggestion
            return this.options.locale.firstDay || this.options.locale.firstDayOfWeek;
```

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 4]
```diff
@@ -273,11 +273,20 @@
...
+        },
+
         getSundayIndex: function () {
-            var firstDayOfWeek = this.options.locale.firstDay !== undefined ? this.options.locale.firstDay : this.options.locale.firstDayOfWeek;
+            var firstDayOfWeek = this.getFirstDayOfWeek();
             return firstDayOfWeek > 0 ? 7 - firstDayOfWeek : 0;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:282]:
```suggestion
            return 7 - this.getFirstDayOfWeek() % 7;
```

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 5]
```diff
@@ -273,11 +273,20 @@
...
         },
 
+        getSaturdayIndex: function () {
+            var firstDayOfWeek = this.getFirstDayOfWeek();
+            return 7 - firstDayOfWeek - 1;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]:
```suggestion
            return 7 - this.getFirstDayOfWeek() - 1;
```

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 6]
```diff
@@ -1474,7 +1483,7 @@
         },
 
         calculateWeekNumber: function(d) {
-            var dow = this.options.locale.firstDay !== undefined ? this.options.locale.firstDay : this.options.locale.firstDayOfWeek,
+            var dow = this.getFirstDayOfWeek(),
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]: I think this variable name is misleading. Isn't something like `firstDow` better?

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js (hunk 3 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:277]: no because if first day is `0` that is JS falsy so it will then go to first dayofWeek right it needs to check for undefined not just for falsiness?  And that is how it already was in the code I just moved it to a function.

Comment (jepsar) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:277]: Ah! Alright. Need to keep that in mind.

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js (hunk 6 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]: Fixed
