### PR TITLE
Fixes #9025 - DataTable: RowHover attribute doesn't work

### LINKED ISSUE #9025: DataTable: RowHover attribute doesn't work
### Describe the bug

RowHover attribute doesn't work on PrimeFaces 12-SNAPSHOT but it works on PrimeFaces 11.

With PrimeFaces 12
row_hover_12

With PrimeFaces 11
row_hover_11

### Reproducer

Just use any `<p:dataTable>` with `rowHover="true"`.

```xhtml
<p:dataTable id="tbl" var="car" value="#{carView.cars}" rowHover="true" paginator="true" rows="10">
      <p:column headerText="Id">
          <h:outputText value="#{car.id}" />
      </p:column>
      <p:column headerText="Year">
          <h:outputText value="#{car.year}" />
      </p:column>
      <p:column headerText="Mileage">
          <h:outputText value="#{car.mileage}">
              <f:convertNumber />
          </h:outputText>
      </p:column>
      <p:column headerText="Brand">
          <h:outputText value="#{car.brand}" />
      </p:column>
      <p:column headerText="Color">
          <h:outputText value="#{car.color}" />
      </p:column>
  </p:dataTable>
```

### Expected behavior

rowHover attribute should be respected in PrimeFaces 12.

### PrimeFaces edition

_No response_

### PrimeFaces version

12.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

Edge

### PR DESCRIPTION
**Pull request by jasonex7**
Fixes #9025 

It seems this problem was introduced while fixing #8620 specifically in commit https://github.com/primefaces/primefaces/commit/dbf8912705925d13e281bd6ff0c40cd2ead56dc4. I'm creating a PR reverting partially that commit. Maybe @ihsanyapicioglu could review it.

### CODE REVIEW

**Comment by melloware** [comment]
I think you reverted too much.  When I worked with @ihsanyapicioglu on issue #8620 i thought it should have been this one line fix.

basically its a 1 line fix in datatable.js change...
```js
 var checkboxes = this.tbody.find('> tr.ui-datatable-selectable > td.ui-selection-column > div.ui-chkbox > div.ui-chkbox-box:visible'),
```
to
```js
var checkboxes = this.jq.find('tr.ui-datatable-selectable > td.ui-selection-column > div.ui-chkbox > div.ui-chkbox-box:visible'),
```

it has to find the checkboxes in both the frozen table and regular table and it was only searching through TBODY of the regular table

**Comment by melloware** [comment]
What was happening with frozen you can use this reproducer:
[pf-8260.zip](https://github.com/primefaces/primefaces/files/9173646/pf-8260.zip)

When you clicked hte SelectAll checkbox it was not selecting them all

 
image

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -2842,7 +2842,7 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
     toggleCheckAll: function() {
         var shouldCheckAll = true;
         if(this.cfg.nativeElements) {
-            var checkboxes = this.jq.find('tr.ui-datatable-selectable > td.ui-selection-column > :checkbox:visible'),
+            var checkboxes = this.tbody.find('tr.ui-datatable-selectable > td.ui-selection-column > :checkbox:visible'),
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js]: I think you have to leave this line

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 2]
```diff
@@ -2861,7 +2861,7 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
             });
         }
         else {
-            var checkboxes = this.jq.find('tr.ui-datatable-selectable > td.ui-selection-column > div.ui-chkbox > div.ui-chkbox-box:visible'),
+            var checkboxes = this.tbody.find('tr.ui-datatable-selectable > td.ui-selection-column > div.ui-chkbox > div.ui-chkbox-box:visible'),
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js]: I think you have to leave this line

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
