### PR TITLE
Fix #5912: DatePicker incorrect behavior with keyboard entry

### LINKED ISSUE #5912: DatePicker: with pattern has confusing behaviour when editing
p:datePicker in PrimeFaces-8.0 (and earlier) seem to have a confusing behavior when editing the input field. 

In PrimeFaces Showcase, p:datePicker with id="german" (that has pattern="dd.MM.yyy" and locale="de") : enter value 01.01.2020, click between 0 and 1 either on day or month and press Backspace (like user wants to change 01 to 10). -> the cursor jumps to the end of input value and nothing gets deleted. This is at least confusing and can cause invalid values to be entered if user does not check carefully what happens on page. 

This p:datePicker behavior could probably be categorized as a bug because p:calendar behaves more logically with same input sequence. 

This might be related to handling of locale as kukeltje on PrimeFaces forum indicated that it seems to work correctly with some locales.

### PR DESCRIPTION
**Pull request by christophs78**
- [x] My first steps to decouple the update of the input-field from the update of the model and DatePicker-widget. I think this already improves input-behaviour.
- [x] I´ll try to add some code which does the reformating on focus-lost as next step and add this to this PR.
- [x] And maybe we can add something to accept 2-digits-year-inpuz also for 4-digit-patterns.

As already said before people choose libraries like PrimeFaces because they expect this things to work. And now we are as a community on a point where we need to fix dozens of issues for DatePicker. PrimeTek released DatePicker in sub-par quality with 7.0. And now we as community need to do this work.

### CODE REVIEW

**Comment by melloware** [comment]
I totally agree with you that we need to do whatever it takes to make this component work like a user expects it to work.

This is an excellent PR and improves the component behavior quite a bit.

File: src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 1]
```diff
@@ -1704,6 +1709,9 @@
                 this.options.onBlur.call(this, event);
             }
 
+            //reformat input - is always OK? or only if it was modified?
```
Comment (melloware) [inline src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]: I think its safe to remove this comment I think we should always format unless we find it to be a problem.

**Review by melloware — APPROVED** [review]

File: src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 2]
```diff
@@ -2488,9 +2495,11 @@
             this._setInitOptionValues();
         },
 
-        updateModel: function (event, value) {
+        updateModel: function (event, value, updateInput) {
             this.value = (value === '' ? null : value);
-            this.inputfield.val(this.getValueToRender());
+            if (updateInput != false) {
```
Comment (melloware) [inline src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:2500]: I think you can just say `if (updateInput)` and its truthiness will only enter the block if the value is `true` rather than checking for !false

**Review by melloware — CHANGES_REQUESTED** [review]

File: src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js (hunk 2 above)
Comment (christophs78) [reply src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js:2500]: No, not that easy. updateInput is only passed when i want to disable input-update. All other calls to this function are without this parameter.
So we may change this. But this requires all other calls to this function to pass true for the third parameter.

**Review by melloware — APPROVED** [review]
