### PR TITLE
ValueExpressionStateHelper: implement Faces 4.0 eval

### LINKED ISSUE #13038: ValueExpressionStateHelper does not implement Faces 4.0 eval
`StateHelper#eval(Serializable, Supplier)` was introduced in Faces 4.0: https://jakarta.ee/specifications/faces/4.0/apidocs/jakarta/faces/component/statehelper#eval(java.io.Serializable,java.util.function.Supplier)

This exception is thrown when this method is invoked
`java.lang.AbstractMethodError: Receiver class org.primefaces.el.ValueExpressionStateHelper does not define or inherit an implementation of the resolved method 'abstract java.lang.Object eval(java.io.Serializable, java.util.function.Supplier)' of interface jakarta.faces.component.StateHelper.`

PrimeFaces cannot @Override this right now for obvious reasons, but it should be possible to just implement this IMO

### PR DESCRIPTION
**Pull request by jungm**
Fixes #13038

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/el/ValueExpressionStateHelper.java [hunk 1]
```diff
@@ -108,6 +111,19 @@ public Object eval(Serializable key, Object defaultValue) {
         return ve.getValue(FacesContext.getCurrentInstance().getELContext());
     }
 
+    public Object eval(Serializable key, Supplier<Object> defaultValueSupplier) {
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/el/ValueExpressionStateHelper.java:115]: please add ``// @Override`

Comment (jungm) [reply primefaces/src/main/java/org/primefaces/el/ValueExpressionStateHelper.java:115]: done
