### PR TITLE
Fix #8765/#7767/#7763/#7765/#3781: AutoComplete/SelectOneMenu/RowExpansion/OrderList duplicate ids

### LINKED ISSUE #7767: SelectOneMenu: duplicate ids with custom content
**Describe the defect**
Using selectOneMenu with custom content results in duplicate ids.

**Reproducer**
[primefaces-7767-selectonemenu-custom-content-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/7068606/primefaces-7767-selectonemenu-custom-content-duplicate-ids.zip)
(Targets 10.0.0 instead of master-SNAPSHOT due to #7739.)

**Environment:**
 - PF Version: _6.2.30_, _10.0.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Open the reproducer.
2. See the error message in the browser console (a script detects duplicate ids and logs them).
image

**Expected behavior**
Client ids should probably include iteration, like with ui:repeat: "x:1:y", "x:2:y"...

**Example XHTML**
```html
<h:form id="form">
	<p:selectOneMenu id="menu" var="v">
		<f:selectItems value="#{testView.selectItems}" />
		<p:column>
			<h:outputText id="item_id" value="#{v.id}" />
		</p:column>
		<p:column>
			<h:outputText id="item_name" value="#{v.name}" />
		</p:column>
	</p:selectOneMenu>
</h:form>

<script>
	function checkDuplicateIds() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	}
	checkDuplicateIds();
</script>
```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {
    
	private List<TestBean> data = Arrays.asList(new TestBean(0, "Zero"),
			new TestBean(1, "One"), new TestBean(2, "Two"));

	public List<SelectItem> getSelectItems() {
		return data.stream().map(bean -> new SelectItem(bean, bean.getName())).collect(Collectors.toList());
	}

	public static class TestBean {

		private Integer id;
		private String name;

		public TestBean() {
		}

		public TestBean(Integer id, String name) {
			this.id = id;
			this.name = name;
		}

		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		@Override
		public String toString() {
			return getId() + " " + getName();
		}

	}

}
```

### LINKED ISSUE #8765: Core: Prevent duplicate IDs in DOM
### Describe the bug

PrimeFaces has a few places where duplicate IDs are present in the DOM.  This issue is to track all of them in 1 spot.  Most of the time its in places where PF uses `UIColumn` to iterate over some advanced rendering but not always.

**Why is it bad?**
https://softwareengineering.stackexchange.com/questions/127178/two-html-elements-with-same-id-attribute-how-bad-is-it-really

**Components Affected:**
- [x] AutoComplete (https://github.com/primefaces/primefaces/issues/7763
- [x] SelectOneMenu (https://github.com/primefaces/primefaces/issues/7767)
- [x] OrderList (https://github.com/primefaces/primefaces/issues/3781)
- [ ] DataTable RowExpansion (https://github.com/primefaces/primefaces/issues/7765)
- [ ] Diagram (https://github.com/primefaces/primefaces/issues/9551)

- [x] SelectCheckBoxMenu (https://github.com/primefaces/primefaces/issues/4696)

**Possible Solutions:**
1. Just ignore it until browser doesn't support it anymore
2. Commit a fast workaround (https://github.com/primefaces/primefaces/pull/8761)
3. Do it the right JSF way, which takes a long time using `UIRepeat / UINamingContainer`

### Reproducer

Great example from https://github.com/primefaces/primefaces/issues/7767 on how to test with SelectOne and use a script to check for duplicate ID's.

```xml
<h:form id="form">
	<p:selectOneMenu id="menu" var="v">
		<f:selectItems value="#{testView.selectItems}" />
		<p:column>
			<h:outputText id="item_id" value="#{v.id}" />
		</p:column>
		<p:column>
			<h:outputText id="item_name" value="#{v.name}" />
		</p:column>
	</p:selectOneMenu>
</h:form>

<script>
	function checkDuplicateIds() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	}
	checkDuplicateIds();
</script>
```

### Expected behavior

No components should generate duplicate ID's and all ID's in the DOM should be unique.

Client ids should probably include iteration, like with UI "x:1:y", "x:2:y"...

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

ANY

### JSF implementation

All

### JSF version

ALL

### Browser(s)

ALL is

### PR DESCRIPTION
**Pull request by melloware**
Fix #8765  AutoComplete/SelectOneMenu/RowExpansion/OrderList/SelectCheckboxMenu duplicate ids
Fix #7767/#7763/#7765/#3781: AutoComplete/SelectOneMenu/RowExpansion/OrderList/SelectCheckboxMenu duplicate ids

I am reviving this PR since @ltlBeBoy just added support for SelectCheckBoxMenu and @Bukama has pointed out duplicate ID's cause Accessibility issues.

@tandraschko I know you said this should be done with UIRepeat/NamingContainer but honestly I looked all over for examples and studied the code and I could not figure out how to make these components easily support that for this "Advanced" rendering feature.  Any hints would be great but I think we might need to go with this short term solution until a longer term solution can be found?

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 1]
```diff
@@ -608,6 +608,34 @@ public static boolean isNestedWithinIterator(UIComponent component) {
...
+
+        // encode the component
+        component.encodeAll(context);
+
+        // restore the original writer
+        context.setResponseWriter(writer);
+
+        // append index to all id's
+        String encodedComponent = fsw.toString();
+        encodedComponent = encodedComponent.replaceAll("\\sid=\"(.*?)\"", " id=\"$1:" + index + "\"");
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: Separator char could be configured to something different then `:`

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: You are right!

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 2]
```diff
@@ -630,8 +630,9 @@ public static void encodeIndexedId(FacesContext context, UIComponent component,
         context.setResponseWriter(writer);
 
         // append index to all id's
+        char separator = UINamingContainer.getSeparatorChar(context);
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:633]: Is this a costly operation? If so maybe cache the separator char?

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:633]: I don't think its costly its done all over the code base.  Maybe a question for @tandraschko whether we want to cache it in `Lazy` in PrimeEnvironment?

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:633]: Just asking as we are iterating over a list of items.. 🙂

File: primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java [hunk 3]
```diff
@@ -46,11 +46,7 @@
 import org.primefaces.expression.SearchExpressionUtils;
 import org.primefaces.renderkit.InputRenderer;
 import org.primefaces.renderkit.SelectManyRenderer;
-import org.primefaces.util.ComponentUtils;
-import org.primefaces.util.Constants;
-import org.primefaces.util.HTML;
-import org.primefaces.util.MessageFactory;
-import org.primefaces.util.WidgetBuilder;
+import org.primefaces.util.*;
```
Comment (Bukama) [inline primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java]: Star-Import wanted or by accident?

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 4]
```diff
@@ -608,6 +608,35 @@ public static boolean isNestedWithinIterator(UIComponent component) {
...
+        // encode the component
+        component.encodeAll(context);
+
+        // restore the original writer
+        context.setResponseWriter(writer);
+
+        // append index to all id's
+        char separator = UINamingContainer.getSeparatorChar(context);
+        String encodedComponent = fsw.toString();
+        encodedComponent = encodedComponent.replaceAll("\\sid=\"(.*?)\"", " id=\"$1" + separator + index + "\"");
```
Comment (Bukama) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:635]: Just to avoid a mindgap. Does `id=\"$1"` already contains the first separator, so you only need to add the second and the index to achieve `id="form:test:0"`

**Review by Bukama — APPROVED** [review]

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 4 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java:635]: yes the capture group captures the entire current ID so can then append `:1`, `:2` etc onto it!

File: primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java (hunk 3 above)
Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java]: Our standard policy on PrimeFaces is that once you have 5 imports from the same package switch it to *.  My IDE is set to do that automatically.

**Comment by tandraschko** [comment]
Need to think about it

**Comment by melloware** [comment]
No problem.. even if you could give me a hint on how it could be done a more proper way that would be great.

**Comment by tandraschko** [comment]
Why do we need a ID anyway in such cases?

**Comment by melloware** [comment]
@Bukama do you have a specific accessibility use case where having the duplicate id's causes issues?

Also I think the issue is @VsevolodGolovanov mentioned it in his issue its not how any other JSF component works and we can't stop people from doing this:

```xml
<p:selectOneMenu id="menu" var="v">
		<f:selectItems value="#{testView.selectItems}" />
		<p:column>
			<h:outputText id="item_id" value="#{v.id}" />
		</p:column>
		<p:column>
			<h:outputText id="item_name" value="#{v.name}" />
		</p:column>
	</p:selectOneMenu>
```

Maybe they need unique ID's for from JS code that have written or some Selenium Test code?

**Comment by Bukama** [comment]
> @Bukama do you have a specific accessibility use case where having the duplicate id's causes issues?

Duplicate Ids are a) not valid HTML, therefor it validates SC 4.1.1 which is one criteria of the WVAG as valid HTML is THE base for assistence technologies. Having duplicate ids those technologies either can't identify the correct element and/or (screenreaders) tend to double speaking as multiple elements are read out loud. These kind of errors are making every accessibility test fail "instantly" as they are from the most weightend error class.

> Maybe they need unique ID's for from JS code that have written or some Selenium Test code?

Well it's coming to the same point as the assistence technologies - identifying the right element. So you could argue to gains at once ;)

**Comment by melloware** [comment]
Thank you @Bukama for your insight!

**Comment by tandraschko** [comment]
also need to think about it, currently i dont have much time for PF as i mostly help to bring Apache EE10 stuff out

**Comment by melloware** [comment]
@tandraschko if you look at the current merge conflict you will see @christophs78 had to do exactly what I am proposing in this fix to make the AutoComplete properly accessible.

**Comment by tandraschko** [comment]
yep
can you resolve conflicts? i'm ok to apply it if you aligned autoComplete with others

**Comment by melloware** [comment]
Resolved and all IT's passing.
