### PR TITLE
Fix #9093: InputNumber: decimalPlaces not defaulting correctly on numeric types with null value

### LINKED ISSUE #9093: InputNumber: decimalPlaces not defaulting correctly on numeric types with null value
### Describe the bug

If the value is `null` the type of the bound value should be checked

https://github.com/primefaces/primefaces/blob/fcced6df36579bc34f09b03b683f31fdee8f0ce3/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java#L393-L395

### Reproducer

Bind to an `Integer` type of which the value is `null`

### Expected behavior

`decimalPlaces` should be 0 instead of 2, because the value is of type `Integer` although the value is `null`.

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

_No response_

### JSF implementation

_No response_

### JSF version

_No response_

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9093

### CODE REVIEW

**Comment by jepsar** [comment]
I think the failing test is wrong:
```java
        // NOTE: because its now NULL the default decimal places is set back to 2 because its no longer an Integer
        assertConfiguration(inputNumber.getWidgetConfiguration(), "2", "0.0000001", "999999");
```
That's exactly what has changed in this PR. Shall I change the test value from 2 to 0?

**Comment by jepsar** [comment]
Done.

File: primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java [hunk 1]
```diff
@@ -391,7 +394,24 @@ private String getMaximum(InputNumber inputNumber, Object value) {
...
+                || value instanceof Byte;
+    }
+
+    private boolean isIntegral(FacesContext context, InputNumber inputNumber) {
+        ValueExpression valueExpression = inputNumber.getValueExpression("value");
+        if (valueExpression == null) {
+            return false;
+        }
+        Class<?> type = valueExpression.getType(context.getELContext());
+        return type.isAssignableFrom(Long.class)
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java:409]: Maybe you can simplify by moving these conditions in isIntegral(Object value) and then you can directly call in isIntegral(FacesContext context, InputNumber inputNumber)? To avoid repetition

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java:409]: Agreed!   Other than that looks great

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by melloware** [comment]
> I think the failing test is wrong:
> 
> ```java
>         // NOTE: because its now NULL the default decimal places is set back to 2 because its no longer an Integer
>         assertConfiguration(inputNumber.getWidgetConfiguration(), "2", "0.0000001", "999999");
> ```
> 
> That's exactly what has changed in this PR. Shall I change the test value from 2 to 0?

Yes you have fixed the code propertly so the unit test should be changed accordingly.

File: primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java (hunk 1 above)
Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java:409]: Right, it's better now. I also optimized it a bit (it was called three times in a row)

**Review by melloware — APPROVED** [review]
