### PR TITLE
Fix #12989: Cell Editor with SelectOne blocking tab control

### LINKED ISSUE #12989: DataTable: Editable cell with p:selectonemenu not moving focus properly with tab key
### Describe the bug

When pressing the 'tab' key in an editable datatable, focus is not moving to the next column properly on tab out if the cell contains a `p:selectOneMenu`.

### Reproducer

_No response_

### Expected behavior

Focus will move to the next column when tabbing out of an editable cell containing a `p:selectOneMenu`

### PrimeFaces edition

Community

### PrimeFaces version

14.0.7

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12989: 14.0.9 Cell Editor with SelectOne blocking tab control

This was because of the restructure of SelectOne for ARIA and Keyboard accessibility

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js [hunk 1]
```diff
@@ -3910,7 +3913,11 @@ PrimeFaces.widget.DataTable = PrimeFaces.widget.DeferredWidget.extend({
                             if(multi) {
                                 var focusIndex = shiftKey ? input.index() - 1 : input.index() + 1;
 
-                                if(focusIndex < 0 || (focusIndex === inputs.length) || input.parent().hasClass('ui-inputnumber') || input.parent().hasClass('ui-helper-hidden-accessible')) {
+                                var parent = input.parent();
+                                if(focusIndex < 0 || focusIndex === inputs.length ||
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:3922]: please add some comment here

Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js:3922]: comments added
