### PR TITLE
Fix #12862 FileUpload: handle invalid filename like url-encoded characters (%20) as validation error

### LINKED ISSUE #12862: fileUpload: handle invalid filename like url-encoded characters (%20) as validation error
### Describe the bug

If i try to upload a file whose filename contains url encoded characters like %20 (example 'attrezzatura+r%C3%A4te_signed.pdf') the component throws an exception (ValidatorException), but should display only an error message.

You can try this behaviour using showcase and the attached file
attrezzatura+informatica+-+EDV-Ger%C3%A4te_signed

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

all

### PR DESCRIPTION
**Pull request by melloware**
Fix #12862 FileUpload: handle invalid filename like url-encoded characters (%20) as validation error

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java [hunk 1]
```diff
@@ -86,29 +92,29 @@ private FileUploadUtils() {
      */
     public static String requireValidFilename(String filename) {
         if (LangUtils.isBlank(filename)) {
-            throw validationError("Filename cannot be empty or null");
+            throw validationError(MessageFactory.getMessage(FILE_LIMIT_KEY));
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: why FILE_LIMIT? thats for amount of uploaded files, not related to filename
sounds more like a FILENAME_EMPTY?

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: Yep fixing it now

File: primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java [hunk 2]
```diff
@@ -396,7 +401,7 @@ void requireValidFilename_NotBlank() {
         ValidatorException ex = assertThrows(ValidatorException.class, () -> FileUploadUtils.requireValidFilename(invalidFileName));
 
         // Assert
-        assertEquals("Filename cannot be empty or null", ex.getFacesMessage().getDetail());
+        assertEquals("primefaces.FileValidator.FILENAME_NOT_NULL", ex.getFacesMessage().getDetail());
```
Comment (tandraschko) [inline primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java]: shouldnt you check the real message here instead of the key?

Comment (melloware) [reply primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java]: It can't it blows up because three is not FacesContext. 

```
Unexpected exception type thrown, expected: <javax.faces.validator.ValidatorException> but was: <java.lang.NullPointerException>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
        at org.primefaces.util.FileUploadUtilsTest.requireValidFilename_NotBlank(FileUploadUtilsTest.java:401)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.faces.context.FacesContext.getApplication()" because "facesContext" is null
        at org.primefaces.util.MessageFactory.getMessage(MessageFactory.java:142)
        at org.primefaces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at org.primefaces.util.FileUploadUtils.requireValidFilename(FileUploadUtils.java:95)
        at org.primefaces.util.FileUploadUtilsTest.lambda$11(FileUploadUtilsTest.java:401)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
```

Comment (melloware) [reply primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java]: Wait I think I can mock the static testing it now.

Comment (melloware) [reply primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java]: Had to wrap it in this and it works!

```java
 try (MockedStatic<FacesContext> facesContext = Mockito.mockStatic(FacesContext.class)) {
            facesContext.when(FacesContext::getCurrentInstance).thenReturn(context);

}

```

**Comment by tandraschko** [comment]
TBH
we just pass FacesContext to MessageFactory

but we can do it a seperate ticket; wanna create it?

**Comment by melloware** [comment]
Yep I will create it

File: primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java [hunk 3]
```diff
@@ -69,6 +69,12 @@ public class FileUploadUtils {
 
     private static final Logger LOGGER = Logger.getLogger(FileUploadUtils.class.getName());
 
+    // Message keys
+    private static final String FILENAME_INVALID_NULL = "primefaces.FileValidator.FILENAME_NOT_NULL";
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: either add _KEY or remove _KEY from others
i prefer without _KEY

also its currenlty inverted
FILENAME_NOT_NULL, FILENAME_INVALID_CHAR

i would just call it FILENAME_EMPTY

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: good catch I have fixed them

File: primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java [hunk 4]
```diff
@@ -69,6 +69,12 @@ public class FileUploadUtils {
 
     private static final Logger LOGGER = Logger.getLogger(FileUploadUtils.class.getName());
 
+    // Message keys
+    private static final String FILENAME_EMPTY = "primefaces.FileValidator.FILENAME_NOT_NULL";
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: also change the string please

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: Fixed also updated the localization.md docs
