### PR TITLE
#11071 - Better spanish translation

### LINKED ISSUE #11071: Better spanish translation
### Describe the bug

I attach the files of the Spanish version of both Java and Javascript with a better translation.
[primefaces-13.0.3-spanish_locale.zip](https://github.com/primefaces/primefaces/files/13557843/primefaces-13.0.3-spanish_locale.zip)

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by JuanMiguelBG**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@SoyDiego not sure if you want to review these and roll some of these into PrimeLocale?

**Comment by SoyDiego** [comment]
> @SoyDiego not sure if you want to review these and roll some of these into PrimeLocale?

Thanks @melloware I can check it now. But I think in some of them there are "errors" in my opinion.
I will leave comments in the code.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 1]
```diff
@@ -71,11 +71,11 @@ if (window.PrimeFaces) {
       pageLabel: "Página {page}",
       firstPageLabel: "Primera Página",
       lastPageLabel: "Última Página",
-      nextPageLabel: "Siguiente Página",
+      nextPageLabel: "Página Siguiente",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:74]: I think "Siguiente Página" was ok.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 2]
```diff
@@ -85,10 +85,10 @@ if (window.PrimeFaces) {
       filterOperator: "Operador de filtro",
       filterConstraint: "Restricción de filtro",
       editRow: "Editar fila",
-      saveEdit: "Guardar editado",
-      cancelEdit: "Cancelar editado",
-      listView: "Vista de lista",
-      gridView: "Vista de cuadrícula",
+      saveEdit: "Guardar cambios",
+      cancelEdit: "Descartar cambios",
+      listView: "Mostrar como lista",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:90]: "Ver como lista", IMO.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 3]
```diff
@@ -85,10 +85,10 @@ if (window.PrimeFaces) {
...
+      gridView: "Mostrar como cuadrícula",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:91]: "Ver como cuadrícula", IMO.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 4]
```diff
@@ -116,26 +116,26 @@ if (window.PrimeFaces) {
...
     list: "Agenda",
     allDayText: "Todo el día",
-    moreLinkText: "Más....",
+    moreLinkText: "Más...",
     noEventsText: "No hay eventos",
     aria: {
-      "datatable.sort.ASC": "ordenar columna ascendente",
-      "datatable.sort.DESC": "ordenar columna descendente",
-      "datatable.sort.NONE": "eliminar la clasificación en la columna",
+      "datatable.sort.ASC": "ordenar columna ascendentemente",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:122]: "Ordenar columna de forma ascendente", IMO.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 5]
```diff
@@ -116,26 +116,26 @@ if (window.PrimeFaces) {
...
+      "datatable.sort.DESC": "ordenar columna descendentemente",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:123]: "Ordenar columna de forma descendente", IMO.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 6]
```diff
@@ -116,26 +116,26 @@ if (window.PrimeFaces) {
...
+      "datatable.sort.NONE": "eliminar la ordenación de la columna",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: "Eliminar el orden de la columna", IMO.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 7]
```diff
@@ -144,68 +144,68 @@ if (window.PrimeFaces) {
...
       "javax.faces.converter.FloatConverter.FLOAT_detail": "{2}: '{0}' debe ser un número entre 1.4E-45 y 3.4028235E38  Ejemplo: {1}",
       "javax.faces.converter.DateTimeConverter.DATE": "{2}: '{0}' no se ha podido reconocer como fecha.",
       "javax.faces.converter.DateTimeConverter.DATE_detail": "{2}: '{0}' no se ha podido reconocer como fecha. Ejemplo: {1}",
       "javax.faces.converter.DateTimeConverter.TIME": "{2}: '{0}' no se ha podido reconocer como hora.",
       "javax.faces.converter.DateTimeConverter.TIME_detail": "{2}: '{0}' no se ha podido reconocer como hora. Ejemplo: {1}",
       "javax.faces.converter.DateTimeConverter.DATETIME": "{2}: '{0}' no se ha podido reconocer como fecha y hora.",
       "javax.faces.converter.DateTimeConverter.DATETIME_detail": "{2}: '{0}' no se ha podido reconocer como fecha y hora. Ejemplo: {1}",
-      "javax.faces.converter.DateTimeConverter.PATTERN_TYPE": "{1}: debe especificarse el atributo 'pattern' o 'type' para convertir el valor '{0}'",
+      "javax.faces.converter.DateTimeConverter.PATTERN_TYPE": "{1}: debe especificarse el atributo 'patrón' o 'tipo' para convertir el valor '{0}'",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:179]: I'm not sure in this case but I think the words "patrón"y "tipo" should be in English.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 8]
```diff
@@ -144,68 +144,68 @@ if (window.PrimeFaces) {
...
-      "javax.faces.validator.LengthValidator.MAXIMUM": "{1}: Error de validación: el largo es mayor que el máximo permitido de '{0}'",
-      "javax.faces.validator.RegexValidator.PATTERN_NOT_SET": "Se debe establecer el patrón de Regex.",
-      "javax.faces.validator.RegexValidator.PATTERN_NOT_SET_detail": "El patrón Regex debe establecerse en un valor no vacío.",
-      "javax.faces.validator.RegexValidator.NOT_MATCHED": "El patrón Regex no coincide",
-      "javax.faces.validator.RegexValidator.NOT_MATCHED_detail": "El patrón Regex de '{0}' no coincide",
-      "javax.faces.validator.RegexValidator.MATCH_EXCEPTION": "Error en expresión regular.",
-      "javax.faces.validator.RegexValidator.MATCH_EXCEPTION_detail": "Error en expresión regular, '{0}'",
+      "javax.faces.validator.LengthValidator.MINIMUM": "{1}: Error de validación: La longitud es inferior al mínimo permitido de '{0}'",
+      "javax.faces.validator.LengthValidator.MAXIMUM": "{1}: Error de validación: La longitud es superior al máximo permitido de '{0}'",
+      "javax.faces.validator.RegexValidator.PATTERN_NOT_SET": "El patrón de la expresión regular no debe estar vacío.",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:190]: "El patrón de la expresión regular no puede estar vacío.", IMO

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 9]
```diff
@@ -144,68 +144,68 @@ if (window.PrimeFaces) {
...
+      "javax.faces.validator.RegexValidator.PATTERN_NOT_SET_detail": "El patrón de la expresión regular no debe estar vacío.",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:191]: "El patrón de la expresión regular no puede estar vacío.", IMO

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties [hunk 10]
```diff
@@ -15,4 +15,4 @@ primefaces.password.INVALID_MATCH = {0}: Error de validación.
 primefaces.password.INVALID_MATCH_detail = {0} debería coincidir con {1}.
 primefaces.slider.OUT_OF_RANGE = {0}: Error de validación: el valor está fuera de rango.
 primefaces.tree.REQUIRED = {0}: Error de validación.
-primefaces.tree.REQUIRED_detail = Se requiere selección.
\ No newline at end of file
+primefaces.tree.REQUIRED_detail = Selección obligatoria.
```
Comment (SoyDiego) [inline primefaces/src/main/resources/org/primefaces/Messages_es.properties:18]: I need to see the context of this translation but I think maybe can be better: "La selección es requerida."

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties [hunk 11]
```diff
@@ -1,4 +1,4 @@
-primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Error de validación: La fecha de inicio es mayor que la fecha de finalización.
+primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Error de validación: La fecha de inicio es posterior a la fecha de fin.
```
Comment (SoyDiego) [inline primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: "Error de validación: La fecha de inicio es posterior a la fecha final.", IMO

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 12]
```diff
@@ -71,11 +71,11 @@ if (window.PrimeFaces) {
       pageLabel: "Página {page}",
       firstPageLabel: "Primera Página",
       lastPageLabel: "Última Página",
-      nextPageLabel: "Siguiente Página",
+      nextPageLabel: "Página Siguiente",
       previousPageLabel: "Página Anterior",
       rowsPerPageLabel: "Filas por página",
-      jumpToPageDropdownLabel: "Ir al menú desplegable de página",
-      jumpToPageInputLabel: "Ir a la entrada de página",
+      jumpToPageDropdownLabel: "Menú desplegable para ir a una página",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:77]: I need to see the context of this but "Ir al menu desplegable", IMO.
Also I don't know if is something like "Ir a la página X". I need to see the context / design @melloware (in some of them I have doubts because I need to see where is applying)

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js [hunk 13]
```diff
@@ -71,11 +71,11 @@ if (window.PrimeFaces) {
...
+      jumpToPageInputLabel: "Entrada para ir a una página",
```
Comment (SoyDiego) [inline primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:78]: Same here, maybe is "Ir a una pagina" or "Ir a la página X" because the variable name is "jumpToPage". I cannot see the context @melloware

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 12 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:77]: Most of these are related to the datatable Paginator:
image

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 13 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:78]: Its for the paginator:

image

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 1 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:74]: In Spanish/Castellan, you need to folow some semantic rules.

If you use

`nextPageLabel: "Página Siguiente",` 

then you need to change

`previousPageLabel: "Página Anterior",`

to

`previousPageLabel: "Anterior Página",`

because they have the same semantic context.

It's more correct say

"Página Siguiente"

example:

- Veamos la página siguiente (rigth)

- Veamos la siguiente página (rigth, understable but not ussually used)

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 3 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:91]: The 'ver' verb, is applicate to the human subject, it's an action does by humans or animals, not applicable to the list or grid objects. The correct verb is `mostrar`.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 1 above)
Comment (SoyDiego) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:74]: In my opinion is more usually use ''Siguiente página'' than ''Página siguiente''

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 4 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:122]: 'de forma ascendente' or 'ascendentemente' are synonims.
'de forma ascendente' is more polite/formal.

Comment (SoyDiego) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:122]: Maybe, but I haven't seen any Spanish website with ''ascendentemente''. Is more clear ''... de forma ascendente''

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: In that context, 

'Eliminar el orden de la columna' and 'eliminar la ordenación de la columna' They have same meaning. More polite/formal the second.

@SoyDiego you need to maintain the same context in the text. You use formal text or expression in some texts, but not in others.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 7 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:179]: Yes, I've have doubts too. Maybe, not need to change.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 8 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:190]: Yes, It's better to use `puede` than `debe`.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 9 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:191]: Yes, It's better to use `puede` than `debe`.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (SoyDiego) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: The translation in my opinion should not be VERY polite and for example in others Spanish (Argentinian) translations, ''ordenación'' is wrong. Search another website or translations in other websites and you will see your text is super super polite and are not like the typical translations.

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties (hunk 10 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:18]: In Spanish/castellan, the word `requerida` isn't usually used, the usually word used `obligatoria/obligatorio`. `requerida/requerido` it's normally used in technical context. This message is for user. The best option is to use `Selección obligatoria`.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 1 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:74]: Where are you from?

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 4 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:122]: Yes, it's rigth.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: `Argentinian`, thas the problem. You make an es_AR traslation, not an es_ES traslation.

In es_ES, the formal/polite text is `eliminar la ordenación de la columna`.

Yes, my text is super super polite because I've required to use with very restricted accessibility rules.

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties (hunk 11 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: The same problem again.

If you use the word `inicio`, you are required to use the word `fin`, to respect the semantic context.
To use the word `final`, it's required to use the word `inicial` and not `inicio`.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (SoyDiego) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: > 'Argentinian', thas the problem. You make an es_AR traslation, not an es_ES traslation.
> 
> In es_ES, the formal/polite text is 'eliminar la ordenación de la columna'.

Is not a problem. Always the translations we're ok in all the websites. Is the first time that I read some translations like yours.  And yes I'm Argentinian but I'm living in Spain since 2011 and I know when translations are not ok. Should be more neutral.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 12 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:77]: Accessibility context. The text is used by OCR (On Screen Reader).

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 13 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:78]: Accessibility context. The text is used by OCR (On Screen Reader).

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties (hunk 11 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: The right values are

`primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Error de validación: La fecha de inicio es posterior a la fecha de fin.`

or

`primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Error de validación: La fecha de inicial es posterior a la fecha final.`

Comment (SoyDiego) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: Problem? Show me websites exactly with your translations. I can show you a lot of examples with my suggestions and anyone with yours.
I think should be more neutral like all the projects

Comment (JuanMiguelBG) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: I work to public administration, I need to follow the RAE rules.

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (JuanMiguelBG) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: Sorry, but just because you think it's correct, doesn't mean it is, even if it's understandable.

In Spain/Castilian we must follow the rules of the RAE.

File: primefaces/src/main/resources/org/primefaces/Messages_es.properties (hunk 11 above)
Comment (SoyDiego) [reply primefaces/src/main/resources/org/primefaces/Messages_es.properties:1]: @melloware is my last comment here. My final opinion is all should be in a neutral Spanish (like always my suggestions) , if not, we can have 10 translations more, for example Mexican, Bolivian, Chile, etc...

You decide what is the best for the project but if I'm not wrong with primelocale every user can personalise the translations, right?

File: primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js (hunk 6 above)
Comment (SoyDiego) [reply primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js:124]: > Sorry, but just because you think it's correct, doesn't mean it is, even if it's understandable.
> 
> In Spain/Castilian we must follow the rules of the RAE.

Sorry but just because you work in public administration doesn't mean it's correct for all the people that use primefaces in the world it is correct and very very very polite. There are people from all the world using it and again, my suggestions are Spanish **NEUTRAL** for all (is not Argentinian, is not Bolivian, is not Castillan, is neutral).
 @melloware can decide what is the best for the project 🙂. Bye
