### PR TITLE
Fix #14628: MegaMenu allow custom content in columns

### LINKED ISSUE #14628: MegaMenu: Can't place customized content in a menuItem column
### Describe the bug

The PF 15 documentation for `megaMenu` says:

    Any content can be placed inside columns.

    <p:column>
        <strong>Sopranos</strong>
        <p:graphicImage value="/images/sopranos/sopranos1.jpg" width="200"/>
    </p:column>

However, doing that results in the following exception:

    jakarta.servlet.ServletException: java.io.IOException: jakarta.servlet.ServletException: class 
    com.sun.faces.facelets.compiler.UIInstructions cannot be cast to class  org.primefaces.model.menu.MenuElement (com.sun.faces.facelets.compiler.UIInstructions and  org.primefaces.model.menu.MenuElement are in unnamed module of loader  org.eclipse.jetty.ee.webapp.WebAppClassLoader @36790bec)

[pf.zip](https://github.com/user-attachments/files/24916443/pf.zip)

### Reproducer

Here are the steps required to reproduce the issue:

1. Unzip the attached file (pf.zip)
2. `cd` to the directory root
3. Run `mvn jetty:run`
4. Run `open http://localhost:8080`
5. Obesrve the exception

### Expected behavior

I expect that a `graphicImage` be placed in a `menuItem` as shown in the documentation and without exception.

### PrimeFaces edition

None

### PrimeFaces version

15.0.12

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0.14

### Java version

21

### Browser(s)

Firefox

### PR DESCRIPTION
**Pull request by melloware**
Fix #14628: MegaMenu allow custom content in columns

image

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java [hunk 1]
```diff
@@ -204,16 +205,21 @@ protected void encodeColumn(FacesContext context, MegaMenu component, MenuColumn
...
         if (column.getElementsCount() > 0) {
-            List<MenuElement> columnElements = column.getElements();
-            for (MenuElement element : columnElements) {
-                if (element.isRendered()) {
-                    if (element instanceof Submenu) {
-                        encodeDescendantSubmenu(context, component, (Submenu) element);
-                    }
-                    else if (element instanceof Separator) {
-                        encodeSubmenuSeparator(context, (Separator) element);
+            List<?> columnElements = column.getElements();
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java:208]: we need a comment here, why ? instead of MenuElement
otherwise it will get lost in future again

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java:208]: i will add a comment
