### PR TITLE
Fix #9817: PanelGrid error in responsive if not valid

### LINKED ISSUE #9817: PanelGrid: not responsive when there are 5 columns
### Describe the bug

5 columns does not responsive, other values is ok. when columns attribute is 5 output html is:
`<div class="ui-panelgrid-cell null"><span class="font-bold" style="color:rgb(255, 99, 132);">1</span></div>`
class is null, expected value is ui-md-3

### Reproducer

<p:panelGrid columns="5" styleClass="showcase-text-align-center" layout="grid">
<h:outputText value="1" class="font-bold"/>
<h:outputText value="2" class="font-bold"/>
<h:outputText value="3" class="font-bold"/>
<h:outputText value="4" class="font-bold"/>
<h:outputText value="5" class="font-bold"/>
<h:outputText value="6" class="font-bold"/>
<h:outputText value="7" class="font-bold"/>
<h:outputText value="8" class="font-bold"/>
<h:outputText value="9" class="font-bold"/>
<h:outputText value="10" class="font-bold"/>
</p:panelGrid>

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

11.0.0, 12.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

8

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #9817: PanelGrid error in responsive if not valid

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java [hunk 1]
```diff
@@ -91,8 +91,8 @@ public void encodeGridLayout(FacesContext context, PanelGrid grid) throws IOExce
         String clientId = grid.getClientId(context);
         String layout = grid.getLayout();
         int columns = grid.getColumns();
-        if (columns <= 0) {
-            throw new FacesException("Columns of PanelGrid \"" + clientId + "\" must be greater than zero in grid layout.");
+        if (columns <= 0 || 12 % columns != 0) {
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java]:
```suggestion
        if (columns <= 0 || columns > 12 || 12 % columns != 0) {
```

**Review by christophs78 — APPROVED** [review]

**Review by jepsar — APPROVED** [review]
