### PR TITLE
Fix #10609: Colorpicker double conversion

### LINKED ISSUE #10609: ColorPicker: Submitted value set to converted value.
### Describe the bug

ColorPickerRenderer.decode() sets submitted value to converted value:
`colorPicker.setSubmittedValue(ComponentUtils.getConvertedValue(context, component, submittedValue))`

This causes problems when using a converter: getAsObject() is called twice, first time with correct (submitted) value and second time with already converted value.

Obviously, converter can be made to work around this, but I doubt this is expected behaviour.

### Reproducer

https://github.com/primefaces/primefaces/files/12552676/pf-10609.zip

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0.3

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #10609: Colorpicker double conversion

I have confirmed that removing this line causes it to be called only once and properly.

**Before:**
```
getAsString null
getAsObject #853232
getAsObject 853232
Color = 853232
```

**After:** 
```
getAsString null
getAsObject #853232
Color = 853232
```

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java [hunk 1]
```diff
@@ -161,7 +160,6 @@ protected void encodeScript(FacesContext context, ColorPicker colorPicker, Strin
                 .attr("locale", colorPicker.calculateLocale(context).toString())
                 .attr("mode", colorPicker.getMode())
                 .attr("defaultColor", value, null)
-                .attr("theme", colorPicker.getTheme())
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java:164]: This was declared twice.
