### PR TITLE
Fixes #8987 - DataExporter: OutputFormat doesn't render correctly on exports

### LINKED ISSUE #8987: DataExporter: OutputFormat doesn't render correctly on exports
### Describe the bug

When exporting a DataTable that contains <h:outputFormat> in header or footer facet, the exported value doesn't render correctly.

image

### Reproducer

```xhtml
<p:dataTable id="table" var="r" value="#{testView.records}">
    <f:facet name="header">
        <h:outputFormat value="{0} - {1}">
            <f:param value="#{testView.title}" />
            <f:param value="#{testView.customMessage}" />
        </h:outputFormat>
    </f:facet>
    <p:column headerText="Text Value">
        <h:outputText value="#{r.textValue}" />
    </p:column>
    <p:column headerText="Int Value">
        <h:outputText value="#{r.intValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <f:facet name="footer">
        <h:outputFormat value="{0,number,#,##0} records.">
            <f:param value="#{testView.records.size()}" />
        </h:outputFormat>
    </f:facet>
</p:dataTable>

<h:commandLink immediate="true">
    <h:outputText value="xlsx" />
    <p:dataExporter type="xlsx" target="table" fileName="test" />
</h:commandLink>
```

### Expected behavior

image

### PrimeFaces edition

_No response_

### PrimeFaces version

11.0.0, 12.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jasonex7**
Fixes #8987

### CODE REVIEW

**Comment by melloware** [comment]
I think you can eliminate most of this PR.  You don't need to do this `RenderKit` stuff if you simply want to write to a temporary writer we do this using our `FastStringWriter` all over in the code base.

```java
ResponseWriter writer = context.getResponseWriter();

try (FastStringWriter fsw = new FastStringWriter()) {
                fsw.write("{");
                writeOption(fsw, "@context", model.getContext(), false);
                writeOption(fsw, "@type", model.getType(), true);
                encodeItems(fsw, model.getItemListType(), model.getItems(), true);
                fsw.write("}");

                writer.write(fsw.toString());
}
```

File: primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java [hunk 1]
```diff
@@ -70,4 +77,46 @@ else if (partialSelected) {
...
+                renderKitId = application.getDefaultRenderKitId();
+
+                if (renderKitId == null) {
+                    renderKitId = RenderKitFactory.HTML_BASIC_RENDER_KIT;
+                }
+            }
+        }
+
+        return ((RenderKitFactory) FactoryFinder.getFactory(FactoryFinder.RENDER_KIT_FACTORY)).getRenderKit(context, renderKitId);
+    }
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java:120]: Ithink you can remove this method

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 2]
```diff
@@ -607,4 +619,43 @@ public static String getDynamicColumnValueAsString(UIComponent component) {
...
+     * already doesn't have a HTML head nor body.
+     * @param component The component to capture HTML output for.
+     * @param context The current FacesContext.
+     * @return The encoded HTML output of the given component.
+     * @throws UncheckedIOException Whenever something fails at I/O level. This would be quite unexpected as it happens locally.
+     * @see <a href="https://github.com/omnifaces/omnifaces">Omnifaces</a>
+     */
+    public static String encodeHtml(UIComponent component, FacesContext context) {
+        ResponseWriter originalWriter = context.getResponseWriter();
+        StringWriter output = new StringWriter();
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: Just use our FastStringWriter.

**Review by melloware — CHANGES_REQUESTED** [review]

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 2 above)
Comment (jasonex7) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: FastStringWriter is not a javax.faces.context.ResponseWriter so I cannot pass directly to `context.setResponseWriter` method. I think that is the reason why the method needs the render kit instance, to create a ResponseWriter.

I've just commited a modifed version using FastStringWriter instead of StringWriter

**Comment by jasonex7** [comment]
> I think you can eliminate most of this PR. You don't need to do this `RenderKit` stuff if you simply want to write to a temporary writer we do this using our `FastStringWriter` all over in the code base.
> 
> ```java
> ResponseWriter writer = context.getResponseWriter();
> 
> try (FastStringWriter fsw = new FastStringWriter()) {
>                 fsw.write("{");
>                 writeOption(fsw, "@context", model.getContext(), false);
>                 writeOption(fsw, "@type", model.getType(), true);
>                 encodeItems(fsw, model.getItemListType(), model.getItems(), true);
>                 fsw.write("}");
> 
>                 writer.write(fsw.toString());
> }
> ```

The most uses I see of StringWriter is in render classes to generate strings which at the end are going to be writed to `ResponseWriter` of FacesContext:

```java
public static void encodeModel(FacesContext context, JsonLDModel model) throws IOException {
    if (model != null) {
        ResponseWriter writer = context.getResponseWriter();

        try (FastStringWriter fsw = new FastStringWriter()) {
            fsw.write("{");
            writeOption(fsw, "@context", model.getContext(), false);
            writeOption(fsw, "@type", model.getType(), true);
            encodeItems(fsw, model.getItemListType(), model.getItems(), true);
            fsw.write("}");

            writer.write(fsw.toString());
        }
    }
}
```

**Comment by melloware** [comment]
Hmmm but isn't that all you are doing here capturing the string of encodeAll to put in the Excel cell?

**Comment by melloware** [comment]
If you search the code base for "setResponseWriter" you will see we do this in other places in the code

**Comment by jasonex7** [comment]
OK, I used a cloned writer as in TimelineRenderer and UICacheRenderer

File: primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java (hunk 1 above)
Comment (jasonex7) [reply primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java:120]: OK, I removed to favor the use of `cloneWithWriter` method

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 2 above)
Comment (jasonex7) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: I used `cloneWithWriter` method to avoid the use of getRenderKit method

**Comment by melloware** [comment]
Excellent that is what I meant!

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 3]
```diff
@@ -99,7 +103,12 @@ else if (submittedValue != null) {
 
             ValueHolder valueHolder = (ValueHolder) component;
             if (value == UNDEFINED_VALUE) {
-                value = valueHolder.getValue();
+                if (valueHolder instanceof HtmlOutputFormat) {
+                    value = encodeHtml((HtmlOutputFormat) valueHolder, context);
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: You don't need to pass `(HtmlOutputFormat)valueHolder` here just pass `component` since its already a UIComponent that the signature of encodeHtml needs.

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 4]
```diff
@@ -607,4 +616,40 @@ public static String getDynamicColumnValueAsString(UIComponent component) {
...
+     * added components, component event listeners, then it should mostly be safe.
+     * In other words, use this at most for "simple templates" only, e.g. a HTML based mail template, which usually
+     * already doesn't have a HTML head nor body.
+     * @param component The component to capture HTML output for.
+     * @param context The current FacesContext.
+     * @return The encoded HTML output of the given component.
+     * @throws UncheckedIOException Whenever something fails at I/O level. This would be quite unexpected as it happens locally.
+     * @see <a href="https://github.com/omnifaces/omnifaces">Omnifaces</a>
+     */
+    public static String encodeHtml(UIComponent component, FacesContext context) {
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: I would just call this `encodeComponent` instead of `encodeHtml` and check the Javadoc above to make sure its all still true?  Especially all the OmniFaces stuff.

**Review by melloware — CHANGES_REQUESTED** [review]

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 4 above)
Comment (jasonex7) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: Please check now

**Review by melloware — APPROVED** [review]

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 5]
```diff
@@ -607,4 +616,29 @@ public static String getDynamicColumnValueAsString(UIComponent component) {
...
+     * Encodes the given component locally as HTML.
+     * @param component The component to capture HTML output for.
+     * @param context The current FacesContext.
+     * @return The encoded HTML output of the given component.
+     * @throws UncheckedIOException Whenever something fails at I/O level. This would be quite unexpected as it happens locally.
+     */
+    public static String encodeComponent(UIComponent component, FacesContext context) {
+        ResponseWriter originalWriter = context.getResponseWriter();
+        FastStringWriter output = new FastStringWriter();
+        context.setResponseWriter(originalWriter.cloneWithWriter(output));
```
Comment (jasonex7) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: @melloware this line throws NPE because originalWriter return null. I think that is why Omnifaces uses getRenderKit method to address that situations. Maybe is because the render response is not available yet when this method is executed

**Comment by melloware** [comment]
Ahhh I see I bet its not set yet because DataExporter is a TagHandler not a Renderer.

**Review by melloware — APPROVED** [review]
