### PR TITLE
#13230, #13224 - allowType error message improvements

### LINKED ISSUE #13224: FileUpload: improve allowedType error message
### Description

Hello,

I have a request (and possibly a small bug) reported by customers. Thank you in advance for your consideration.

The issue concerns the error message displayed during regex file validation (allowTypes).

Currently, the system outputs allowed types in a simplified regex format, for example:
`Invalid file type: 'biga.pdf'. Allowed types: 'gif|jpeg|jpg|png'.`

The recommendation is to display it in a more user-friendly format:
`Invalid file type: 'biga.pdf'. Allowed types: '.gif, .jpeg, .jpg, .png'`

Additionally, there appears to be a bug when regex flags (such as "i") are used in allowTypes validation. For instance, with:					
`allowTypes="/(\.|\/)(xls|xlsx)$/i"`

the message appears as:
`Invalid file type: 'biga.pdf'. Allowed types: 'xls|xlsxi'.`

### Describe the solution you would like

If you agree, the function should be as follows
```
function formatAllowTypes(allowTypes) {
    if (allowTypes === undefined) return '';
    const match = allowTypes.match(/\(.*?\)\((.*?)\)\$/);
    if (!match) return '';
    return '.' + match[1].replace(/\|/g, ', .');
}
```

### Additional context

_No response_

### LINKED ISSUE #13230: FileUpload: handle regexp flags incorrectly
### Describe the bug

There is a bug when regex flags (such as "i") are used in allowTypes validation. For instance, with:
allowTypes="/(\.|\/)(xls|xlsx)$/i"

the error message appears as:
Invalid file type: 'biga.pdf'. Allowed types: 'xls|xlsxi'.

### Reproducer

_No response_

### Expected behavior

Ignore flags in allowTypes error message

### PrimeFaces edition

Elite

### PrimeFaces version

14+

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

all

### PR DESCRIPTION
**Pull request by milansie**
- ignored regexp flags
- human readable for extensions regexps "zip|xls" -> ".zip, .xls"
- complex regexp returned as-is

Fix https://github.com/primefaces/primefaces/issues/13230
Fix https://github.com/primefaces/primefaces/issues/13224

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java [hunk 1]
```diff
@@ -413,7 +418,30 @@ public static <T extends HttpServletRequest> String getWebkitRelativePath(T requ
      * @return The allowTypes formatted in a more human-friendly format.
      */
     public static String formatAllowTypes(String allowTypes) {
-        return allowTypes != null ? allowTypes.replace("/(\\.|\\/)(", "").replace(")$/", "") : null;
+        // emtpy or null
+        if (allowTypes == null || allowTypes.isEmpty()) {
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: you can also use LangUtils.isBlank() here

Comment (milansie) [reply primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java]: done, thanks :+1:
