### PR TITLE
Messages: Add closable to widget config, respect in appendMessage function

### LINKED ISSUE #14031: Messages: client-side appendMessage ignores closable attribute
### Describe the bug

`closable` attribute in messages component is ignored when using the client-side `appendMessage` function

### Reproducer

Simply run `PF('myWidget').appendMessage({severity: 'info', summary: 'hello'})` - it unconditionally renders a close icon when it should not

### Expected behavior

close icon is not rendered if `closable=false` (default case)

### PrimeFaces edition

Community

### PrimeFaces version

16.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

All

### JSF version

4.0

### Java version

21

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jungm**
Fixes #14031

### CODE REVIEW

**Comment by melloware** [comment]
Awesome I think we got bit by this too and had a hack workaround.

**Comment by melloware** [comment]
@jungm any chance you can create a PR for the 15.X branch also please?

File: primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java [hunk 1]
```diff
@@ -39,6 +39,9 @@
  * Component wrapper for the PrimeFaces {@code p:messages}.
  */
 public abstract class Messages extends AbstractComponent {
+    public WebElement getClose(String severity) {
```
Comment (tandraschko) [inline primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java]: Should we call it maybe getCloseElement?
maybe you can check it we call it in other cases, bit unsure

Comment (melloware) [reply primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java]: Agreed `getCloseElement` would be more descriptive.

Comment (jungm) [reply primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java]: `getCloseButton` seems to be the most reasonable choice, that name is already used in Dialog and StaticMessage
