### PR TITLE
#7641 corrected chunked FileUpload, added integration tests

### LINKED ISSUE #7641: FileUpload: throws RuntimeExceptions when chunked mode is used
**Describe the defect**
1. Chunked FileUpload throws RuntimeException if `UPLOADER=native`.
```
java.util.NoSuchElementException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1495)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
at java.base/java.util.Collections$3.nextElement(Collections.java:5267)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.lambda$getUploadDirectory$3(NativeFileUploadDecoder.java:79)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.getUploadDirectory(NativeFileUploadDecoder.java:82)
```

2. Chunked FileUpload throws NPE if `UPLOADER=comons` and
`<init-param><param-name>uploadDirectory</param-name>...</init-param>` is not configured in `web.xml`
```
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "org.primefaces.webapp.MultipartRequest.getUploadDirectory()" is null
	at org.primefaces.component.fileupload.CommonsFileUploadDecoder.getUploadDirectory(CommonsFileUploadDecoder.java:80)
	at org.primefaces.component.fileupload.CommonsFileUploadDecoder.getUploadDirectory(CommonsFileUploadDecoder.java:36)
```
**Reproducer**
Former issue cannot be reproduced with primefaces-test project, since jetty adds some attributes to the request which hide the bug.

Reproducer for latter issue.
[PF-7617-chunked.zip](https://github.com/primefaces/primefaces/files/6893161/PF-7617-chunked.zip)

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start server `mvn jetty:run`
2. Go to 'localhost:8080/primefaces-test/'
3. Click 'choose'
4. Select any file bigger than 1MB
5. Click 'upload'
6. See error in server log

**Expected behavior**
RuntimeExceptions should not be thrown. Files should be uploaded without error.

**Example XHTML**
```html
<h:form id="frmTest">
    <p:fileUpload id="fileupload" mode="advanced" maxChunkSize="65536" .../>
</h:form>
```

**Example Bean**
see reproducer

### PR DESCRIPTION
**Pull request by wal-jan**
Fixed RuntimeExceptions in FileUpload component (chunked uploads). Added chunked file upload integration tests.

### CODE REVIEW

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+
+    @Test
+    @Order(1)
+    public void testAdvancedSingleChunkedUpload(Page page) {
+        // Arrange
+        FileUpload fileUpload = page.fileupload;
+        Assertions.assertEquals("", fileUpload.getValue());
+
+        // Act
+        File file = locateClientSideBigFile("primefaces-integration-tests-sources.jar");
```
Comment (melloware) [inline primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java]: This is a nitpick but shouldn't locateCLientSideBiFile be in the `Arrange` section since you are setting up data?

**Review by melloware — CHANGES_REQUESTED** [review]

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java (hunk 1 above)
Comment (wal-jan) [reply primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java]: I think `locateClientSideBigFile` belongs to `Act`. It mimics the user action to select a file in the OS-dependent file dialog. Maybe it should be renamed to `chooseClientSideBigFile`. 
Btw. Please have a closer look into `AbstractFileUploadTest.locateClientSideBigFile`. It effectively picks files from the `primefaces-integration-tests/target` folder. I'm not sure if tha is a good idea. But I did not want to add random big files to the resources folder, just for test purpose.

Comment (melloware) [reply primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java]: No problem!

**Comment by wal-jan** [comment]
Using (big) files from the primefaces-integration-tests/target folder was a bad idea. Since maven `integration-test` phase preceeds `install` phase, not all files used in `FileUpload11`Test are already available. I'll have to do some rework on that.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Looks like we might have an intermittent failure?
```
 FileUpload011Test.testAdvancedSingleChunkedUploadCancelFile:189 » StaleElementReference
```

**Comment by wal-jan** [comment]
I think it's a timing problem. For the time being I'l remove the test `testAdvancedSingleChunkedUploadCancelFile` . PR will come soon.

**Comment by melloware** [comment]
@wal-jan can you check out this Sonar violation?  

https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AXr4HzsgR4qTMU9YjbwC&resolved=false&types=BUG

Its causing our Quality Gate to fail.

**Comment by wal-jan** [comment]
@melloware see #7660
