### PR TITLE
Fix #9137: SelectOneRadio: Labels and index are incorrect in custom layout

### LINKED ISSUE #9137: SelectOneRadio: Labels and index are incorrect in custom layout
### Describe the bug

Since PF 12.0.0-RC3 selectOneRadio with custom layout has issues with the labels if the item index is not straight.

Take for instance the showcase example with custom layout and change some <p:radioButton> order, labels will be broken.

This used to work in 11.0.0.

I'm not really sure about what commit broke this, if you can point me in some direction I can try to put up a PR.

### Reproducer
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
    <h:form id="frmTest">
        <h5>Custom Layout</h5>
        <p:selectOneRadio id="customRadio" layout="custom">
            <f:selectItem itemLabel="Red" itemValue="Red"/>
            <f:selectItem itemLabel="Green" itemValue="Green"/>
            <f:selectItem itemLabel="Blue" itemValue="Blue"/>
        </p:selectOneRadio>
        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet2" for="customRadio" itemIndex="1"/>
            <p:outputLabel for="facet2">
                Green
            </p:outputLabel>
        </span>

        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet1" for="customRadio" itemIndex="0"/>
            <p:outputLabel for="facet1">
                Red
            </p:outputLabel>
        </span>

        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet3" for="customRadio" itemIndex="2"/>
            <p:outputLabel for="facet3">
                Blue
            </p:outputLabel>
        </span>
    </h:form>

</h:body>
</html>


```
### Expected behavior

Labels should point to the correct radio button

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC-3

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3-NEXT-M6

### Java version

18.0.2

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9137

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java [hunk 1]
```diff
@@ -44,19 +45,7 @@ public class SelectOneRadio extends SelectOneRadioBase {
...
-
-    public String getRadioButtonId(FacesContext context) {
-        index++;
-
+    public String getRadioButtonId(FacesContext context, int index) {
         return this.getClientId(context) + UINamingContainer.getSeparatorChar(context) + index;
     }
-
-    @Override
-    public Object saveState(FacesContext context) {
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java:56]: Please explain this
This will likely destroy viewpooling

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio003Test.java [hunk 2]
```diff
@@ -72,6 +72,15 @@ public static class Page extends AbstractPrimePage {
         @FindBy(id = "form:opt4")
         RadioButton opt4;
 
+        @FindBy(id = "form:label1")
```
Comment (tandraschko) [inline primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio003Test.java:75]: Label, not labe

File: primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java (hunk 1 above)
Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java:56]: I removed the index, so all that was left was a call to super

**Review by melloware — APPROVED** [review]
