### PR TITLE
Fix #3019: Add ARIA properties to SelectCheckBoxMenu.

### LINKED ISSUE #3019: selectCheckboxMenu: accessibility
## 1) Environment
- PrimeFaces version: Primefaces 6.1
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: JBoss EAP 7.0
- Affected browsers: Firefox ESR 52.5.0 (64-Bit)
- Screenreader: JAWS 18.0

## 2) Expected behavior
<p:selectCheckboxMenu> component should be read by screenreader similiar like <p:selectOneMenu> component. There it says "`label` dropdown, `selection`, enter text"

## 3) Actual behavior
<p:selectCheckboxMenu> component is read as "Read only input" by screenreaders.

## 4) Steps to reproduce
Read <p:selectCheckboxMenu> component with screenreader

### PR DESCRIPTION
**Pull request by melloware**
Fix #3019: Add ARIA properties to SelectCheckBoxMenu.

### CODE REVIEW

File: src/main/java/org/primefaces/renderkit/InputRenderer.java [hunk 1]
```diff
@@ -112,4 +112,19 @@ protected void renderARIARequired(FacesContext context, UIInput component) throw
         }
     }
 
+    /**
```
Comment (Rapster) [inline src/main/java/org/primefaces/renderkit/InputRenderer.java:115]: If it's really meant for combobox, what about putting it in `SelectRenderer`? Or you think it might be needed by renderer inheriting from InputRenderer?

**Comment by tandraschko** [comment]
@melloware i removed the necessary generics stuff - i had a warning because of a missing documentation of \<T\>

**Comment by melloware** [comment]
Thanks @tandraschko!  And @Rapster from reviewing the ARIA docs and the PF codebase i think the only two components this specific ARIA role applies to is these two.

**Comment by Rapster** [comment]
Yeah so I think this method `renderARIACombobox` should be in SelectRenderer instead. Since it's been merged already, I'll do it

**Comment by tandraschko** [comment]
Actually we should think about moving to CoreRenderer or something as even DataTable e.g. has comboboxes.
I would leave it as it is for now.
