### PR TITLE
Missing Secure Attribute in Encrypted Session (SSL) Cookie 

### LINKED ISSUE #6040: DataExporter  : Missing Secure Attribute in Encrypted Session (SSL) Cookie
**Environment:**
 - PF Version: _7.0.14
 - JSF + version: Mojarra 2.2.13
 - Affected browsers: ALL

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml
2. Click on chrome developer tools
image

3. Secure property is not set for primefaces.download when using with HTTPS

**Expected behavior**
When using with HTTPS the cookie.setSecure(request.isSecure()) is not for primefaces.download

https://stackoverflow.com/questions/62418321/ibm-appscan-missing-secure-attribute-in-encrypted-session-ssl-cookie/62418437#62418437

### PR DESCRIPTION
**Pull request by ravihariharan**
PR to fix set secure attribute for primefaces.download

https://github.com/primefaces/primefaces/issues/6040

### CODE REVIEW

**Comment by tandraschko** [comment]
1) you must also take care of PortletRequest. We already have this check somewhere and reuseable.
2) AFAIR the Cookie is also created/removed on clientside

File: src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java [hunk 1]
```diff
@@ -379,4 +384,24 @@ public int invoke(FacesContext context) {
...
+        externalContext.setResponseHeader("Expires", "0");
+        externalContext.setResponseHeader("Cache-Control", "must-revalidate, post-check=0, pre-check=0");
+        externalContext.setResponseHeader("Pragma", "public");
+        externalContext.setResponseHeader("Content-disposition", contentDisposition);
+    }
+
+    protected void addResponseCookie(ExternalContext externalContext) {
+        final boolean secure = ((HttpServletRequest) externalContext.getRequest()).isSecure();
+        if (secure) {
+            Map<String, Object> map = new HashMap<String, Object>();
```
Comment (melloware) [inline src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java:398]: Initialize the HashMap size to 1 since you are only adding one value `new HashMap<>(1);`  You can just use the diamond operator as we are on Java 8

File: src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java [hunk 2]
```diff
@@ -379,4 +384,24 @@ public int invoke(FacesContext context) {
...
+            map.put("secure", secure);
+            externalContext.addResponseCookie(Constants.DOWNLOAD_COOKIE, "true", map);
+        }
+        else {
+            externalContext.addResponseCookie(Constants.DOWNLOAD_COOKIE, "true", Collections.<String, Object>emptyMap());
+        }
+    }
+
```
Comment (melloware) [inline src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java:409]: I think a better way to write this method is:
```java
        protected void addResponseCookie(ExternalContext externalContext) {
            final boolean secure = ((HttpServletRequest) externalContext.getRequest()).isSecure();
            Map<String, Object> map;
            if (secure) {
                map = new HashMap<>(2);
                map.put("secure", secure);
                map.put("sameSite", "Strict");
            }
            else {
                map = Collections.emptyMap();
            }
            externalContext.addResponseCookie(Constants.DOWNLOAD_COOKIE, "true", map);
        }
```

I also future proofed it by adding `sameSite=Strict` even though JSF and Servlet spec does not support it yet it hopefully will in the future as this is becoming a requirement of most browsers.

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by melloware** [comment]
Hopefully the SameSite attribute will be included in Servlet 5.0: https://github.com/eclipse-ee4j/servlet-api/pull/271

File: src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java (hunk 2 above)
Comment (ravihariharan) [reply src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java:409]: > 1. you must also take care of PortletRequest. We already have this check somewhere and reuseable.

Had to make a minor refactor to support passing an ExternalContext

> 2. AFAIR the Cookie is also created/removed on clientside

File: src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java [hunk 3]
```diff
@@ -379,4 +384,27 @@ public int invoke(FacesContext context) {
...
+    protected void addResponseCookie(ExternalContext externalContext) {
+        final boolean secure = PrimeRequestContext.isSecure(externalContext);
+        Map<String, Object> map = null;
+        if (secure) {
+            map = new HashMap<String, Object>(2);
+            map.put("secure", secure);
+            map.put("sameSite", "Strict");
+            externalContext.addResponseCookie(Constants.DOWNLOAD_COOKIE, "true", map);
```
Comment (melloware) [inline src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java]: You can remove this line you are adding it below

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I just created this ticket now that i realized we are creating client side cookies.
https://github.com/primefaces/primefaces/issues/6045

**Comment by tandraschko** [comment]
i think it's better to just use:
`PrimeRequestContext.getCurrentInstance(context).isSecure()`

and cache the result in `PrimeRequestContext#isSecure`

**Comment by ravihariharan** [comment]
> i think it's better to just use:
> `PrimeRequestContext.getCurrentInstance(context).isSecure()`
> 
> and cache the result in `PrimeRequestContext#isSecure`

Refactored the method to pass FacesContext in place of ExternalContext.

**Review by melloware — APPROVED** [review]
@tandraschko You have this comment in `isSecure` of PrimeRequestContext
```java
// currently called once per request - later we might cache the result per request
// and even the method lookup
```

File: src/main/java/org/primefaces/context/PrimeRequestContext.java [hunk 4]
```diff
@@ -207,22 +208,25 @@ public void release() {
      * @return if secure or not.
      */
     public boolean isSecure() {
-        // currently called once per request - later we might cache the result per request
-        // and even the method lookup
-        Object request = context.getExternalContext().getRequest();
+        // currently called once per request
```
Comment (melloware) [inline src/main/java/org/primefaces/context/PrimeRequestContext.java]: This comment is no longer true now you are caching it after the first result.  @tandraschko I think this is OK because i doubt any site has a mix of HTTP and HTTPS.  At least they should not!

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
