### PR TITLE
IT - take screenshots of failed tests

### LINKED ISSUE #11203: IT: Tree flickering test
This test fails intermittently on the nightly IT.

variants:
```
Tree003Test.tabbing:72->AbstractPrimePageTest.assertDisplayed:88 Element should be displayed!
Tree003Test.tabbing:70->AbstractPrimePageTest.assertDisplayed:88 Element should be displayed!
Tree003Test.tabbing:70 expected: <true> but was: <false>
```

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
image

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/tree/Tree003Test.java [hunk 1]
```diff
@@ -75,6 +75,8 @@ void tabbing(Page page) {
         assertDisplayed(secondChildren.get(2).getWebElement());
 
         assertConfiguration(tree.getWidgetConfiguration());
+
+        throw new RuntimeException("some IT - failure a screenshot should be taken");
```
Comment (christophs78) [inline primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/tree/Tree003Test.java]: We have to remove this line before merging this PR.

**Comment by christophs78** [comment]
We also find them there:
image

File: primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+import java.io.FileWriter;
+import java.io.IOException;
+import java.io.PrintWriter;
+import java.time.LocalDateTime;
+import java.time.format.DateTimeFormatter;
+import java.util.UUID;
+
+public class ScreenshotOnFailureExtension implements TestWatcher {
+
+    public static String path4Screenshots;
```
Comment (tandraschko) [inline primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: can we make it configurable via properties?

Comment (christophs78) [reply primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: should be possible.
just not yet sure what´s the right package overall. when we run IT´s on our local windows/macos/linux-machine we want other settings than when we run them on github actions CI.

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java [hunk 3]
```diff
@@ -70,6 +71,13 @@ public void startup() throws Exception {
         con.disconnect();
 
         Thread.sleep(2000);
+
+        // make screenshots of failed tests
+        if ("true".equals(System.getenv("CI"))) {
```
Comment (christophs78) [inline primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java:76]: That´s the second part i currently use to achive our target.

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java [hunk 4]
```diff
@@ -70,6 +71,13 @@ public void startup() throws Exception {
...
+            // CI is running - see https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
+            ScreenshotOnFailureExtension.path4Screenshots = "/tmp/pf_it/";
```
Comment (christophs78) [inline primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java]: That´s the second part i currently use to achive our target.

File: primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java (hunk 2 above)
Comment (tandraschko) [reply primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: therefore make configurable via the primefaces-selenium.properties

Comment (tandraschko) [reply primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: we can also add support for env vars in the properties config

Comment (christophs78) [reply primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: setting `path4Screenshots` via env-var would make sense.
should work with Github Actions too - https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow.

File: primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java (hunk 4 above)
Comment (tandraschko) [reply primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java]: i think we should add a property here: https://github.com/primefaces/primefaces/tree/master/primefaces-selenium#configuration

and when parsing the properties, we can check for ${...} and resolve as environment var

**Review by melloware — APPROVED** [review]
Looks good and I agree with @tandraschko suggestions!

**Comment by christophs78** [comment]
Feedback incorporated.

File: primefaces-integration-tests-jakarta/src/test/resources-filtered/primefaces-selenium/config.properties [hunk 5]
```diff
@@ -7,3 +7,5 @@ timeout.documentLoad = 30
 
 webdriver.browser = ${webdriver.browser}
 webdriver.headless = ${webdriver.headless}
+
+junit.path4Screenshots = ${JUNIT_PATH4SCREENSHOTS}
```
Comment (tandraschko) [inline primefaces-integration-tests-jakarta/src/test/resources-filtered/primefaces-selenium/config.properties]: What about "screenshotDirectory" instead of "junit...."?

Comment (christophs78) [reply primefaces-integration-tests-jakarta/src/test/resources-filtered/primefaces-selenium/config.properties]: done - renamed at all necessary places

File: primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+import java.time.format.DateTimeFormatter;
+import java.util.UUID;
+
+public class ScreenshotOnFailureExtension implements TestWatcher {
+
+    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
+
+    @Override
+    public void testFailed(ExtensionContext context, Throwable cause) {
+        String path4Screenshots = ConfigProvider.getInstance().getScreenshotDirectory();
```
Comment (tandraschko) [inline primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java]: screenshotDirectory as var name

**Comment by tandraschko** [comment]
everything else looks good - dont forget to remove the exception before merging
