### PR TITLE
Fix #13854: Table render with ARIA role="group"

### LINKED ISSUE #13854: AutoComplete: Accessibility issues with `<p:column>` custom rendering
### Describe the bug

Issue 2&3 from #13849

Image
Image

### Reproducer

1. Run [primefaces-test.zip](https://github.com/user-attachments/files/20444283/primefaces-test.zip)
2. Click into the field "autocomplete tabular" and type "val1"
3. Problems described in "Describe the bug" arise

### Expected behavior

The problem is the `<tbody>` tag. Elements with `role="option"` have to be direct children of an element with `role="listbox"`.

### PrimeFaces edition

Community

### PrimeFaces version

15.0.3

### Theme

_No response_

### JSF implementation

All

### JSF version

4.0

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #13854: Table render with ARIA role="group"

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java [hunk 1]
```diff
@@ -465,10 +465,10 @@ protected void encodePanelContent(FacesContext context, SelectCheckboxMenu compo
                 writer.startElement("table", null);
                 writer.writeAttribute("id", component.getClientId(context) + "_list", null);
                 writer.writeAttribute("class", SelectCheckboxMenu.TABLE_CLASS, null);
-                writer.writeAttribute(HTML.ARIA_ROLE, "listbox", null);
                 writer.writeAttribute(HTML.ARIA_MULITSELECTABLE, "true", null);
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java:469]: @pfumi  i wonder if MultiSelectable should also go on TBODY?

File: primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java [hunk 2]
```diff
@@ -145,9 +145,9 @@ protected void encodeList(FacesContext context, SelectManyMenu component, List<S
         if (customContent) {
             writer.startElement("table", null);
             writer.writeAttribute("class", SelectManyMenu.LIST_CLASS, null);
-            writer.writeAttribute(HTML.ARIA_ROLE, "listbox", null);
             writer.writeAttribute(HTML.ARIA_MULITSELECTABLE, "" + component.isMetaKeySelection(), null);
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java:149]: Same here?

File: primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java [hunk 3]
```diff
@@ -141,9 +141,9 @@ protected void encodeList(FacesContext context, SelectOneListbox component, List
         if (customContent) {
             writer.startElement("table", null);
             writer.writeAttribute("class", SelectOneListbox.LIST_CLASS, null);
-            writer.writeAttribute(HTML.ARIA_ROLE, "listbox", null);
             writer.writeAttribute(HTML.ARIA_MULITSELECTABLE, "false", null);
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java:145]: Same?

File: primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java (hunk 1 above)
Comment (pfumi) [reply primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java:469]: It has to be on the element with listbox see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-multiselectable

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java:469]: OK so for TABLE type this should be removed as its only valid in the normal `<UL>` listbox style.

File: primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java [hunk 4]
```diff
@@ -553,7 +553,6 @@ protected void encodeSuggestionsAsTable(FacesContext context, AutoComplete compo
 
         writer.startElement("table", component);
         writer.writeAttribute("class", AutoComplete.TABLE_CLASS, null);
-        writer.writeAttribute("role", HTML.ARIA_ROLE_LISTBOX, null);
```
Comment (pfumi) [inline primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java:556]: Should not be deleted, the group on tbody is additional

File: primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java (hunk 1 above)
Comment (pfumi) [reply primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java:469]: Same here, keep listbox

File: primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java (hunk 3 above)
Comment (pfumi) [reply primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java:145]: keep listbox

File: primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java [hunk 5]
```diff
@@ -376,9 +376,9 @@ protected void encodePanelContent(FacesContext context, SelectOneMenu component,
                 writer.startElement("table", null);
                 writer.writeAttribute("id", component.getClientId(context) + "_table", null);
                 writer.writeAttribute("class", SelectOneMenu.TABLE_CLASS, null);
-                writer.writeAttribute("role", "listbox", null);
```
Comment (pfumi) [inline primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java:379]: Keep it

File: primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java [hunk 6]
```diff
@@ -145,9 +145,8 @@ protected void encodeList(FacesContext context, SelectManyMenu component, List<S
         if (customContent) {
             writer.startElement("table", null);
             writer.writeAttribute("class", SelectManyMenu.LIST_CLASS, null);
-            writer.writeAttribute(HTML.ARIA_ROLE, "listbox", null);
```
Comment (pfumi) [inline primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java:148]: Keep
