### PR TITLE
Fix #4505: Correct both up and down propagation on backing bean

### LINKED ISSUE #4505: Tree with propagateSelectionDown to false still propagates selection on update
## 1) Environment
- PrimeFaces version: 6.2.0
- Does it work on the newest released PrimeFaces version? Version? Not working in 7.0.RC2
- Does it work on the newest sources in GitHub? Not working
- Application server + version: Wildfly 10.1.0.Final
- Affected browsers: All

## 2) Expected behavior

When setting attribute 'propagateSelectionDown' to 'false' in checkbox selection, I expect there is no selection propagation to child nodes.

## 3) Actual behavior

If I select a node with some childs, child nodes are selected or unselected in backing model. 
This behavior can be seen on updating the tree component.

## 4) Steps to reproduce

First, check a node with some childs like this : 
image

After this, click on ajax button which updates the tree, it will results on this : 
image

## 5) Sample XHTML

```xhtml
<h:form>
	<p:tree value="#{testTreeBean.root}"
		var="data"
		selectionMode="checkbox"
		selection="#{testTreeBean.selectedNodes}"
		propagateSelectionDown="false"
		propagateSelectionUp="false">
				
		<p:treeNode>
			<h:outputText value="#{data}"/>
		</p:treeNode>
	</p:tree>
			
	<p:commandButton value="test" update="@form" />
</h:form>
```

## 6) Sample bean

```java
@Named
@ViewScoped
public class TestTreeBean implements Serializable {	
	private TreeNode root;
	private TreeNode[] selectedNodes;
	
	@PostConstruct
	public void init() {
		root = new CheckboxTreeNode();
		
		// First Level
		TreeNode fruits = new CheckboxTreeNode("Fruits", root);
		TreeNode vegetables = new CheckboxTreeNode("Vegetables", root);
		
		// Fruits Childs
		TreeNode apple = new CheckboxTreeNode("Apple", fruits);
		TreeNode strawberry = new CheckboxTreeNode("Strawberry", fruits);
		
		// Apple Childs
		TreeNode greenApple = new CheckboxTreeNode("Green Apple", apple);
		TreeNode yellowApple = new CheckboxTreeNode("Yellow Apple", apple);
	}

	public TreeNode getRoot() {
		return root;
	}

	public void setRoot(TreeNode root) {
		this.root = root;
	}

	public TreeNode[] getSelectedNodes() {
		return selectedNodes;
	}

	public void setSelectedNodes(TreeNode[] selectedNodes) {
		this.selectedNodes = selectedNodes;
	}
}
```

### PR DESCRIPTION
**Pull request by brivalin**
class UITree: Get values of propagateSelectionDown and propagateSelectionUp. If selectionMode is 'checkbox', call setSelected method of CheckboxTreeNode with propagateSelectionDown and propagateSelectionUp.

class CheckboxTreeNode: Add setSelected method with the two parameters propagateSelectionDown and propagateSelectionUp to process independently up and down.

function initSelection: Add constraint propagateUp to not propagate minus icons to parents if propagateUp is false

### CODE REVIEW

**Comment by melloware** [comment]
So I think from this PR you are saying that CheckBoxTreeNode never supported the propogate up or down that it was missing functionality?

**Comment by brivalin** [comment]
Yes, a part of code was missing but I think it looks like more as a bug because propagation methods was already implemented in CheckboxTreeNode but not called properly.

**Review by melloware — APPROVED** [review]

File: src/main/java/org/primefaces/component/api/UITree.java [hunk 1]
```diff
@@ -64,7 +65,9 @@
         requiredMessage,
         skipChildren,
         showUnselectableCheckbox,
-        nodeVar;
+        nodeVar,
+        propagateSelectionDown,
+        propagateSelectionUp;
```
Comment (melloware) [inline src/main/java/org/primefaces/component/api/UITree.java:70]: If you put these propagate values in UITree shouldn't you remove them from TreeBase.java?

**Review by melloware — CHANGES_REQUESTED** [review]

File: src/main/java/org/primefaces/component/api/UITree.java (hunk 1 above)
Comment (brivalin) [reply src/main/java/org/primefaces/component/api/UITree.java:70]: I have added these changes and I have correct another mistake I made by setting default propagate values to true.

Comment (melloware) [reply src/main/java/org/primefaces/component/api/UITree.java:70]: Thanks for fixing.

**Review by trandbert37 — APPROVED** [review]

**Comment by bvandaele** [comment]
Any chance for this to be merged before next release ?

**Comment by brivalin** [comment]
Is there something else to do on this Pull Request to be merged ?

**Comment by tandraschko** [comment]
Looks good for me. Thanks for the PR.
