### PR TITLE
Fix #9101: TabMenu: disabled items can be focussed

### LINKED ISSUE #9101: TabMenu: disabled items can be focussed
### Describe the bug

disabled items of a `TabMenu` can be focussed.

### Reproducer
```xml
<p:tabMenu>
    <p:menuitem value="Tab 1"/>
    <p:menuitem value="Tab 2" disabled="true"/>
</p:tabMenu>

<p:menu>
    <p:menuitem value="Tab 1"/>
    <p:menuitem value="Tab 2" disabled="true"/>
</p:menu>
```

### Expected behavior

Disabled items cannot be focussed and have the correct ui-state class and tabindex

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

_No response_

### JSF implementation

_No response_

### JSF version

_No response_

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9101

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java [hunk 1]
```diff
@@ -112,7 +109,7 @@ protected void encodeItem(FacesContext context, TabMenu menu, MenuItem item, boo
             writer.writeAttribute("style", containerStyle, null);
         }
 
-        encodeMenuItem(context, menu, item, "-1");
+        encodeMenuItem(context, menu, item);
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java:112]: FYI this will default to tabindex -1, so no functional change here

**Review by melloware — APPROVED** [review]
