### PR TITLE
Fix #13993: ResourceUtils close inputstream

### LINKED ISSUE #13993: GraphicImage: InputStream not closed
### Describe the bug

When using GraphicImage with dynamic content, the InputStream, passed as StreamedContent in the ValueExpression, seems not to be closed after use, resulting in possible resource leakage.

The InputStream is processed by DynamicContentSrcBuilder and ResourceUtils to convert the stream to a Base64 string. 

This was refactored in v12 and the InputStream was properly closed after use.
See https://github.com/primefaces/primefaces/commit/35fb017806566d02c122d10d03961eaaa51d2558#diff-61f38752c2eac65f3b2cfa01d255cc05b89c0d076eea21622ba5936f3b0b88d2R142 on R142.

However, this was recently removed during a sonar cleanup in https://github.com/primefaces/primefaces/pull/11839/files#diff-61f38752c2eac65f3b2cfa01d255cc05b89c0d076eea21622ba5936f3b0b88d2L155.

If I am not missing anything, IMO the input stream should be properly closed by the ResourceUtil method.

### Reproducer

_No response_

### Expected behavior

The InputStream should be properly closed after use.

### PrimeFaces edition

Community

### PrimeFaces version

>= 15

### Theme

_No response_

### JSF implementation

All

### JSF version

4

### Java version

17

### Browser(s)

-

### PR DESCRIPTION
**Pull request by melloware**
Fix #13993: ResourceUtils close inputstream

### CODE REVIEW

**Comment by tandraschko** [comment]
i would propably add a try statement around the IS from the caller, not inside the toByteArray

**Comment by melloware** [comment]
OK i moved it out of there and too the calling locations.

File: primefaces/src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java [hunk 1]
```diff
@@ -90,7 +96,12 @@ else if (InputStream.class.isAssignableFrom(type)) {
                 return buildStreaming(context, component, extractedVE, cache);
             }
             else {
-                return ResourceUtils.toBase64(context, (InputStream) value.get());
+                try (InputStream is = (InputStream) value.get()) {
+                    return ResourceUtils.toBase64(context, is);
+                }
+                catch (IOException e) {
+                    throw new FacesException("Could not open InputStream from InputStream", e);
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java]: from StreamedContent
