### PR TITLE
Fix #12744 - Datatable: supports multiple editableValueHolder in filters

### LINKED ISSUE #12744: Datatable: Filtering dynamic columns from a composite component
Hi all,

I'm trying to filter dynamic columns (<p:columns ...), but filtering doesn't work if it's called from a composite component.

I made a standalone project (from primefaces-test) to try this (link is on bottom of this message).

If i move, for example, <p:inputText from file.xhtml to test.xhtml (just after <sf:file .....), then filtering will work properly.

Am i missing something or this is a bug ?

I tried it with PF 14.0.6.

Thank you !

[primefaces-test (1).zip](https://github.com/user-attachments/files/17437123/primefaces-test.1.zip)

### PR DESCRIPTION
**Pull request by Rapster**
I always felt that getting only the first item was some sort of trick but now it feels more compliant with the JSF API

### CODE REVIEW

**Review by melloware — APPROVED** [review]
LGTM

**Comment by melloware** [comment]
It looks like only on Mojarra we have two IT test failures.

```
OutputLabel001Test.composite2:140->assertLabel:222 expected: <true> but was: <false>
OutputLabel001Test.composite3:151->assertLabel:222 expected: <true> but was: <false>
```

**Comment by Rapster** [comment]
> It looks like only on Mojarra we have two IT test failures.
> 
> ```
> OutputLabel001Test.composite2:140->assertLabel:222 expected: <true> but was: <false>
> OutputLabel001Test.composite3:151->assertLabel:222 expected: <true> but was: <false>
> ```

Yeah I think we had to tweak it for Mojarra (~8 years ago). But no tweak anymore, I managed to get rid of that code

**Comment by melloware** [comment]
@tandraschko after you review let me know if its OK to squash and merge and backport to 14.0.7.

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java [hunk 1]
```diff
@@ -812,4 +818,59 @@ public static Object convertToType(Object value, Class<?> valueType, Logger logg
             return value;
         }
     }
+
+    /**
+     * Invoke callback on the first rendered {@link EditableValueHolder} component
+     */
+    public static void invokeOnDeepestEditableValueHolder(FacesContext context, UIComponent composite, ContextCallback callback) {
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: ~@tandraschko I think it could be renamed, turns out to be the closest as it takes the first rendered component WDYT?~

Comment (tandraschko) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: the closest means the "closest outer" one?
in this case we go into all nested composites and look for the deepest nested EditableValueHolder
therefore IMO its "deepest" and belongs only the composites, therefor it was in CompositeUtils.

Comment (tandraschko) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: just to make sure:

if you do something like
```
p:outputLabel for=@next
myCC:wrappedWrappedInput
```

and wrappedWrappedInput has a cc:editableValueHolder for another CC called wrappedInput, which has a cc:editableValueHolder for a p:inputText

OutputLabelRenderer will then call the invokeOnDeepestEditableValueHolder and will be finally invoked for the real p:inputText

**Comment by Rapster** [comment]
> the closest means the "closest outer" one?

Deepest turns out to be fine, it's not accurate but it's fine. We actually don't look for the deepest, but the "first" rendered EditableValueHolder to be precise

> in this case we go into all nested composites and look for the deepest nested EditableValueHolder
therefore IMO its "deepest" and belongs only the composites, therefor it was in CompositeUtils.

It was indeed introduced because of composites, but again see #12519. CompositeUtils if it was only meant for composite, it's not the case, it's being used from simple component, to UIPanel component and for composite component.

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 1 above)
Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: > the closest means the "closest outer" one?

Deepest turns out to be fine, it's not accurate but it's fine. We actually don't look for the deepest, but the "first" rendered EditableValueHolder to be precise

> in this case we go into all nested composites and look for the deepest nested EditableValueHolder
therefore IMO its "deepest" and belongs only the composites, therefor it was in CompositeUtils.

It was indeed introduced because of composites, but again see #12519. CompositeUtils if it was only meant for composite, it's not the case, it's being used from simple component, to UIPanel component and for composite component.

Comment (tandraschko) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: it was actually only meant only for composites; im also not happy with ComponentUtils but this belongs to the linked issue and this bugfix
i just dont like to mix refactorings and bugfixes

Comment (Rapster) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: I don't mind putting it back in CompositeUtils, and move it once https://github.com/primefaces/primefaces/issues/12519 gets solved

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: That is a good idea @Rapster we can refactor with that other ticket.

File: primefaces/src/main/java/org/primefaces/util/CompositeUtils.java [hunk 2]
```diff
@@ -44,50 +47,55 @@ public static boolean isComposite(UIComponent component) {
...
-                    }
+        @Override
+        public VisitResult visit(VisitContext context, UIComponent target) {
+            if (target instanceof EditableValueHolder) {
+                callback.invokeContextCallback(context.getFacesContext(), target);
+                return VisitResult.COMPLETE;
+            }
+            else if (UIComponent.isCompositeComponent(target)) {
+                visitEditableValueHolderTargets(context, target);
+                return VisitResult.COMPLETE;
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/util/CompositeUtils.java]: Don't merge I think I need to make quick fix here

File: primefaces/src/main/java/org/primefaces/util/ComponentUtils.java (hunk 1 above)
Comment (tandraschko) [reply primefaces/src/main/java/org/primefaces/util/ComponentUtils.java]: sounds good! +1

**Comment by Rapster** [comment]
Ok I think I'm done with this one, I'm quite happy about the result 😄

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
looks good!
