### PR TITLE
Fix #8504: ChartsJS scale and axes fixes

### LINKED ISSUE #8504: Chart.js: Cartesian(Linear)Axes properties are ignored
**Describe the defect**
CartesianAxes.scaleLabel and CartesianLinearTicks.suggested[Min/Max] are not encoded correctly due to renamings in Chart.js 3.x.

According to https://www.chartjs.org/docs/latest/getting-started/v3-migration.html:

> - scales.[x/y]Axes.scaleLabel.labelString was renamed to scales[id].title.text
> - scales.[x/y]Axes.ticks.suggestedMax was renamed to scales[id].suggestedMax
> - scales.[x/y]Axes.ticks.suggestedMin was renamed to scales[id].suggestedMin

**Reproducer**
https://github.com/viiez/primefaces-test/tree/chartjs-migration

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: N/A
 - JSF + version: Mojarra 2.2.x
 - Affected browsers: ALL

**To Reproduce**
1. Run the Reproducer
2. Visit http://localhost:8080/primefaces-test

**Expected behavior**
Cartesian(Linear)Axes properties are encoded correctly.

**Example XHTML**
See https://github.com/viiez/primefaces-test/blob/chartjs-migration/src/main/webapp/test.xhtml

**Example Bean**
See https://github.com/viiez/primefaces-test/blob/chartjs-migration/src/main/java/org/primefaces/test/TestView.java

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by melloware** [comment]
I need to update the migration guide...

File: primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java [hunk 1]
```diff
@@ -164,7 +164,15 @@ protected void encodeScales(FacesContext context, String chartName, Object scale
             if (scales instanceof CartesianScales) {
                 writer.write("\"scales\":{");
                 CartesianScales cScales = (CartesianScales) scales;
-                StringBuilder scaleAttrs = new StringBuilder(20);
+                StringBuilder scaleAttrs = new StringBuilder(128);
+
+                if (cScales.getSuggestedMin() != null) {
+                    writeJsonAttribute(scaleAttrs, "suggestedMax", cScales.getSuggestedMin().toString());
```
Comment (viiez) [inline primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java]:
```suggestion
                    writeJsonAttribute(scaleAttrs, "suggestedMin", cScales.getSuggestedMin().toString());
```

File: primefaces/src/main/java/org/primefaces/model/charts/axes/cartesian/CartesianScaleTitle.java [hunk 2]
```diff
@@ -217,7 +237,8 @@ public String encode() throws IOException {
             fsw.write("{");
 
             ChartUtils.writeDataValue(fsw, "display", this.display, false);
-            ChartUtils.writeDataValue(fsw, "labelString", this.labelString, true);
+            ChartUtils.writeDataValue(fsw, "title", this.title, true);
```
Comment (viiez) [inline primefaces/src/main/java/org/primefaces/model/charts/axes/cartesian/CartesianScaleTitle.java]:
```suggestion
            ChartUtils.writeDataValue(fsw, "text", this.title, true);
```
https://www.chartjs.org/docs/latest/axes/labelling.html

File: primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java [hunk 3]
```diff
@@ -184,7 +192,7 @@ protected void encodeScales(FacesContext context, String chartName, Object scale
             else if (scales instanceof RadialScales) {
                 writer.write("\"scale\":{");
```
Comment (viiez) [inline primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java:186]: I'm not sure if the default scaleId ('r') has to be encoded here as well like for x and y scales
https://www.chartjs.org/docs/latest/axes/#default-scales

File: primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java [hunk 4]
```diff
@@ -164,7 +164,15 @@ protected void encodeScales(FacesContext context, String chartName, Object scale
...
-                StringBuilder scaleAttrs = new StringBuilder(20);
+                StringBuilder scaleAttrs = new StringBuilder(128);
+
+                if (cScales.getSuggestedMin() != null) {
+                    writeJsonAttribute(scaleAttrs, "suggestedMax", cScales.getSuggestedMin().toString());
+                }
+                if (cScales.getSuggestedMax() != null) {
+                    writeJsonAttribute(scaleAttrs, "suggestedMax", cScales.getSuggestedMax().toString());
+                }
+
```
Comment (viiez) [inline primefaces/src/main/java/org/primefaces/component/charts/ChartRenderer.java]: suggestedMin and -Max are per axis options, therefore they have to be encoded for each axis individually, i.e. https://www.chartjs.org/docs/latest/axes/#axis-range-settings

File: primefaces/src/main/java/org/primefaces/model/charts/axes/AxesScale.java [hunk 5]
```diff
@@ -34,6 +34,8 @@
 
     private boolean display = true;
     private Number weight;
+    private Number suggestedMax;
+    private Number suggestedMin;
```
Comment (viiez) [inline primefaces/src/main/java/org/primefaces/model/charts/axes/AxesScale.java]: Please see my 2nd comment in ChartRenderer.java.

Since these options are 'per axis', there is no way to configure them for either x or y axis here.

**Review by viiez — COMMENTED** [review]
I finished the review. Hope my comments are helpful. Feel free to contact me if you have any questions.

**Comment by melloware** [comment]
OK all changes made. Their docs were misleading...

I think I have to make more changes too.  Min and Max were also moved

I have updated your reproducer working with 12.0.0-SNAPSHOT to show its all working here:
[pf-8504.zip](https://github.com/primefaces/primefaces/files/8170870/pf-8504.zip)

**Review by viiez — APPROVED** [review]
Reviewed and tested it. Works perfectly for me, thanks a lot!
