### PR TITLE
Fix #4068: Menu fix CTRL/CMD+click open in new tab

### LINKED ISSUE #4068: MenuItem: link and command at the same time
PrimeFaces version: 6.3-SNAPSHOT

Right now declaring a menuitem such as:

    <p:menuitem value="Item" url="<url>" action="<action>" />

will result in only the url having effect. The menuitem will be just a link.

Instead it could both. If you simply click it, it would behave like an AJAX action, but if you middle-click or right-click and open in a new tab - then it's a link.

Why would you want that? You know how Jira has the "Create issue" button - if you simply click it, it opens the "Create issue" dialog; if you open it in a new tab, it opens the functionally identical "Create issue" page.

### PR DESCRIPTION
**Pull request by melloware**
Fix #4068: Menu fix CTRL/CMD+click open in new tab

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java [hunk 1]
```diff
@@ -112,6 +112,10 @@ protected void encodeOnClick(FacesContext context, UIComponent source, MenuItem
                         : buildNonAjaxRequest(context, ((UIComponent) menuitem), form, ((UIComponent) menuitem).getClientId(context), true);
             }
 
+            if (isLink) {
+                // allow CTRL+CLICK link to open new tab
+                command = "if(event.ctrlKey||event.metaKey){return true};" + command;
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java:117]: I'm wondering if we should do `PF.isMetaKey(event)` (not sure how to name it) instead of `event.ctrlKey||event.metaKey`. If we would have a function, we could do OS checks and makes it easier to refactor. Something like
```js
return isMacOS ? event.metaKey : event.ctrlKey;
```
On macOS Control+Click will show the context menu by default.

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java:117]: Great idea. Let me fix.
