### PR TITLE
#7369 Don't save empty / default states

### LINKED ISSUE #7369: UIData: Huge memory consumption for facets containing UIInput
Primefaces: 8.0++

### Description of the bug

Recently our server (WF 10) crashed with OOM exception. The heapdump revelead over 90mio instances of `HashMap#Node` (consuming 4GB of heap space). Nearly 90% of those instances exists because of the state saving mechanism (50% of those nodes are filled with `SavedState` instances).

It looks like that the `facets` (like `filter`) are stored per row-index instead of only one time.

### Steps to reproduce

Reproducer: https://github.com/fanste/primefaces-test/tree/test-7369

1. Add a breakpoint to PF's UIData, line 481
2. Open the index page
3. Each time `setRowIndex` is called, UIData will save it's state, which also iterates over the facets of each column. At some point you will see, that the componentID will contain the rowIndex which makes no sense for some facets.

Effectively it will generate an entry in the hashmap for each column times each row. Imagine you have a datatable with 50 columns and 50000 rows - that was the problem in our case.

I know that it makes no sense to display that many data at once. Therefor we used a datatable with `pagination=true`. It seems that the user visitied each single page. Otherwise the map should not be flooded with `SavedState` instances of each single row.

### PR DESCRIPTION
**Pull request by jepsar**
It's not really possible to only store the actual filter from the filter facet, but I've noticed that checking for the state helps a lot. Basically you don't need to store the state of inputs that are default / empty. This drastically drops the amount of inputs the state is saved for.

Fixes #7369

### CODE REVIEW

**Review by melloware — APPROVED** [review]
This looks reasonable to me.

**Comment by melloware** [comment]
@fanste any chance you could take this PR for a spin and check your results?

**Comment by melloware** [comment]
@jepsar looks like Integration Tests are failing.

**Comment by melloware** [comment]
Well don't discount that the tests may be incorrect.  If you view they manually they may actually be correct and before they were not.  Just something to double check.

**Comment by Rapster** [comment]
That's not what I had in mind, but it might be one step closer to a better memory management. Since it's about UIData, I wonder what Mojarra/MyFaces peeps think about this, do you think you can create a ticket on both sides so they can share their feedbacks on your proposal?

**Comment by christophs78** [comment]
# MyFaces - Failures: 14, Errors: 6

1. Error:    DataTable007LazyTest.testEditRow:111 expected: <abc> but was: <Language 3>
2. Error:    DataTable007Test.testEditRow:108 expected: <abc> but was: <JavaScript>
3. Error:    DataTable007Test.testFilterAndEditRow_1442:153 expected: <abc> but was: <JavaScript>
4. Error:    DataTable011Test.testSortAndDeleteV2:74->lambda$testSortAndDeleteV2$1:74 expected: not equal but was: <1>
5. Error:    DataTable021Test.testFilterAndRemoveRowV2:128 expected: <0> but was: <1>
6. Error:    DataTable028Test.testFilterSortEdit:53->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
7. Error:    DataTable028Test.testFilterSortEdit:53->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
8. Error:    DataTable028Test.testFilterSortEditV2:102->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
9. Error:    DataTable028Test.testFilterSortEditV2:102->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
10. Error:    DataTable028Test.testSortEdit:143->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
11. Error:    DataTable028Test.testSortEdit:143->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
12. Error:    DataTable028Test.testSortEditV2:177->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
13. Error:    DataTable028Test.testSortEditV2:177->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
14. Error:    DataView002Test.testLazyRowDeleteFromLastPage:114 expected: <9> but was: <8>
15. Error:    DataTable009Test.testFilterIssue1390:68 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:msgs"}
16. Error:    DataTable009Test.testFilterIssue7026:157 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable"}
17. Error:    DataTable024Test.testRowGroup:53 NullPointer
18. Error:    DataTable032Test.testDisabledRowSelection:60 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:0\:toggle"}
29. Error:    DataTable034Test.test:44 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:0\:name"}
20. Error:    DataTable035Test.test:42 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:1\:name"}

# Mojarra - Failures: 13, Errors: 6

1. Error:    DataTable007LazyTest.testEditRow:111 expected: <abc> but was: <Language 3>
2. Error:    DataTable007Test.testEditRow:108 expected: <abc> but was: <JavaScript>
3. Error:    DataTable007Test.testFilterAndEditRow_1442:153 expected: <abc> but was: <JavaScript>
4. Error:    DataTable011Test.testSortAndDeleteV2:74->lambda$testSortAndDeleteV2$1:74 expected: not equal but was: <1>
5. Error:    DataTable028Test.testFilterSortEdit:53->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
6. Error:    DataTable028Test.testFilterSortEdit:53->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
7. Error:    DataTable028Test.testFilterSortEditV2:102->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
8. Error:    DataTable028Test.testFilterSortEditV2:102->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
9. Error:    DataTable028Test.testSortEdit:143->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
10. Error:    DataTable028Test.testSortEdit:143->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
11. Error:    DataTable028Test.testSortEditV2:177->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
12. Error:    DataTable028Test.testSortEditV2:177->assertInitalState:205 expected: <Result:509,EUR,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E> but was: <Result:509,null,BB,BB2,A512,EUR,BB,BB2,B515,EUR,BB,BB2,C516,USA,AA,AA,D517,USA,AA,AA,E>
13. Error:    DataView002Test.testLazyRowDeleteFromLastPage:114 expected: <9> but was: <8>
14. Error:    DataTable009Test.testFilterIssue1390:68 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:msgs"}
15. Error:    DataTable009Test.testFilterIssue7026:157 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable"}
16. Error:    DataTable024Test.testRowGroup:53 NullPointer Cannot invoke 
17. Error:    DataTable032Test.testDisabledRowSelection:60 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:0\:toggle"}
18. Error:    DataTable034Test.test:44 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:0\:name"}
19. Error:    DataTable035Test.test:42 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":"#form\:datatable\:1\:name"}

**Comment by christophs78** [comment]
This PR definitive breaks row- and cell-editing. Probably even more when looking into failing tests.
The row- and cell-editing-regression is also reproduceable with http://localhost:8080/showcase/ui/data/datatable/edit.xhtm.
(I did not looked into the other failing tests yet.)

**Comment by fanste** [comment]
I will take A Look, of we still have that construct in the application.

Regarding the failing tests: the restore method also skips the reset of the input client id. This could be the cause. As far aß I know the client ID is chached once created and nulled when the ID is set again. This is required to get the correct Iteration state, isn't IT?

File: primefaces/src/main/java/org/primefaces/component/api/UIData.java [hunk 1]
```diff
@@ -622,7 +625,18 @@ else if (component instanceof UIForm) {
                 restoreDescendantState(facet, context);
             }
         }
+    }
 
+    protected SavedState getSavedState(UIComponent component, FacesContext context) {
+        Map<String, SavedState> saved = (Map<String, SavedState>) getStateHelper().get(PropertyKeys.saved);
+        if (saved == null) {
+            return new SavedState();
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/api/UIData.java]: should we return a static empty SavedState?

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/api/UIData.java]: If the IT are passing I can change it to a static one.

File: primefaces/src/main/java/org/primefaces/component/api/UIData.java [hunk 2]
```diff
@@ -557,7 +536,41 @@ else if (component instanceof UIForm) {
                 saveDescendantState(facet, context);
             }
         }
+    }
+
+    protected void saveInputState(EditableValueHolder input, FacesContext context) {
+        String componentClientId = ((UIComponent) input).getClientId(context);
+        if (isDefaultAndEmpty(input)) {
+            getStateHelper().remove(PropertyKeys.saved, componentClientId);
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/api/UIData.java]: this code looks weird?
It actually returns a Map with Map<String, SavedState> for ALL inputs, should we really remove the whole map for the single componentClientId?

**Comment by jepsar** [comment]
> That's not what I had in mind, but it might be one step closer to a better memory management. Since it's about UIData, I wonder what Mojarra/MyFaces peeps think about this, do you think you can create a ticket on both sides so they can share their feedbacks on your proposal?

I don't think this issue, nor the fix are related to JSF implementations. Although I think it's a bit weird PF had to write this patch, but I'm no expert in this matter. I just found that there were a lot empty states stored for (for example) column filters which are set through the "filter" facet. That is what I tried to reduce here.

**Comment by tandraschko** [comment]
we could maybe inherit SavedState to a ImmutableSaveState, just to make sure we dont change our static empty instance.

i like your fix as it reduces useless object instances in general
still, it has room to improvements as we shouldnt not visit "column scoped" facets inside each row

but even i dont know why we have PropertyKeys.saved

**Comment by Rapster** [comment]
UIData is a copy of Mojarra to patch few issues encountered in the past (no idea which ones, it doesn't say...) so it is somehow related to JSF impl (at least Mojarra), not only it patches a few things, but also it supports `org.primefaces.api.UIColumn` (while JSF impl supports `javax.faces.component.UIColumn` . That's why also it makes almost impossible to properly test `p:dataTable` with MyFaces impl (you can run it, but under the hood it remains Mojarra impl 😞 )

> I just found that there were a lot empty states stored for (for example) column filters which are set through the "filter" facet. That is what I tried to reduce here.

That's what I tried to explain in the past, column facets should probably not be saved. Just that should avoid the creation of  `cols * rows` states if you have at least one filter contained in each column.

My feeling is that your PR workaround the real issue, but even with a proper fix, I would still consider your PR since it keeps in memory what's really necessary

**Comment by jepsar** [comment]
> we could maybe inherit SavedState to a ImmutableSaveState, just to make sure we dont change our static empty instance.

Yeah, was thinking the same thing.

> ... we shouldnt not visit "column scoped" facets inside each row

Thought about that as well, but can we tell we are in a row instead of the header or footer?

File: primefaces/src/main/java/org/primefaces/component/api/UIData.java [hunk 3]
```diff
@@ -622,7 +626,16 @@ else if (component instanceof UIForm) {
...
         }
+    }
 
+    protected SavedState getSavedState(UIComponent component, FacesContext context) {
+        Map<String, SavedState> saved = (Map<String, SavedState>) getStateHelper().get(PropertyKeys.saved);
+        if (saved == null) {
+            return SavedState.NULL_STATE;
+        }
+        String componentClientId = component.getClientId(context);
+        SavedState state = saved.get(componentClientId);
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/component/api/UIData.java]: You can use saved.getOrDefault here

File: primefaces/src/main/java/org/primefaces/component/api/UIData.java [hunk 4]
```diff
@@ -557,7 +536,43 @@ else if (component instanceof UIForm) {
...
+            state = new SavedState();
+        }
+
+        if (state == null) {
+            state = saved.get(componentClientId);
+
+            if (state == null) {
+                state = new SavedState();
+            }
+        }
```
Comment (Rapster) [inline primefaces/src/main/java/org/primefaces/component/api/UIData.java]: Can be simplified:

```java
if (saved != null) {
    state = saved.computeIfAbsent(componentClientId, SavedState::new);
}
else {
   state = new SavedState();
}
```

File: primefaces/src/main/java/org/primefaces/component/api/UIData.java [hunk 5]
```diff
@@ -548,19 +548,9 @@ protected void saveInputState(EditableValueHolder input, FacesContext context) {
...
-
-        if (state == null) {
-            state = saved.get(componentClientId);
-
-            if (state == null) {
-                state = new SavedState();
-            }
-        }
+        SavedState state = saved != null
+                ? saved.computeIfAbsent(componentClientId, key -> new SavedState())
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/api/UIData.java:552]: is the "put" by design? your old code did not saved.put(..)

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/api/UIData.java:552]: It is put below (line 559 currently). And here we already know it is not default / empty, so it should be put.

**Comment by tandraschko** [comment]
feel free to merge @jepsar 
code looks fine + all tests are running

**Comment by tandraschko** [comment]
i dont think we will hit the same problem in plain MyFaces/Mojarra but i we should optimize it: https://issues.apache.org/jira/browse/MYFACES-4600
