### PR TITLE
Fix #9282: SelectOneRadio pagedirection layout

### LINKED ISSUE #9282: Core: Deprecate `<table>` based layouts
### Describe the bug

When using the [SelectOneRadio](https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml) with `layout` configuration set to `lineDirection`(wich is the default value!), then invalid HTML is rendered.

> The value of the for attribute of the label element must be the ID of a non-hidden form control

This is caused by the fact that with the rendering option `lineDirection` a table is rendered and the labels of the options point to the id of the table. But tables are not allowed to have a label.

radioInput_tablerender

### Reproducer

https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml (Showcase Primefaces 12)

### Expected behavior

* Valid HTML is rendered, with the label pointing to the input field (hich could be problematic as it's hidden)
* No usage of layout tables, therefore change the default value to `responsive` or chaning the implementation of the `lineDirection` (and others)

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0 at work (Showcase is using 12.0.0)

### Theme

Saga

### JSF implementation

All

### JSF version

2.2

### Java version

8

### Browser(s)

All

### PR DESCRIPTION
**Pull request by melloware**
Added showcase example too:
image

Fix #9282

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java [hunk 1]
```diff
@@ -119,9 +119,16 @@ protected void encodeResponsiveLayout(FacesContext context, SelectOneRadio radio
 
         Converter converter = radio.getConverter();
         String name = radio.getClientId(context);
-        int columns = radio.getColumns();
         String currentValue = ComponentUtils.getValueToRender(context, radio);
 
+        int columns = radio.getColumns();
+        if ("lineDirection".equals(layout)) {
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: What happens is the label is long? It will probably start wrapping in the 1/12th column, right?

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: If gives it column `md-1` so column 13 should be wrapped on the next line.

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: I'm not talking about 12+ items, but the length of a single label. So instead of "Option1" use "A label which you might expect in everyday use and might be longer".

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: ahh good point let me make a fix.

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: OK updated. The columns actually default to 12 unless you override it so it will be 12 but if you do `columns=2` with long labels it would make them both obviousle `md-6` making them much bigger.

Comment (jepsar) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: I think we should just drop using columns in that case.

Comment (melloware) [reply primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java]: I don't think we can else it won't be responsive anymore?
