### PR TITLE
Fix #7029: LinkButton allow content

### LINKED ISSUE #7029: LinkButton: broken with custom markup
works
```
<p:linkButton href="#{request.contextPath}#{pdf.resourcePath}" target="_blank" value="#{msgs[pdf.msgKey]}">
</p:linkButton>
```

works not:
```
<p:linkButton href="#{request.contextPath}#{pdf.resourcePath}" target="_blank">
    <span>#{msgs[pdf.msgKey]}</span>
</p:linkButton>
```

### PR DESCRIPTION
**Pull request by melloware**
Refactored to use `StyleClassBuilder` and allow child content.

image

```xml
            <p:linkButton outcome="productDetail" icon="pi pi-star"  style="margin-right:20px;">
                <f:param name="productId" value="50"/>
                <span>Content</span>
            </p:linkButton>
```

### CODE REVIEW

File: src/main/java/org/primefaces/component/linkbutton/LinkButton.java [hunk 1]
```diff
@@ -45,30 +49,36 @@
...
-        }
-        else if (value == null && !LangUtils.isValueBlank(icon)) {
-            styleClass = HTML.BUTTON_ICON_ONLY_BUTTON_CLASS;
-        }
+        String styleClass = PrimeRequestContext.getCurrentInstance(context).getStyleClassBuilder()
+                    .add("ui-linkbutton")
+                    .add(getStyleClass())
+                    .add(hasValue && !hasIcon, HTML.BUTTON_TEXT_ONLY_BUTTON_CLASS)
+                    .add(!hasValue && hasIcon, HTML.BUTTON_ICON_ONLY_BUTTON_CLASS)
+                    .add(isTextAndIcon && getIconPos().equals("left"), HTML.BUTTON_TEXT_ICON_LEFT_BUTTON_CLASS, HTML.BUTTON_TEXT_ICON_RIGHT_BUTTON_CLASS)
```
Comment (Rapster) [inline src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: "left".equals...

File: src/main/java/org/primefaces/component/linkbutton/LinkButton.java [hunk 2]
```diff
@@ -45,30 +49,36 @@
...
-        String userStyleClass = getStyleClass();
-        if (userStyleClass != null) {
-            styleClass = styleClass + " " + userStyleClass;
+    public boolean hasDisplayedChildren() {
+        if (getChildCount() == 0) {
+            return false;
         }
-
-        return "ui-linkbutton " + styleClass;
+        else {
```
Comment (Rapster) [inline src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: remove else?

File: src/main/java/org/primefaces/component/linkbutton/LinkButton.java [hunk 3]
```diff
@@ -45,30 +49,36 @@
...
+            for (int i = 0; i < getChildCount(); i++) {
+                UIComponent child = getChildren().get(i);
+                if (child instanceof UIParameter || !child.isRendered()) {
```
Comment (Rapster) [inline src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: what about returning true if child not UIParameter? I just feel is more readable and straightforward that way

**Comment by melloware** [comment]
Thanks @Rapster great feedback.

File: src/main/java/org/primefaces/component/linkbutton/LinkButton.java [hunk 4]
```diff
@@ -45,30 +49,34 @@
         return ComponentUtils.getUIParams(this);
     }
 
-    public String resolveStyleClass() {
-        String icon = getIcon();
-        Object value = getValue();
-        String styleClass = "";
+    public String resolveStyleClass(FacesContext context) {
```
Comment (Rapster) [inline src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: I know we have other resolveStyleClass in component, but I think it makes more sense to have that in renderers

Comment (melloware) [reply src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: I was wondering why this was here.  I agree I should move it to the renderer.

**Comment by tandraschko** [comment]
looks good to me
i just copied it from CommandButton in the past, i'm ok with moving to renderer

File: src/main/java/org/primefaces/component/linkbutton/LinkButton.java (hunk 4 above)
Comment (melloware) [reply src/main/java/org/primefaces/component/linkbutton/LinkButton.java]: moved into renderer
