### PR TITLE
fixes #3282 slider input validation

### LINKED ISSUE #3282: slider: lack of user input validation
## 1) Environment
- PrimeFaces version: primefaces-6.2.RC2-snapshot
- Application server + version: any
- Affected browsers: any

## 2) Expected behavior
`minValue` and `maxValue` should be enforced at server side and value has to be rejected if outside the range.

## 3) Actual behavior
User input validation is neither done on server nor on client side.

## 4) Steps to reproduce
Just go to your showcase https://www.primefaces.org/showcase/ui/input/slider.xhtml and enter some values that are outside the range.

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/input/slider.xhtml

## 6) Sample bean
https://www.primefaces.org/showcase/ui/input/slider.xhtml

### PR DESCRIPTION
**Pull request by cnsgithub**
- Range checks are performed in process validations phase, therefore the slider now extends `UIInput`
- if values are out of range a validation error will be thrown and the submitted values will be rejected
- tested with your showcase xhtml, as well range as simple slider seem to work correctly

### CODE REVIEW

File: src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java [hunk 1]
```diff
@@ -57,3 +60,60 @@ public void queueEvent(FacesEvent event) {
...
         }
     }
+
+    public final static String VALUE_OUT_OF_RANGE = "primefaces.slider.OUT_OF_RANGE";
+
+    @Override
+    public void validate(FacesContext context) {
+        super.validate(context);
+        
+        if(isValid()) {
```
Comment (melloware) [inline src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java:70]: I prefer to use `if (!isValid()) { return; }` to short circuit the whole method rather than having all of the code inside a giant IF statement.  Just my preference.

**Review by melloware — APPROVED** [review]
Nice work.

File: src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java [hunk 2]
```diff
@@ -57,3 +60,60 @@ public void queueEvent(FacesEvent event) {
...
+            String[] inputIds = this.getFor().split(",");
+            if (this.isRange()) {
+                UIInput inputFrom = (UIInput) SearchExpressionFacade.resolveComponent(context, this, inputIds[0].trim());
+                UIInput inputTo = (UIInput) SearchExpressionFacade.resolveComponent(context, this, inputIds[1].trim());
+                String valueFromStr = getSubmittedValue(inputFrom).toString();
+                String valueToStr = getSubmittedValue(inputTo).toString();
+                double valueFrom = Double.valueOf(valueFromStr);
+                double valueTo = Double.valueOf(valueToStr);
+                if (valueFrom < this.getMinValue() || valueFrom > this.getMaxValue()) {
+                    this.setValid(false);
```
Comment (jxmai) [inline src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java]: ~~Why not use `non-shortcircuit or` to force evaluating both statements ?~~

```
if(valueFrom < this.getMinValue() | valueFrom > this.getMaxValue())
  setInvaliad
```

Comment (jxmai) [reply src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java]: Nevermind, my bad :sweat_smile: . Your implementation is Good. You are evaluating the same field.

Comment (jxmai) [reply src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java]: Just a nitpick

if valueFrom and valueTo are both out of range, there is no need to excute `valueTo < valueFrom` since both fields are already invalid at that point. 

Those three if statements will execute in order regardless of the condition is valid or invalid that can waste some cycles.

Comment (cnsgithub) [reply src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java]: Let's say `valueFrom=2, valueTo=1, minValue=0, maxValue=2`. 

Then the first two conditions aren't met, however the third condition is since `valueTo < valueFrom`. So the third condition is absolutely required.

Your suggestion would be to additionally check these prerequisites in the third condition? Then you would save the setter but introduce getter cycles. Does that make sense?

Comment (jxmai) [reply src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java]: > Your suggestion would be to additionally check these prerequisites in the third condition? Then you would save the setter but introduce getter cycles. Does that make sense?

No, what I meant was to move the third condition to the first.
```
if (valueTo < valueFrom) {  
    // both are invalid then no need to check individual fields
} else {
 //  checkIndividual fields
  if (valueFrom) {

  }

  if (valueTo) {

  }
}
```

instead of 

```
if (valueFrom) {

}

if (valueTo) {

}

if (valueFrom > valueTo) {

}
```
---

Let's say `valueFrom = 4, valueTo = 0, minValue = 1, maxValue = 3`

 `if (valueFrom < this.getMinValue() || valueFrom > this.getMaxValue())` will be true

`if (valueTo > this.getMaxValue() || valueTo < this.getMinValue())` will be true

`if (valueTo < valueFrom)` will also be true (wasted)

---

Let's say valueFrom=2, valueTo=1, minValue=0, maxValue=2.

 `if (valueFrom < this.getMinValue() || valueFrom > this.getMaxValue())` will be false

`if (valueTo > this.getMaxValue() || valueTo < this.getMinValue())` will be false

`if (valueTo < valueFrom)` will also be true

the third case is necessary but it will also be faster if we check valueTo < valueFrom first.

**Comment by cnsgithub** [comment]
@jxmai Good morning. Now I got it. Just saved some cycles.

**Comment by tandraschko** [comment]
Looks good, thanks! Just swichtecd the isValid() if as melloware suggested, its easier to read if the if-block is to big.
