### PR TITLE
Fix #8687: DatePicker range mask

### LINKED ISSUE #8687: DatePicker: mask="true" does not work with selection mode 'range'
```xhtml
      <p:datePicker pattern="yyyy-MM-dd"
                    selectionMode="range"
                    rangeSeparator="-"
                    mask="true"/>
```

Currently shows: `____-__-__`

Expected: `____-__-__ - ____-__-__`

### PR DESCRIPTION
**Pull request by jepsar**
Fix #8687

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js [hunk 1]
```diff
@@ -231,7 +231,7 @@ PrimeFaces.widget.DatePicker = PrimeFaces.widget.BaseWidget.extend({
                     return pastedValue;
                 }
             };
-            var pattern = new RegExp("m|d|y|h|s", 'i');
+            var pattern = /[mdyhs]/i;
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js:234]: Not related to the actual issue, but fixes SonarLint smells.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
nice work
