### PR TITLE
Fix #9796: BlockUI center content

### LINKED ISSUE #9796: BlockUI not centered
a blockui associated to a commandbutton is not centered if the command button has an action listener. If we remove the action listener it works as expected. Issue noticed after upgrading from PF8 to PF12.0.0.

test.xhtml

```
    <!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>TEST</title>

</h:head>

<h:body styleClass="login-body logout">

    <h:form>
        <p:commandButton value="test" actionListener="#{myTestBean.waitOneSecond}" onstart="PF('panelBlocker').show();" oncomplete="PF('panelBlocker').hide();"/>
    </h:form>

    <h:panelGroup style="background-color: red; height: 400px; width: 400px;" id="panel" layout="block">

    </h:panelGroup>

    <p:blockUI block="panel" widgetVar="panelBlocker">
        <i class="pi pi-spin pi-spinner" style="font-size: 2rem"></i>
    </p:blockUI>
</h:body>

</html>

```

MyTestBean.java

```


import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class MyTestBean  implements java.io.Serializable{

    public String waitOneSecond(){
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        return "success";
    }
}

```

### PR DESCRIPTION
**Pull request by melloware**
Fix #9796: BlockUI center content

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js [hunk 1]
```diff
@@ -92,9 +92,9 @@ PrimeFaces.widget.BlockUI = PrimeFaces.widget.BaseWidget.extend({
         });
 
         // subscribe to all DOM update events so we can resize even if another DOM element changed
-        $(document).on('pfAjaxUpdated', function(e, xhr, settings) {
+        $(document).on('pfAjaxSend pfAjaxUpdated', function(e, xhr, settings) {
             if (!$this.cfg.blocked) {
-                $this.alignOverlay();
+                setTimeout(function() { $this.alignOverlay() }, 0);
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js:97]: 🤯
