### PR TITLE
Fix #8843: Datepicker JS error in month picker

### LINKED ISSUE #8843: DatePicker: Month-Picker with manual input throws JS error
### Describe the bug

A manually entered year-month in the Month-Picker will produce JS error while typing:

image

### Reproducer

Showcase: https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml?jfwid=3145d

Open the web console.

Start typing in the input for `Month Picker (java.time.YearMonth)`. The expected format is `MM/YYYY`.
As long as the month is not "fully" entered, each key press will produce a JS error.

### Expected behavior

No JS error should be thrown

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.1.19

### Browser(s)

Chrome Edge 101.0.1210.53

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js [hunk 1]
```diff
@@ -512,7 +512,7 @@
                         return this.isDateEquals(this.value[0], dateMeta);
                 }
                 else {
-                    return (this.value.getMonth() === month && this.value.getFullYear() === this.viewDate.getFullYear());
+                    return this.isDate(this.value) && (this.value.getMonth() === month && this.value.getFullYear() === this.viewDate.getFullYear());
```
Comment (jepsar) [inline primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js]:
```suggestion
                    return this.isDate(this.value) && this.value.getMonth() === month && this.value.getFullYear() === this.viewDate.getFullYear();
```

**Comment by melloware** [comment]
Fixed parenthesis
