### PR TITLE
Sonar JS fixes for Core

### LINKED ISSUE #11863: SONAR: Fix JS issues
### Description

see https://sonarcloud.io/project/issues?languages=js&resolved=false&id=org.primefaces%3Aprimefaces

### Describe the solution you would like

less issues

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix https://github.com/primefaces/primefaces/issues/11863

Addresses the Sonar issues on in the `/core` package only

### CODE REVIEW

**Comment by tandraschko** [comment]
Need to think about it, im not that happy with it right now

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js [hunk 1]
```diff
@@ -1201,7 +1193,7 @@
 
             // try and strip specific language from nl_BE to just nl
             if (!locale) {
-                var localeKey = cfgLocale ? cfgLocale : PrimeFaces.settings.locale;
+                var localeKey = cfgLocale || PrimeFaces.settings.locale;
```
Comment (Rapster) [inline primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: this localKey var could be renamed since it's a boolean

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js [hunk 2]
```diff
@@ -451,23 +449,25 @@ if (!PrimeFaces.utils) {
...
+
+                $scrollParent.off(scrollNamespace, scrollHandler).on(scrollNamespace, scrollHandler);
+            });
 
             return {
                 unbind: function() {
-                    for (var i = 0; i < scrollableParents.length; i++) {
-                        $(scrollableParents[i]).off(scrollNamespace);
-                    }
+                    scrollableParents.forEach(scrollParent => {
```
Comment (Rapster) [inline primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js]: why not use for of ?

Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js]: Switched to for-of

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js (hunk 1 above)
Comment (melloware) [reply primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: This actually is the value "en_US" either using the local config or global locale value before it gets split to "en".

Comment (Rapster) [reply primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: ohh

**Comment by tandraschko** [comment]
what about external JS? are the filtered out somehow?
https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=org.primefaces%3Aprimefaces&open=AY8u9KHvLK6QkKtQMXzo

i would like to not scan it

**Comment by Rapster** [comment]
I just added the exclusion (there might be still a few left)

**Review by Rapster — APPROVED** [review]
