### PR TITLE
Fix #8801/#8317: Use client side fallback if server form not found

### LINKED ISSUE #8317: MenuItem: doesn't work when used inside composite component with a form
When using a composite component which has a h:form inside and using <cc:renderFacet> to put content inside, if you use <p:splitButton> with <p:menuItem> it results in an exception:
```
Caused by: javax.faces.FacesException: MenuItem must be inside a form element
    at org.primefaces.renderkit.MenuItemAwareRenderer.encodeOnClick (MenuItemAwareRenderer.java:81)
    at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeMenuItem (SplitButtonRenderer.java:339)
    at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeElements (SplitButtonRenderer.java:292)
    at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeMenu (SplitButtonRenderer.java:263)
    at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeMarkup (SplitButtonRenderer.java:103)
    at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeEnd (SplitButtonRenderer.java:77)
    at javax.faces.component.UIComponentBase.encodeEnd (UIComponentBase.java:675)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:555)
    at org.apache.myfaces.renderkit.html.HtmlCompositeFacetRenderer.encodeChildren (HtmlCompositeFacetRenderer.java:80)
    at javax.faces.component.UIComponentBase.encodeChildren (UIComponentBase.java:644)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:542)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:551)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:551)
    at org.apache.myfaces.renderkit.html.HtmlCompositeComponentRenderer.encodeChildren (HtmlCompositeComponentRenderer.java:66)
    at javax.faces.component.UIComponentBase.encodeChildren (UIComponentBase.java:644)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:542)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:551)
    at javax.faces.component.UIComponentBase.encodeAll (UIComponentBase.java:551)
    at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView (FaceletViewDeclarationLanguage.java:1891)
    at org.apache.myfaces.application.ViewHandlerImpl.renderView (ViewHandlerImpl.java:313)
    at javax.faces.application.ViewHandlerWrapper.renderView (ViewHandlerWrapper.java:58)
    at javax.faces.application.ViewHandlerWrapper.renderView (ViewHandlerWrapper.java:58)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute (RenderResponseExecutor.java:116)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render (LifecycleImpl.java:267)
    at javax.faces.webapp.FacesServlet.service (FacesServlet.java:200)
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1459)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1631)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:548)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:618)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:235)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1624)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1434)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:188)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1594)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1349)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.Dispatcher.forward (Dispatcher.java:229)
    at org.eclipse.jetty.server.Dispatcher.forward (Dispatcher.java:81)
    at org.eclipse.jetty.server.ResourceService.sendWelcome (ResourceService.java:439)
    at org.eclipse.jetty.server.ResourceService.doGet (ResourceService.java:257)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet (DefaultServlet.java:447)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1450)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1631)
    at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter (WebSocketUpgradeFilter.java:228)
    at org.eclipse.jetty.servlet.FilterHolder.doFilter (FilterHolder.java:193)
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter (ServletHandler.java:1601)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:548)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:600)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:235)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1624)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1434)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:188)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1594)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1349)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:191)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:146)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.Server.handle (Server.java:516)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1 (HttpChannel.java:400)
    at org.eclipse.jetty.server.HttpChannel.dispatch (HttpChannel.java:645)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:392)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:277)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:311)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:105)
    at org.eclipse.jetty.io.ChannelEndPoint$1.run (ChannelEndPoint.java:104)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:883)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:1034)
    at java.lang.Thread.run (Thread.java:834)


```
 Primefaces fails to detect that p:menuItem is  inside a form.

**Environment:**
 - PF Version: _11_
 - JSF + version: I tested on myfaces22 but I believe it happens in all implementations
 - Affected browsers: ALL_

**To Reproduce**
See attached primefaces-test project 

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/7920844/primefaces-test.zip)

**Expected behavior**
Primefaces should be able to detect that the p:menuItem is inside a h:form already even though the h:form is inside the composite component

**Example XHTML**
**test.xhtml**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:my="http://xmlns.jcp.org/jsf/composite/my"
      >

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <br/><br/>

        <my:component >
            <f:facet name="content">
                <p:splitButton value="Test">
                    <p:menuitem value="Test2" />
                </p:splitButton>
            </f:facet>

        </my:component>
    </h:body>
</html>
```
**component.xhtml**
```html
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <cc:interface>


    </cc:interface>

   
    <cc:implementation>
        <h:form>
            <cc:renderFacet name="content" />
        </h:form>

    </cc:implementation>
</html>

### LINKED ISSUE #8801: CommandButton: when ajax=false, it doesn't work when used inside composite component with a form
### Describe the bug

When using a composite component which has a h:form inside and using cc:renderFacet to put a p:commandButton with ajax=false inside, that page won't render with the following error:
```
FacesException: CommandButton : "j_id_7:j_id_8" must be inside a form element
    at org.primefaces.component.commandbutton.CommandButtonRenderer.buildRequest (CommandButtonRenderer.java:153)
```
I think this issue might be related to #8317 

### Reproducer

[primefaces_test.7z](https://github.com/primefaces/primefaces/files/8735132/primefaces_test.zip)

### Expected behavior

Primefaces should be able to detect that the p:commandButton is inside a h:form already even though the h:form is inside the composite component

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

ALL?

### JSF implementation

All

### JSF version

ALL?

### Browser(s)

ALL?

### PR DESCRIPTION
**Pull request by melloware**
cc @newk5

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java [hunk 1]
```diff
@@ -78,7 +80,7 @@ protected void encodeOnClick(FacesContext context, UIComponent source, MenuItem
 
             UIForm form = ComponentTraversalUtils.closestForm(context, source);
             if (form == null) {
-                throw new FacesException("MenuItem must be inside a form element");
+                LOGGER.log(Level.FINE, "MenuItem should be inside a form element");
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java]: we should use the same string like in AjaxRequestBuilder: 
```
Component '" + component.getClientId(context)
 + "' should be inside a form or should reference a form via its form attribute."
 + " We will try to find a fallback form on the client side.
```

File: primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js [hunk 2]
```diff
@@ -102,6 +102,22 @@
             });
         },
 
+        /**
+         * Gets the form by id or the closest form if the id is not a form itself.
+         * @param {string} id ID of the component to get the closest form.
+         * @return {JQuery} the form or NULL if no form found
+         */
+        getForm: function(id) {
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js]: we should name it "getClosestForm"

in AJAX we also have a fallback for the first form in DOM, this should not be used here

**Comment by melloware** [comment]
OK changes made if you want to re-review.
