### PR TITLE
FIX #10876: inputtextarea primefaces-overlay-target setting

### LINKED ISSUE #10876: InputTextarea: Autocomplete overlay panel is behind dialog
### Describe the bug

If the inputtextarea with active autocomplete is used in the dialog, then the autocomplete overlay panel is displayed behind dialog after clicking into inputtexarea element.

image

Could you fixed it the same way like in forms.selectcheckboxmenu, please? using triggers?
```
    init: function(cfg) {
        this.triggers = this.jq;
    }

    _render: function() {
        this.triggers.data('primefaces-overlay-target', true);
    }
```

### Reproducer

1. make inputtextarea in dialog with active autocomplete
2. enter some text
3. autocomplete overlay panel with suggestions is displayed
4. click intu inputtextarea element
5. autocomplete overlay panel is behind dialog

### Expected behavior

The autocomplete overlay is visible when clicking into inputtextarea element.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3.20

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by vonnai**
Fix #10876

### CODE REVIEW

**Comment by melloware** [comment]
I bound it if you just make the comment "Fix #xxx" it automatically joins it.

File: primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js [hunk 1]
```diff
@@ -55,6 +55,9 @@ PrimeFaces.widget.InputTextarea = PrimeFaces.widget.DeferredWidget.extend({
         //autoComplete
         if(this.cfg.autoComplete) {
             this.setupAutoComplete();
+            if (!this.jq.hasClass('ui-state-disabled')) {
+                this.jq.data('primefaces-overlay-target', true);
+            }
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js]: I think a better place for this is the last line of of the `setupAutoComplete` method.

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
