### PR TITLE
Fix #10325 - DataExporter: xlsx export and ui:repeat inside columnGroup

### LINKED ISSUE #10325: DataExporter: problems with xlsx export and ui:repeat inside columnGroup
### Describe the bug

I tried dataExporter on table with ui:repeat inside columnGroup. Header doesn't export to xlsx at all.
Seems like problem in method ColumnAware::forEachColumnGroupRow.

I overridden the method forEachColumnGroupRow in class MyDataTable.
You can uncomment lines in faces-config.xml to start using this overriden method.
With this changes header exports to xlsx more or less ok.

### Reproducer

[export-to-excel-repeat.zip](https://github.com/primefaces/primefaces/files/11992380/export-to-excel-repeat.zip)

1. Start application
2. Go to test page
3. Press xlsx button

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by Rapster**
Fix #10325

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java [hunk 1]
```diff
@@ -165,11 +164,29 @@ default boolean forEachColumnGroupRow(FacesContext context, ColumnGroup cg, bool
...
             return false;
         }
-        for (UIComponent component : cg.getChildren()) {
-            if (!(component instanceof Row)) {
+        for (UIComponent child : cg.getChildren()) {
+            if (child.getClass().getName().endsWith("UIRepeat")) {
+                VisitContext visitContext = VisitContext.createVisitContext(context, null,
+                        ComponentUtils.VISIT_HINTS_SKIP_UNRENDERED);
+                return child.visitTree(visitContext, (ctx, target) -> {
+                    if (target.getClass().getName().endsWith("UIRepeat")) {
```
Comment (melloware) [inline primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java]: I assume you want to change this to your new utility method?

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
