### PR TITLE
Fix #11429: Message tooltip fix

### LINKED ISSUE #11429: Message: tooltip is not shown in 14.0.0-RC1
### Describe the bug

Message in tooltip display mode is not shown.

### Reproducer

1.Run 
```
wget https://github.com/primefaces/primefaces/archive/refs/tags/14.0.0-RC1.tar.gz -O- | tar -x -z -C /tmp/ 
cd /tmp/primefaces-14.0.0-RC1/
mvn clean install 
cd primefaces-showcase
mvn -Ddev
```
2.Open http://localhost:8080/showcase/ui/message/messages.xhtml
3.Click Submit button

### Expected behavior

Tooltip should be shown - it works on https://www.primefaces.org/showcase/ui/message/messages.xhtml

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11429: Message tooltip fix

### CODE REVIEW

File: primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js [hunk 1]
```diff
@@ -29,7 +30,7 @@ PrimeFaces.widget.Message = PrimeFaces.widget.BaseWidget.extend({
               target.data('tooltip', text);
            }
 
-           target.attr('aria-describedby', this.id + '_error-detail');
+           target.attr('aria-describedby', this.id + '_error-' + + summaryOrDetail);
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js:33]: `+ +`?

File: primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js [hunk 2]
```diff
@@ -20,7 +20,8 @@ PrimeFaces.widget.Message = PrimeFaces.widget.BaseWidget.extend({
     init: function(cfg) {
         this._super(cfg);
 
-        var text = this.jq.find('.ui-message-error-detail').text();
+        var summaryOrDetail = this.jq.find('.ui-message-error-summary').length ? "summary" : "detail";
+        var text = this.jq.find('.ui-message-error-' + summaryOrDetail).text();
```
Comment (tandraschko) [inline primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js:24]: TBH i dont like that code as you cant search via IDE for "ui-message-error-detail"
