### PR TITLE
Fix #9038: Other UI commands supporting disableOnAjax

### LINKED ISSUE #9038: UICommand: reenabled after disableOnAjax when disabled on server side in request
### Describe the bug

When a command button action willingly sets the disabled state of the button, the visual state of the button is still enabled. After another page update, this is reflected properly.

### Reproducer

Please clone: https://github.com/stolp/primefaces-test/tree/PF-9038

Form:
```xhtml
<h:form id="frmTest">

 <p>It is expected, that the first button disables itself after its action, but it doesn't.</p>
 <p>The second button only refreshes the form to prove that the disabled setting is indeed present.</p>

 <p:commandButton disabled="#{testView.isDisabled()}"
   value="Button Action disables this button" action="#{testView.sleep()}" partialSubmit="true" update="@form" />

 <p:commandButton
   value="Button Action updates the page" action="#{testView.refresh()}" partialSubmit="true" update="@form" />
</h:form>
```

### Expected behavior

The button state should be disabled after the action finishes.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC2

### Theme

any

### JSF implementation

All

### JSF version

2.3

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9038

### CODE REVIEW

File: primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java [hunk 1]
```diff
@@ -174,7 +174,7 @@ protected void encodeScript(FacesContext context, CommandButton button) throws I
         WidgetBuilder wb = getWidgetBuilder(context);
         wb.init("CommandButton", button)
             .attr("disableOnAjax", button.isDisableOnAjax(), true)
-            .attr("disabled", button.isDisabled(), false);
+            .attr("disabledAttr", button.isDisabled(), false);
```
Comment (jepsar) [inline primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java:177]: `this.cfg.disabled` was already used in `SplitButton` and `MenuButton`, so I opted to rename it on each component for consistency.

**Review by melloware — APPROVED** [review]
