### PR TITLE
Fix #7617 fixed NPEs in FileUpload

### LINKED ISSUE #7616: FileUpload: Simple auto upload throws exception while size limit is reached
I tried to use the simple file upload component with auto=true, and an error occurs while I sent a file that reaches the max upload size.  Debugging the code I see that field `part` inside `NativeUploadedFile` class is null.

**Reproducer**
Clone repository https://github.com/garcia-jj/primefaces-upload-issue in order to reproduce that issue. The page http://127.0.0.10:8080/primefaces-test/basic.xhtml contains the test case.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Wildfly 21, Mojarra
 - Affected browsers: tested on Chorme and Firefox, but I guess this is not a browser issue

**To Reproduce**
1. Go to 'http://127.0.0.10:8080/primefaces-test/basic.xhtml'
2. Click on '+ Choose' button, then select a file with size greater than 1kb.
4. See error on logs. A NullPointerException will occurs.
```
Jul 21, 2021 3:35:56 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NullPointerException: Cannot invoke "javax.servlet.http.Part.getSize()" because "this.part" is null
        at org.primefaces.model.file.NativeUploadedFile.getSize(NativeUploadedFile.java:70)
        at org.primefaces.model.file.UploadedFileWrapper.getSize(UploadedFileWrapper.java:74)
        at org.primefaces.util.FileUploadUtils.tryValidateFile(FileUploadUtils.java:299)
        at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:85)
```

**Expected behavior**
The file upload sucessfully.

**Example XHTML**
```html
<p:growl id="messages" showDetail="true"/>

<div class="card">
    <h5>Single</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" auto="true"
                      process="@this" update="messages"
                      sizeLimit="1"
                      listener="#{fileUploadView.handleFileUpload}"/>
    </h:form>
</div>

<div class="card">
    <h5>Multiple</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true"
                      auto="true"
                      sizeLimit="1"
                      process="@this" update="messages"
                      listener="#{fileUploadView.handleFilesUpload}"/>
    </h:form>
</div>
```

**Example Bean**
```java
@Named
@RequestScoped
public class FileUploadView {

	private UploadedFile file;
	private UploadedFiles files;

	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

	public UploadedFiles getFiles() {
		return files;
	}

	public void setFiles(UploadedFiles files) {
		this.files = files;
	}

	public void handleFileUpload(FileUploadEvent event) {
		FacesMessage message = new FacesMessage("Successful", event.getFile().getFileName() + " is uploaded.");
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	public void handleFilesUpload(FilesUploadEvent event) {
		for (UploadedFile f : event.getFiles().getFiles()) {
			FacesMessage message = new FacesMessage("Successful", f.getFileName() + " is uploaded.");
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}
}
```

Thank U

### LINKED ISSUE #7617: FileUpload: several NPEs
Follow up of #6428 
`FileUpload` throws NPE at several places. `<p:fileUpload mode=simple auto=true fileLimit=x sizeLimit=y allowTypes=z .../>` sends empty parts if fileLimit, sizeLimit or allowTypes are violated. NPEs occur with both UPLOADER=native and UPLOADER=commons
Example:
```
java.lang.NullPointerException
        at org.primefaces.model.file.NativeUploadedFile.getSize(NativeUploadedFile.java:70)
        at org.primefaces.model.file.UploadedFileWrapper.getSize(UploadedFileWrapper.java:74)
        at org.primefaces.util.FileUploadUtils.tryValidateFile(FileUploadUtils.java:299)
        at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:85)
        at javax.faces.component.UIInput.validate(UIInput.java:1021)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1318)
        at javax.faces.component.UIInput.processValidators(UIInput.java:733)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:608)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIForm.visitTree(UIForm.java:355)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```
```
java.lang.NullPointerException
        at org.primefaces.component.fileupload.CommonsFileUploadDecoder.createUploadedFile(CommonsFileUploadDecoder.java:53)
        at org.primefaces.component.fileupload.CommonsFileUploadDecoder.createUploadedFile(CommonsFileUploadDecoder.java:36)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decodeSimple(AbstractFileUploadDecoder.java:75)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decode(AbstractFileUploadDecoder.java:51)
        at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:64)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
        at javax.faces.component.UIInput.decode(UIInput.java:798)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIForm.visitTree(UIForm.java:355)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
        at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```
**Reproducer**
[PF-6428-native.zip](https://github.com/primefaces/primefaces/files/6858249/PF-6428-native.zip)
[PF-6428-commons.zip](https://github.com/primefaces/primefaces/files/6858250/PF-6428-commons.zip)

**Environment:**
 - PF Version: _10.0_
 - JSF + version: Mojarra 2.3.x, MyFaces 2.3.x
 - Affected browsers: ALL

**To Reproduce**
1. Go to 'http://localhost:8080/primefaces-test/'
2. Chose file/files wich violate description above the widget
3. See error in log file (in GUI no error is shown)

**Expected behavior**
No NPEs in log.

**Example XHTML**
```html
<h:form id="frmTest">
   <p:fileUpload mode="simple" skinSimple="true" auto="true" fileLimit=x sizeLimit=y allowTypes=z />
</h:form>
```

**Example Bean**
see reproducer

(I've created some more FileUpload integration tests where I stumbled across the NPEs. I'll create a PR if these tests are somewhat stable. But that's not the case yet.)

### PR DESCRIPTION
**Pull request by wal-jan**
FileUpload now ignores empty parts in request (both in native and commons uploader).

NPE found in commons uploader actually was a configuration error. So I added a warning log output in that case.

Added some more FileUpload integration tests which required some tweeks in the projects configuration. Now it's possible to pick native or commons uploader via profile (default is auto). 

I think exception reported in #7616 is also fixed.

### CODE REVIEW

File: primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/fileupload/FileUploadView.java [hunk 1]
```diff
@@ -58,9 +66,43 @@ public void doFileUpload(UploadedFile uf) {
...
+        String allowTypes = getAllowTypes();
+        return allowTypes == null || allowTypes.length() < 3 || // JS RegExp has at least 3 chars
+                Pattern.compile(allowTypes.substring(1, allowTypes.length() - 1))
+                .matcher(fileName).find();
+    }
+
+    private String getAllowTypes() {
+        // some tests break in Mojarra when binding is used
+        // search for first FileUpload component in component tree (assuming this is the only one)
+        if (_allowTypes == null) {
```
Comment (tandraschko) [inline primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/fileupload/FileUploadView.java:85]: wouldnt it be better to use findComponent by id?

File: primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java [hunk 2]
```diff
@@ -44,18 +48,19 @@ public String getName() {
...
                 .map(p -> new CommonsUploadedFile(p, sizeLimit))
                 .collect(Collectors.toList());
     }
 
     @Override
     protected UploadedFile createUploadedFile(MultipartRequest request, FileUpload fileUpload, String inputToDecodeId) {
         FileItem file = request.getFileItem(inputToDecodeId);
-        if (file != null && !file.getName().isEmpty()) {
-            return new CommonsUploadedFile(file, fileUpload.getSizeLimit());
+        if (file == null || file.getName().isEmpty()) {
```
Comment (tandraschko) [inline primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java]: shouldnt we use our LangUtils.isBlank?

File: primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/fileupload/FileUploadView.java (hunk 1 above)
Comment (wal-jan) [reply primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/fileupload/FileUploadView.java:85]: I do not have a clear opinion. All FileUpload tests are backed by the same two beans `FileUploadHandler` and `FileUploadView` At the moment all xhtml files contain a single p:fileUpload component which do have all the same id="form:fileupload". So yes, findComponent can be used.
Because it's less and simpler code I'll change that to findComponent.

File: primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java (hunk 2 above)
Comment (wal-jan) [reply primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java]: Thanks for the advice, I'll change that

**Comment by tandraschko** [comment]
great contribution, thanks!

**Comment by wal-jan** [comment]
@christophs78 to check FileUpload in Mojarra, Myfaces, Commons, and Native mode, I created a Github workflow file. I do not know how to test this. Maybe you can add it to the primeface project.
[nightly-file.upload.yml.zip](https://github.com/primefaces/primefaces/files/6877709/nightly-file.upload.yml.zip)

**Comment by christophs78** [comment]
For testing you can add nightly-file.upload.yml to any (draft-)PR.
Just temporarily replace lines 3-5 (on, schedule, cron) with `on: [push, pull_request]`.
And please change the name (line 1).
