### PR TITLE
Fix #8071: SelectCheckBoxMenu resetValue

### LINKED ISSUE #8071: DataTable: clearFilters doesnt work for complex input widgets like p:selectOneMenu
**Describe the defect**
When using `p:selectOneMenu` in `DataTable` as custom filter, a call to `DataTable#clearFilters()` resets the filter of the `DataTable` but not the displayed value of the `p:selectOneMenu`. It works as expected when using `h:selectOneMenu` instead.

**Reproducer**
See [primefaces-test.zip](https://github.com/primefaces/primefaces/files/7520464/primefaces-test.zip).

**Environment:**
 - PF Version: _11.0.0-RC2_
 - JSF + version: _Mojarra 2.3.14.payara-p2_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start the reproducer.
2. Select 'true' in column _c1_
3. Select 'true' in column _c2_
4. Click the filter reset button.
5. Filter for `DataTable` is reset, value of _c1_ filter is reset, but value of _c2_ filter is still 'true'.

**Expected behavior**
Value of custom filter with `p:selectOneMenu` should be reset too when calling `DataTable#clearFilters()`.

**Referenced issues**
#6669, #6670

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko 2 things.

1. I realize its SelectCheckboxMenu we use a lot like this...

```xml
<f:facet name="filter">
	<p:selectCheckboxMenu id="chkProfileStatusFilter" label="All" filter="true" filterMatchMode="startsWith"
						updateLabel="true">
		<p:ajax event="change" process="@this" oncomplete="PF('organizerTable').filter();" />
		<p:ajax event="toggleSelect" process="@this" oncomplete="PF('organizerTable').filter();" />
		<f:selectItems value="#{profileStatusFilterOptions}" />
	</p:selectCheckboxMenu>
</f:facet>
```

2. I added the `resetValue` using the custom code we have already been using but unfortunately it requires the dialog be visible. `Unselects all available options. Note that this required the overlay panel to be visible, use `show` for that.`

### CODE REVIEW

**Comment by tandraschko** [comment]
why must it be visible? makes it a bit weird

**Comment by melloware** [comment]
It is what the note on the `uncheckAll` and `checkAll` methods say.... not sure why.

**Comment by melloware** [comment]
```
/**
     * Selects all available options. Note that this required the overlay panel to be visible, use `show` for that.
     */
    checkAll: function() {
```

**Comment by tandraschko** [comment]
maybe its such a lazy init/load thing like in selectOneMenu?

**Comment by melloware** [comment]
Yep I think that is it and the code has `panel.is(:visible)` checks in the checkAll and unCheckAll.

**Comment by tandraschko** [comment]
we should really recheck this 
it doesnt make sense to show first to uncheck
also UI will flicker

**Comment by FlipWarthog** [comment]
@melloware Similar to the SelectCheckBoxMenu itself needing to be visible for uncheckAll to work, if `filter="true"` and a filter is applied, unckeckAll won't catch those filtered out values. I think we needed to grab the `filterInput` and clear its value.

**Comment by melloware** [comment]
Agreed we need a deeper diver on this.

**Comment by melloware** [comment]
@FlipWarthog maybe we can deep dive together on this and get this working.  This would be a nice addition.

File: primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js [hunk 1]
```diff
@@ -217,6 +215,7 @@ PrimeFaces.widget.SelectCheckboxMenu = PrimeFaces.widget.BaseWidget.extend({
      */
     renderPanel: function() {
         this.panel = $('<div id="' + this.panelId + '" class="ui-selectcheckboxmenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-input-overlay" role="dialog"></div>');
+        this.transition = PrimeFaces.utils.registerCSSTransition(this.panel, 'ui-connected-overlay');
```
Comment (melloware) [inline primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js:218]: This was a bug. The transition should be created right after the panel is created.  There was actually a bug with `dynamic=true` because of this.

**Comment by melloware** [comment]
OK I cleaned it up and got it all working.  You no longer need to call Show or Hide to uncheck or check all the items. That was all around `dynamic="true"` which was actually broken anyway because the CSS transition was not working in Dynamic Mode.

So I have cleaned all this up and tested `dynamic` mode and non-dynamic.  I then tested widget methods `checkAll`, `uncheckAll` and the new `resetValue` all of them are working properly and do NOT need to display the dialog.

**Comment by FlipWarthog** [comment]
@melloware but do we get any new integration tests for this? ;)

**Comment by melloware** [comment]
> @melloware but do we get any new integration tests for this? ;)

That's a bigger task as there isn't even a base Selenium Component for this yet in the suite and 0 tests.    I will open a separate ticket.

**Comment by tandraschko** [comment]
if you tested all cases -> +1

**Review by FlipWarthog — APPROVED** [review]
Tested this in our production code and its working as expected.
